// lib/i18n/ar.js
// Arabic localization. Must define the exact same `strings` keys and the
// exact same FAQ `id`s as lib/i18n/en.js -- lib/i18n.js falls back to en.js
// for anything missing here, and test-i18n.js checks the key sets match.
(function () {
  const strings = {
    "common.needHelp": "هل تحتاج إلى مساعدة؟",
    "common.languageLabel": "اللغة",
    "common.back": "رجوع",
    "common.cancel": "إلغاء",
    "common.copy": "نسخ",
    "common.send": "إرسال",
    "common.swap": "مبادلة",
    "common.buy": "شراء",
    "common.livePrices": "الأسعار المباشرة",
    "common.reject": "رفض",
    "common.passwordPlaceholder": "كلمة المرور",
    "common.confirmPasswordPlaceholder": "تأكيد كلمة المرور",
    "common.newPasswordLabel": "كلمة مرور جديدة (8 أحرف على الأقل)",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "عنوان العملة (0x...)",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "العملة الأصلية للشبكة",

    "onboarding.title": "أهلاً بك",
    "onboarding.subtitle": "أعدّ محفظتك للبدء.",
    "onboarding.createBtn": "إنشاء محفظة جديدة",
    "onboarding.importBtn": "استيراد محفظة موجودة",

    "create.title": "إنشاء محفظة",
    "create.passwordLabel": "كلمة مرور جديدة (8 أحرف على الأقل)",
    "create.passwordWarning": "تُستخدم كلمة المرور هذه لفتح محفظتك على هذا الجهاز فقط. لا يمكن استعادتها إذا نسيتها -- عبارة الاسترداد وحدها هي القادرة على استرجاع أموالك.",
    "create.continueBtn": "متابعة",
    "create.backupWarning": "دوّن عبارة الاسترداد هذه واحتفظ بها في مكان آمن. أي شخص يحصل عليها يمكنه الاستيلاء على كل ما في هذه المحفظة. لا يمكن لـ Token Exchange استعادتها نيابةً عنك.",
    "create.backupCheckbox": "لقد حفظت عبارة الاسترداد الخاصة بي",
    "create.finishBtn": "إنهاء",

    "import.title": "استيراد محفظة",
    "import.mnemonicLabel": "عبارة الاسترداد (12 أو 24 كلمة)",
    "import.mnemonicPlaceholder": "كلمة1 كلمة2 كلمة3 ...",
    "import.submitBtn": "استيراد",

    "unlock.title": "فتح القفل",
    "unlock.submitBtn": "فتح القفل",
    "unlock.resetInsteadBtn": "إعادة تعيين المحفظة بدلاً من ذلك",

    "main.settingsTitle": "الإعدادات",
    "main.portfolioLabel": "الرصيد الإجمالي",
    "main.addAccountOption": "+ إضافة حساب",
    "main.tokensTitle": "العملات",
    "main.addTokenBtn": "+ إضافة عملة",
    "main.tokensEmpty": "لم تتم إضافة أي عملات بعد -- اضغط على «+ إضافة عملة» وأدخل عنوان العقد لتتبع عملة.",
    "main.networkLabel": "الشبكة",
    "main.balanceFetchErrorPrefix": "تعذّر جلب الرصيد: ",
    "main.watchOnlySuffix": "(مراقبة فقط)",
    "main.watchOnlyNotice": "أنت تعرض عنوانًا للمراقبة فقط -- لا يوجد مفتاح خاص له في هذه المحفظة، لذا يتم تعطيل الإرسال والمبادلة هنا.",

    "tokens.loadError": "تعذّر تحميل الرصيد",
    "tokens.removeTitle": "إزالة",

    "addToken.title": "إضافة عملة",
    "addToken.description": "أدخل عنوان عقد العملة على الشبكة الحالية. لا تضف إلا عملة حصلت على عنوان عقدها من مصدر تثق به -- فالمحفظة لا يمكنها التمييز بين عملة حقيقية وأخرى مزيفة تحمل الاسم نفسه.",
    "addToken.addressLabel": "عنوان عقد العملة",
    "addToken.lookupBtn": "بحث",
    "addToken.nameLabel": "الاسم:",
    "addToken.symbolLabel": "الرمز:",
    "addToken.decimalsLabel": "الخانات العشرية:",
    "addToken.confirmBtn": "أضِف إلى محفظتي",
    "addToken.invalidAddress": "أدخل عنوان عقد صالحًا.",
    "addToken.noName": "(بلا اسم)",
    "addToken.swapUnavailableSuffix": " (المبادلة غير متاحة)",

    "prices.description": "أسعار الدولار الأمريكي مأخوذة من واجهة CoinGecko العامة. لأغراض إعلامية فقط -- لا يتم إرسال أي بيانات عن محفظتك للحصول عليها.",
    "prices.loading": "جارٍ التحميل...",
    "prices.naText": "غير متاح",
    "prices.tabCrypto": "العملات الرقمية",
    "prices.tabCurrencies": "العملات",
    "prices.searchPlaceholder": "بحث...",
    "prices.currenciesNote": "قيمة وحدة واحدة من كل عملة بعملة العرض التي اخترتها.",
    "prices.noResults": "لا توجد نتائج.",
    "prices.viewCoin": "عرض {name}",
    "prices.volShort": "الحجم",
    "coin.swapBtn": "مبادلة إلى {symbol}",
    "coin.swapHint": "ستختار من الشاشة التالية أيًّا من أصولك تريد الدفع به.",
    "coin.swapNeedsWallet": "افتح محفظتك للمبادلة.",
    "coin.swapNoRouter": "المبادلة غير مفعّلة على هذه الشبكة بعد.",
    "coin.swapUnavailableNetwork": "لا يمكن مبادلة {symbol} على {network} بعد. يجب أن تكون العملة الأصلية للشبكة أو رمزًا أضفته عبر إضافة رمز.",
    "coin.holding": "لديك {amount} {symbol}",
    "coin.statsTitle": "إحصاءات السوق",
    "coin.aboutTitle": "نبذة",
    "coin.aboutUnavailable": "لا يتوفر وصف حاليًا.",
    "coin.marketCap": "القيمة السوقية",
    "coin.volume24h": "حجم 24 ساعة",
    "coin.high24h": "أعلى سعر خلال 24 ساعة",
    "coin.low24h": "أدنى سعر خلال 24 ساعة",
    "coin.supply": "المعروض المتداول",
    "coin.ath": "أعلى سعر على الإطلاق",
    "coin.viewCoingecko": "عرض على CoinGecko",
    "coin.loadError": "تعذّر تحميل المزيد من التفاصيل عن هذه العملة الآن.",
    "coin.chartUnavailable": "الرسم البياني غير متاح حاليًا.",
    "swap.customAddressOption": "رمز آخر (الصق العنوان)...",

    "buy.title": "شراء عملات رقمية",
    "buy.description1": "خدمة الشراء مقدَّمة عبر Transak، وهي خدمة خارجية منفصلة -- لا تطّلع Token Exchange مطلقًا على بيانات الدفع الخاصة بك.",
    "buy.noThirdPartyCallout": "هل تملك بالفعل بعض العملات المشفّرة؟ تجاوز Transak بالكامل -- بادلها مباشرةً على السلسلة بما تحتاجه، دون طرف ثالث ودون تسجيل.",
    "buy.noThirdPartySwapBtn": "بادل بدلاً من ذلك",
    "buy.continueBtn": "المتابعة إلى Transak",
    "buy.pickerTitle": "اختر ما تريد شراءه",
    "buy.pickerSearchPlaceholder": "ابحث عن العملات بالاسم أو الرمز",
    "buy.pickerCurrencies": "العملات",
    "buy.pickerCrypto": "العملات المشفّرة",
    "buy.changeCoinBtn": "تغيير العملة",

    "support.title": "المساعدة والدعم",
    "support.description": "اطرح سؤالًا أو اضغط على أحد المواضيع أدناه. يعمل هذا بالكامل على جهازك -- لا يُرسَل أي شيء تكتبه هنا إلى أي مكان.",
    "support.inputPlaceholder": "اكتب سؤالاً...",

    "send.title": "إرسال",
    "send.assetLabel": "الأصل",
    "send.assetToken": "عملة (أدخل عنوان العقد)",
    "send.tokenAddressPlaceholder": "عنوان عقد العملة (0x...)",
    "send.toLabel": "إلى عنوان",
    "send.amountLabel": "المبلغ",
    "send.speedSlow": "بطيء",
    "send.speedStandard": "قياسي",
    "send.speedFast": "سريع",
    "send.invalidRecipient": "أدخل عنوان مستلم صالحًا.",
    "send.invalidTokenAddress": "أدخل عنوان عقد عملة صالحًا.",
    "send.sentStatus": "تم الإرسال! رقم العملية: {txHash}",
    "send.poisonWarning": "يشبه هذا العنوان كثيرًا عنوانًا استخدمته من قبل ({match}) لكنه ليس نفسه -- يبدأ وينتهي بنفس الطريقة بينما يختلف المنتصف تمامًا. هذا نمط احتيال شائع (\"تسميم العناوين\") حيث يُزرع عنوان مشابه في سجلك على أمل أن تنسخ العنوان الخاطئ. تحقق من كل حرف قبل الإرسال.",

    "swap.unsupportedWarning": "المبادلة غير مفعّلة بعد على هذه الشبكة -- لا يوجد موجّه (router) موثّق مُعدّ لها. أضِف واحدًا من الإعدادات ← الشبكات أولاً.",
    "swap.fromLabel": "من",
    "swap.toLabel": "إلى",
    "swap.getQuoteBtn": "احصل على عرض سعر",
    "swap.appFeeLine": "رسوم التطبيق ({percent}): {amount}",
    "swap.netAmountLine": "المبلغ الصافي الذي تمت مبادلته: {amount}",
    "swap.estimatedOutLine": "المتوقع استلامه: {amount}",
    "swap.slippageLabel": "نسبة تحمّل الانزلاق السعري",
    "swap.approveBtn": "الموافقة على العملة أولاً",
    "swap.approvingStatus": "جارٍ الموافقة...",
    "swap.approvedStatus": "تمت الموافقة. يمكنك المبادلة الآن.",
    "swap.sendingStatus": "جارٍ إرسال الرسوم والمبادلة...",
    "swap.swappedStatus": "تمت المبادلة! رسوم العملية: {feeTx} | عملية المبادلة: {tx}",
    "swap.feeTxNa": "غير متاح",

    "settings.title": "الإعدادات",
    "settings.addAccountBtn": "إضافة حساب",
    "settings.importKeyBtn": "استيراد مفتاح خاص",
    "settings.addWatchBtn": "إضافة عنوان للمراقبة فقط",
    "settings.approvalsBtn": "إدارة الموافقات",
    "settings.addNetworkBtn": "إضافة شبكة",
    "settings.viewSeedBtn": "عرض عبارة الاسترداد",
    "settings.helpBtn": "المساعدة والدعم",
    "settings.lockBtn": "قفل المحفظة",
    "settings.resetBtn": "إعادة تعيين المحفظة",

    "importKey.title": "استيراد مفتاح خاص",
    "importKey.description": "هذا يضيف حسابًا منفصلاً إلى هذه المحفظة من مفتاح خاص خام، وليس من عبارة الاسترداد الخاصة بك -- احتفظ بنسخة احتياطية منه بشكل منفصل، لأن عبارة الاسترداد الخاصة بك لن تستعيده. لا تشارك المفتاح الخاص مع أي شخص أبدًا؛ فأي شخص يملكه يمكنه إنفاق كل ما في ذلك الحساب.",
    "importKey.placeholder": "المفتاح الخاص 0x",

    "addWatch.title": "إضافة عنوان للمراقبة فقط",
    "addWatch.description": "يتتبع رصيد العنوان وعملاته المشفرة ونشاطه دون الاحتفاظ بمفتاحه -- لا يوجد هنا ما يمكن التوقيع به، لذا يظل الإرسال والمبادلة معطلين له. مفيد لمتابعة عنوان تخزين بارد أو محفظة أجهزة من هنا.",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "تسمية (اختياري)",
    "addWatch.submitBtn": "إضافة",

    "approvals.title": "إدارة الموافقات",
    "approvals.description": "يعرض موافقات إنفاق العملات لموجّه المبادلة الخاص بهذه المحفظة، بالإضافة إلى بحث يدوي عن أي عملة ومُنفِق آخر. الإلغاء يعيد الموافقة إلى صفر -- لن يتمكن المُنفِق بعدها من تحريك تلك العملة نيابةً عنك حتى توافق مجددًا.",
    "approvals.emptyText": "لم يتم العثور على موافقات للعملات التي أضفتها.",
    "approvals.loading": "جارٍ التحقق من الموافقات...",
    "approvals.manualHeading": "التحقق من موافقة محددة",
    "approvals.tokenPlaceholder": "عنوان عقد العملة (0x...)",
    "approvals.spenderPlaceholder": "عنوان عقد المُنفِق (0x...)",
    "approvals.checkBtn": "تحقق",
    "approvals.tokenLabel": "العملة:",
    "approvals.spenderLabel": "المُنفِق:",
    "approvals.allowanceLabel": "الموافقة:",
    "approvals.revokeBtn": "إلغاء",
    "approvals.revokingBtn": "جارٍ الإلغاء...",
    "approvals.rowError": "تعذّر التحقق من هذا -- حاول مرة أخرى بعد قليل.",

    "addNetwork.title": "إضافة شبكة",
    "addNetwork.namePlaceholder": "اسم الشبكة",
    "addNetwork.chainIdPlaceholder": "معرّف السلسلة (رقم)",
    "addNetwork.rpcPlaceholder": "رابط RPC",
    "addNetwork.symbolPlaceholder": "رمز العملة الأصلية",
    "addNetwork.explorerPlaceholder": "رابط مستكشف الكتل (اختياري)",
    "addNetwork.routerPlaceholder": "عنوان موجّه المبادلة الموثّق (اختياري)",
    "addNetwork.routerWarning": "لا تُدخل عنوان الموجّه إلا إذا تحققت منه بنفسك من الوثائق الرسمية للمشروع أو من مستكشف كتل السلسلة. اتركه فارغًا إن لم تكن متأكدًا -- ستبقى المبادلة معطّلة على هذه الشبكة إلى أن تضيف واحدًا.",
    "addNetwork.addBtn": "إضافة",

    "viewSeed.title": "عبارة الاسترداد",
    "viewSeed.passwordPlaceholder": "أدخل كلمة المرور للإظهار",
    "viewSeed.revealBtn": "إظهار",

    "reset.title": "إعادة تعيين المحفظة",
    "reset.warning": "سيؤدي هذا إلى حذف المحفظة المشفّرة من هذا المتصفح. تأكد من أن لديك نسخة احتياطية من عبارة الاسترداد -- لا يمكن التراجع عن هذا الإجراء.",
    "reset.confirmBtn": "نعم، احذف كل شيء",

    "approve.unlockTitle": "افتح القفل للمتابعة",
    "approve.unlockOriginText": "{origin} يطلب الوصول.",
    "approve.connectTitle": "طلب اتصال",
    "approve.connectWantsText": "{origin} يريد الاتصال بمحفظتك.",
    "approve.accountLabel": "الحساب: ",
    "approve.acceptConnectBtn": "اتصال",
    "approve.txTitle": "طلب معاملة",
    "approve.toLabel": "إلى:",
    "approve.valueLabel": "القيمة:",
    "approve.dataLabel": "البيانات:",
    "approve.txWarning": "لا توافق على هذا إلا إذا كنت تثق بالموقع وتفهم ما يطلب منك توقيعه.",
    "approve.confirmBtn": "تأكيد",
    "approve.signTitle": "طلب توقيع",
    "approve.signBtn": "توقيع",
    "approve.addNetTitle": "طلب إضافة شبكة",
    "approve.addNetNameLabel": "الاسم:",
    "approve.addNetChainIdLabel": "معرّف السلسلة:",
    "approve.addNetRpcLabel": "RPC:",
    "approve.addNetWarning": "الشبكة التي يقترحها هذا الموقع لا تملك موجّه مبادلة موثّقًا. ستبقى المبادلة معطّلة عليها إلى أن تضيف واحدًا بنفسك من الإعدادات.",
    "approve.addNetBtn": "إضافة الشبكة",
    "approve.switchNetTitle": "طلب تبديل الشبكة",
    "approve.switchNetText": "يريد {origin} تبديل محفظتك من {from} إلى {to}.",
    "approve.switchNetWarning": "بدّل فقط إذا كنت تتوقع ذلك. ستُرسل المعاملات التي توافق عليها بعد ذلك على الشبكة الجديدة.",
    "approve.switchNetBtn": "تبديل الشبكة",
    "approve.contractCreation": "(إنشاء عقد)",
    "approve.nativeSuffix": " (أصلية)",
    "approve.decodedLoading": "جارٍ قراءة ما يفعله هذا فعليًا...",
    "approve.decodedTransferLine": "سيؤدي هذا إلى تحويل {amount} إلى {to}.",
    "approve.decodedApproveLine": "سيؤدي هذا إلى الموافقة على إنفاق {to} لمبلغ {amount}.",
    "approve.decodedUnlimited": "غير محدود {symbol}",
    "approve.decodedThisToken": "هذه العملة",
    "approve.decodedRawUnitsSuffix": " وحدات خام (تعذّر تأكيد عدد الخانات العشرية لهذه العملة)",
    "approve.decodedGenericIntro": "يستدعي هذا \"{fn}\" على العقد أعلاه مع:",

    "loading.text": "جارٍ التحميل...",

    "home.tabHome": "الرئيسية",
    "home.tabAssets": "الأصول",
    "home.tabActivity": "النشاط",
    "home.tabSend": "إرسال",
    "home.tapToContinue": "اضغط للمتابعة",
    "home.continueBtn": "متابعة",

    "activity.title": "النشاط",
    "activity.subtitle": "سجل محلي لعمليات الإرسال من هذه المحفظة، بالإضافة إلى التحويلات الواردة التي لاحظها هذا الجهاز -- لا شيء هنا يُجلب من خادم.",
    "activity.empty": "لا يوجد نشاط بعد -- ستظهر هنا عمليات الإرسال (والتحويلات الواردة التي يلاحظها هذا الجهاز).",
    "activity.sentLabel": "تم إرسال {amount} {asset}",
    "activity.receivedLabel": "تم استلام {amount} {asset}",
    "activity.toLabel": "إلى {address}",
    "activity.statusSent": "تم الإرسال",
    "activity.tabSends": "الإرسال",
    "activity.tabSwaps": "المبادلات",
    "activity.swapsSubtitle": "سجل محلي للمبادلات التي أُجريت من هذه المحفظة على هذا الجهاز -- لا يُجلب أي شيء هنا من خادم.",
    "activity.swapsEmpty": "لا توجد مبادلات بعد -- ستظهر هنا المبادلات التي تجريها من هذه المحفظة.",
    "activity.swapLabel": "تمت مبادلة {amountIn} {assetIn} مقابل نحو {amountOut} {assetOut}",
    "activity.statusSwapped": "تمت المبادلة",
    "activity.statusReceived": "تم الاستلام",
    "activity.receivedApproxNote": "تم اكتشافه من تغيّر في الرصيد -- تقريبي، لا يوجد رابط للمعاملة",
    "activity.viewOnExplorer": "عرض في مستكشف الكتل",

    "footer.nonCustodial": "غير احتجازية — مفاتيحك لا تغادر هذا الجهاز أبدًا",

    "errors.passwordTooShort": "يجب ألا تقل كلمة المرور عن 8 أحرف.",
    "errors.passwordMismatch": "كلمتا المرور غير متطابقتين.",
    "common.usernameLabel": "اسم المستخدم (يظهر عند فتح القفل)",
    "common.usernamePlaceholder": "اسم المستخدم",
    "unlock.welcomeBack": "مرحباً بعودتك، {name}",
    "errors.usernameRequired": "أدخل اسم مستخدم (حتى 30 حرفاً).",
    "onboarding.webNoticeSummary": "أنت تستخدم نسخة الموقع -- إضافة المتصفح أكثر أماناً للاستخدام اليومي.",
    "onboarding.webNoticeBody": "يشفّر هذا الموقع محفظتك ويحفظها في هذا المتصفح فقط (وليس في أي مكان آخر) -- لكنّ الموقع أسهل استهدافاً بالتصيّد وحيل DNS والنطاقات المزيفة من إضافة المتصفح المثبّتة، ولهذا لا تقدّم MetaMask والمحافظ المشابهة موقعاً يحتفظ بالمفاتيح أصلاً. استخدم الإضافة لكل ما لا تتحمل خسارته.",
    "onboarding.signInLink": "سجّل الدخول لاستعادة محفظة محفوظة نسخةً احتياطية",
    "signin.title": "تسجيل الدخول",
    "signin.intro": "استعد محفظة سبق أن حفظتها نسخةً احتياطية في حساب Token Exchange على جهاز آخر.",
    "account.title": "النسخ الاحتياطي للحساب",
    "account.intro": "اختياري: احفظ نسخة مشفّرة من هذه المحفظة في حساب Token Exchange لتتمكن من استعادتها على جهاز آخر. لا يرى Token Exchange كلمة مرورك ولا محفظتك غير المشفّرة أبداً -- وعبارة الاسترداد وحدها تستعيد أموالك إن نسيت كلمة مرور حسابك.",
    "account.unavailable": "النسخ الاحتياطي للحساب غير متاح على هذا الخادم حالياً.",
    "account.usernameLabel": "اسم المستخدم",
    "account.passwordLabel": "كلمة المرور (يجب أن تطابق كلمة مرور هذه المحفظة)",
    "account.createBtn": "إنشاء حساب ونسخ احتياطي",
    "account.backupNow": "نسخ احتياطي الآن",
    "account.signOut": "تسجيل الخروج",
    "account.changePasswordTitle": "تغيير كلمة المرور",
    "account.changePasswordNote": "يغيّر كلمة مرور محفظتك وكلمة مرور حسابك معاً -- وتبقيان متطابقتين دائماً.",
    "account.currentPasswordPlaceholder": "كلمة المرور الحالية",
    "account.newPasswordPlaceholder": "كلمة مرور جديدة",
    "account.confirmNewPasswordPlaceholder": "تأكيد كلمة المرور الجديدة",
    "account.deleteTitle": "حذف الحساب",
    "account.deleteNote": "يحذف نسختك الاحتياطية على الإنترنت فقط -- ولا تتأثر المحفظة على هذا الجهاز.",
    "account.deleteBtn": "حذف الحساب",
    "scan.button": "🔍 فحص المحفظة",
    "scan.title": "فحص المحفظة",
    "scan.intro": "يفحص هذا الحساب على الشبكة الحالية بحثاً عن الرموز الشائعة المدرجة في السوق ويعرض ما يملكه منها. تُقرأ الأرصدة العامة فقط -- ولا يُضاف شيء حتى تضغط إضافة، ولا تُعرض أبداً الرموز خارج هذه القائمة (بما فيها المقلّدة التي وصلت عبر الإسقاط الجوي).",
    "scan.addAll": "إضافة الكل",
    "scan.again": "فحص مرة أخرى",
    "errors.net.unreachable": "تعذّر الوصول إلى الشبكة. تحقق من اتصالك وحاول مرة أخرى.",
    "errors.net.noFunds": "لا يوجد ما يكفي من عملة هذه الشبكة (ETH على Base) لدفع رسوم الشبكة. أضف مبلغاً صغيراً وحاول مرة أخرى.",
    "errors.net.cancelled": "أُلغي هذا الطلب.",
    "errors.net.nonce": "تعذّر إرسال هذه المعاملة الآن -- حاول مرة أخرى.",
    "errors.net.feesChanged": "تغيّرت رسوم الشبكة للتو -- حاول مرة أخرى.",
    "errors.net.timeout": "استغرقت الشبكة وقتاً طويلاً للرد. حاول مرة أخرى.",
    "errors.net.rateLimit": "طلبات كثيرة جداً الآن -- انتظر قليلاً ثم حاول مرة أخرى.",
    "errors.net.rejected": "رفضت الشبكة هذا الطلب. راجع التفاصيل وحاول مرة أخرى.",
    "errors.net.gasEstimate": "لم تقبل الشبكة هذه المعاملة. تأكد من أن لديك ما يكفي من ETH لرسوم الشبكة ثم حاول مرة أخرى.",
    "errors.net.noResponse": "تعذّر الحصول على رد من الشبكة. حاول مرة أخرى.",
    "errors.net.generic": "حدث خطأ أثناء الاتصال بالشبكة. حاول مرة أخرى.",
    "errors.unknownError": "خطأ غير معروف",

    "common.sell": "بيع",
    "common.seeAll": "عرض الكل",
    "main.showQrBtn": "إظهار رمز QR",
    "main.hideQrBtn": "إخفاء رمز QR",
    "main.nftsTitle": "NFT",
    "main.addNftBtn": "+ إضافة NFT",
    "main.nftsEmpty": "لم تتم إضافة أي NFT بعد -- اضغط على «+ إضافة NFT» وأدخل عنوان العقد ومعرّف العملة لتتبّع واحد.",
    "main.livePricesTitle": "الأسعار المباشرة",
    "main.predictionsTitle": "العملات والعملات المستقرة",
    "main.currenciesCardTitle": "العملات",
    "main.exchangesCardTitle": "أشهر المنصات",
    "addToken.quickAddLabel": "إضافة سريعة:",
    "addToken.quickAddChip": "+ {symbol}",
    "nfts.loadError": "تعذّر التحميل",
    "nfts.removeTitle": "إزالة",
    "addNft.title": "إضافة NFT",
    "addNft.description": "يعمل مع ERC-721 وERC-1155. أضف فقط من مصدر تثق به.",
    "addNft.addressLabel": "عنوان العقد",
    "addNft.tokenIdLabel": "معرّف العملة",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "المعيار:",
    "addNft.invalidAddress": "أدخل عنوان عقد صالحًا.",
    "addNft.invalidTokenId": "أدخل معرّف عملة صالحًا (عدد صحيح غير سالب).",
    "addNft.metaWarning": "تعذّر تحميل الصورة أو الاسم، لكن لا يزال بإمكانك إضافته.",
    "addNft.noName": "(بدون اسم)",
    "prices.watchlistToggle": "اضغط على النجمة للتثبيت في الأعلى",
    "prices.cardUnavailable": "الأسعار غير متاحة حاليًا.",
    "prices.viewPeggedCoin": "عرض {name}، العملة المستقرة المرتبطة بـ {currency}",
    "prices.availableOn": "✓ على {networks}",
    "coin.swapUnavailableSwitchNetwork": "{symbol} هي العملة الأصلية لشبكة {network}. بدّل الشبكة لمبادلتها أو الاحتفاظ بها هناك.",
    "coin.swapUnavailableSwitchNetworkTracked": "لقد أضفت {symbol} على {network} بالفعل. بدّل إلى تلك الشبكة لاستخدامها.",
    "coin.swapUnavailableKnownElsewhere": "{symbol} عملة موثّقة على {network}. بدّل إلى تلك الشبكة لإضافتها تلقائيًا.",
    "coin.switchNetworkBtn": "التبديل إلى {network}",
    "coin.addOnNetworkBtn": "إضافة على {network}",
    "coin.buyBtn": "شراء {symbol}",
    "predictions.title": "العملات والعملات المستقرة",
    "predictions.description": "العملات الوطنية والعملات المستقرة المرتبطة بها، مع الأسعار المباشرة -- للاطلاع فقط. لا يُرسل أي شيء عن محفظتك للاستعلام عن هذه البيانات.",
    "predictions.tabStable": "العملات المستقرة",
    "predictions.tabTop": "أفضل العملات",
    "predictions.loading": "جارٍ التحميل...",
    "predictions.empty": "لا توجد أسعار للعملات المستقرة حاليًا.",
    "predictions.cardUnavailable": "أسعار العملات المستقرة غير متاحة حاليًا.",
    "predictions.volSuffix": "حجم التداول خلال 24 ساعة",
    "exchanges.title": "أشهر المنصات",
    "exchanges.description": "ترتيب منصات تداول العملات الرقمية المركزية حسب درجة الثقة في CoinGecko، ويُحدَّث تلقائيًا -- للاطلاع فقط. Token Exchange محفظة بحفظ ذاتي ولا يمرّر الصفقات عبر أي منها؛ ولا يُرسل أي شيء عن محفظتك للاستعلام عن هذه البيانات.",
    "exchanges.loading": "جارٍ التحميل...",
    "exchanges.empty": "لا توجد بيانات منصات متاحة حاليًا.",
    "exchanges.cardUnavailable": "المنصات غير متاحة حاليًا.",
    "exchanges.foundedYear": "تأسست عام {year}",
    "buy.description2": "يُفتح الشراء عبر Transak هنا مباشرةً داخل التطبيق، مع تعبئة عنوان الاستلام وقفله مسبقًا -- لا شيء للصقه، ولا يمكن إرسال العملات المشتراة إلا إلى محفظتك أنت.",
    "buy.presetNote": "تم ضبط الشراء مسبقًا على {symbol} -- ما زال بإمكانك اختيار أصل آخر عند فتح Transak.",
    "buy.closeWidgetBtn": "← إغلاق",
    "sell.title": "بيع مقابل نقد",
    "sell.description1": "يتم البيع عبر Transak، وهي نفس الخدمة الخارجية المستخدمة في الشراء -- لا يطّلع Token Exchange أبدًا على بيانات الدفع الخاصة بك.",
    "sell.description2": "يُفتح البيع عبر Transak هنا مباشرةً داخل التطبيق ويعرض لك سعرًا للدفع النقدي. سيُظهر لك عنوان إيداع لإرسال عملاتك الرقمية إليه -- وبمجرد استلامها، يحوّلها Transak ويدفع المبلغ إلى حسابك المصرفي أو بطاقتك المرتبطة.",
    "sell.continueBtn": "المتابعة إلى Transak",
    "sell.closeWidgetBtn": "← إغلاق",
    "send.contactsBtn": "جهات الاتصال",
    "contacts.title": "دفتر العناوين",
    "contacts.pickerHint": "اضغط على جهة اتصال لتعبئتها كمستلم.",
    "contacts.namePlaceholder": "الاسم",
    "contacts.addBtn": "حفظ جهة الاتصال",
    "contacts.empty": "لا توجد جهات اتصال محفوظة بعد.",
    "contacts.removeBtn": "إزالة",
    "contacts.nameRequired": "أعطِ جهة الاتصال هذه اسمًا.",
    "contacts.invalidAddress": "أدخل عنوان 0x صالحًا.",
    "send.confirmIntro": "سيتم الإرسال خلال {seconds} ث -- ما زال بإمكانك الإلغاء.",
    "send.confirmSummary": "{amount} {asset} إلى {to}",
    "send.newAddressWarning": "لم تُرسل إلى هذا العنوان من هذا الجهاز من قبل -- تأكد من صحته.",
    "send.cancelBtn": "إلغاء الإرسال",
    "send.cancelledStatus": "تم إلغاء الإرسال -- لم يُرسل أي شيء.",
    "send.feeEstimateLoading": "جارٍ تقدير رسوم الشبكة...",
    "send.feeEstimate": "رسوم الشبكة المقدّرة: ~{fee} {symbol} (~{usd})",
    "send.feeEstimateNoUsd": "رسوم الشبكة المقدّرة: ~{fee} {symbol}",
    "fee.burned": "منها ~{burn} {symbol} يتم حرقها (تُزال نهائيًا من المعروض)",
    "send.scanBtn": "مسح رمز QR",
    "send.scanTitle": "مسح رمز QR للمحفظة",
    "send.scanClose": "إغلاق",
    "send.scanHint": "وجّه الكاميرا نحو رمز QR لعنوان محفظة.",
    "send.scanUnsupported": "مسح رمز QR غير مدعوم في هذا المتصفح. الصق العنوان بدلًا من ذلك.",
    "send.scanDenied": "تم حظر الوصول إلى الكاميرا. اسمح بالكاميرا لهذا الموقع أو الصق العنوان.",
    "send.scanNoAddress": "لا يحتوي رمز QR هذا على عنوان محفظة صالح.",
    "send.scanFilled": "تمت تعبئة العنوان. تحقق منه مرة أخرى قبل الإرسال.",
    "activity.exportCsv": "تصدير بصيغة CSV",
    "activity.exportEmpty": "لا يوجد شيء لتصديره بعد.",
    "settings.themeLabel": "المظهر",
    "settings.themeDark": "داكن (افتراضي)",
    "settings.themeLight": "فاتح",
    "settings.notifyLabel": "الإشعارات",
    "settings.notifyOff": "متوقفة",
    "settings.notifyOn": "مفعّلة",
    "settings.notifyHint": "ينبّهك عند تأكيد معاملة أو وصول أموال أو تفعيل تنبيه سعر. يعمل فقط أثناء فتح هذه الصفحة في متصفحك.",
    "settings.notifyUnsupported": "لا يدعم هذا المتصفح إشعارات النظام. ستظل ترى الرسائل داخل الصفحة.",
    "settings.notifyDenied": "الإشعارات محظورة لهذا الموقع في إعدادات المتصفح.",
    "settings.alertLabel": "تنبيه السعر (العملة الأصلية)",
    "settings.alertAbove": "يرتفع فوق",
    "settings.alertBelow": "ينخفض دون",
    "settings.alertPlaceholder": "السعر",
    "settings.alertAdd": "إضافة",
    "settings.alertHint": "يستخدم عملة العرض لديك. يُفعَّل كل تنبيه مرة واحدة فقط، وفقط أثناء فتح هذه الصفحة.",
    "settings.alertRemove": "إزالة التنبيه",
    "settings.alertBadPrice": "أدخل سعرًا أكبر من الصفر.",
    "settings.alertNoFeed": "لا يتوفر مصدر أسعار لهذه الشبكة حاليًا.",
    "notify.txConfirmed": "تم تأكيد المعاملة",
    "notify.txFailed": "فشلت المعاملة",
    "notify.received": "تم استلام الأموال",
    "notify.priceAlert": "تنبيه السعر",
    "swap.bridgeLink": "تريد الانتقال إلى سلسلة أخرى؟ انقل أموالك عبر جسر ↗",
    "send.feeEstimateUnavailable": "تقدير رسوم الشبكة غير متاح -- ستظل ترى الرسوم الفعلية قبل بثّ أي شيء.",
    "send.confirmFeeLine": "رسوم الشبكة: ~{fee} {symbol}",
    "send.toPlaceholder": "0x... أو name.eth",
    "send.resolvingName": "جارٍ البحث عن {name}...",
    "send.resolvedName": "يُحلّ إلى {address}",
    "send.nameNotFound": "تعذّر العثور على عنوان لـ {name} -- تحقق من الاسم أو الصق العنوان مباشرة.",
    "send.nameResolutionUnsupported": "البحث عن الأسماء غير متاح على هذه الشبكة -- الصق العنوان مباشرة.",
    "swap.selectBtn": "اختيار",
    "swap.balanceLabel": "الرصيد: {amount} {symbol}",
    "swap.maxBtn": "الحد الأقصى",
    "swap.quotingHint": "جارٍ الحصول على السعر…",
    "swap.rateLabel": "السعر",
    "swap.appFeeShortLabel": "رسوم التطبيق",
    "swap.priceImpactLabel": "تأثير السعر",
    "swap.priceImpactWarn": "تأثير السعر حوالي {percent}. الكمية المتاحة للتداول من هذا الرمز قليلة، لذا ستحصل على أقل بكثير من السعر الحالي. فكّر في كمية أصغر.",
    "swap.priceImpactHigh": "تأثير السعر مرتفع جدًا (حوالي {percent}). سيضيع جزء كبير من مبلغك بسبب حركة السعر. جرّب كمية أصغر بكثير.",
    "swap.priceImpactConfirm": "تأثير السعر حوالي {percent}. ستحصل على أقل بكثير من سعر السوق. هل تريد المبادلة على أي حال؟",
    "app.name": "تبادل الرموز",
    "app.copyright": "© 2026 تبادل الرموز",
    "scan.button": "🔍 فحص المحفظة",
    "scan.title": "فحص المحفظة",
    "scan.intro": "يفحص هذا الحساب على الشبكة الحالية بحثًا عن الرموز الشائعة المدرجة في السوق ويعرض ما يملكه منها. تتم قراءة الأرصدة العامة فقط — لا تتم إضافة أي شيء حتى تضغط على إضافة، ولا تُعرض أبدًا الرموز الموجودة خارج هذه القائمة (بما في ذلك الرموز المقلّدة التي تصل عبر الإسقاط الجوي).",
    "scan.addAll": "إضافة الكل",
    "scan.again": "فحص مرة أخرى",
    "scan.scanning": "جارٍ فحص هذا الحساب بحثًا عن الرموز…",
    "scan.unsupported": "الفحص غير متاح على هذه الشبكة بعد. استخدم \"+ إضافة عملة\" والصق عنوان العقد بدلًا من ذلك.",
    "scan.noAccount": "لم يتم اختيار حساب.",
    "scan.noCatalog": "تعذّر الوصول إلى CoinGecko، لذا تم فحص العملات المستقرة الموثّقة فقط.",
    "scan.none": "لم يتم العثور على رموز جديدة في هذا الحساب.",
    "scan.add": "إضافة",
    "scan.adding": "جارٍ الإضافة…",
    "scan.added": "تمت الإضافة ✓",
    "swap.minReceivedLabel": "الحد الأدنى المستلم",
    "swap.networkFeeLabel": "رسوم الشبكة",
    "swap.gasStep_approve": "موافقة",
    "swap.gasStep_fee": "تحويل رسوم التطبيق",
    "swap.gasStep_swap": "مبادلة",
    "swap.gasPriceLabel": "سعر الغاز",
    "swap.gasUnavailable": "غير متاح",
    "swap.gasLowEth": "تنبيه: رسوم الشبكة لهذه المبادلة نحو {need} {symbol}، لكن هذا الحساب يحتوي على {have} فقط. أضف قليلًا من {symbol} أولًا وإلا ستفشل المعاملة.",
    "swap.selectAssetTitle": "اختيار أصل",
    "swap.selectTokenTitle": "اختيار عملة",
    "swap.pickerSearchPlaceholder": "أدخل اسم العملة أو الصق العنوان",
    "swap.pickerNoFavs": "لا توجد عملات مميّزة بنجمة على هذه الشبكة بعد. اضغط على النجمة في عملة لإضافتها.",
    "swap.pickerInfoTitle": "عرض في مستكشف البلوكات",
    "swap.pickerStarTitle": "تمييز العملة بنجمة",
    "swap.pickerNoMatch": "لا توجد عملة مطابقة على هذه الشبكة.",
    "swap.pickerLoadFailed": "تعذّر تحميل قائمة الرموز. تحقق من اتصالك وحاول مرة أخرى.",
    "swap.pickerNothingHeld": "لا يوجد رصيد في هذه الشبكة بعد. أضف رصيدًا أو بدّل الشبكة أعلاه.",
    "swap.pickerUseAddress": "استخدام عنوان هذه العملة",
    "swap.pickerLoadingTokens": "جارٍ البحث عن العملات...",
    "swap.pickerTopTokens": "أبرز العملات على هذه الشبكة",
    "swap.pickerSearchResults": "نتائج البحث",
    "swap.pickerSuggested": "عملات مستقرة مقترحة (موثّقة من الجهة المصدرة)",
    "swap.pickerNoSwapHere": "المبادلة غير مفعّلة على هذه الشبكة بعد. اختر شبكة أخرى من الأعلى.",
    "swap.noAssetsHint": "لا يوجد شيء متاح هنا بعد.",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "دفتر العناوين",
    "settings.currencyLabel": "عملة العرض",
    "settings.navStyleLabel": "نمط التنقل",
    "settings.navCube": "مكعب",
    "settings.navGlobe": "كرة أرضية",
    "settings.feedbackBtn": "اطلب ميزة",
    "settings.sendDelayLabel": "تأخير الإرسال (مهلة الإلغاء)",
    "settings.sendDelayHint": "يحتجز كل عملية إرسال صادرة طوال هذه المدة لتتاح لك فرصة إلغائها قبل بثّها. ينطبق هذا فقط على عمليات الإرسال التي تتم هنا في Token Exchange -- ولا يمكنه حماية محفظة تعرّض مفتاحها الخاص أو عبارة الاسترداد الخاصة بها للكشف خارج التطبيق.",
    "settings.autoLockLabel": "القفل التلقائي عند عدم النشاط",
    "settings.autoLockOff": "متوقف (لا قفل تلقائي أبدًا)",
    "settings.autoLock1": "دقيقة واحدة",
    "settings.autoLock5": "5 دقائق",
    "settings.autoLock15": "15 دقيقة",
    "settings.autoLock21": "21 دقيقة (افتراضي)",
    "settings.autoLock30": "30 دقيقة",
    "settings.autoLockHint": "يقفل المحفظة تلقائيًا بعد هذه المدة دون نقرات أو لمسات أو ضغطات مفاتيح هنا -- لأن علامة تبويب المتصفح المتروكة مفتوحة تبقى غير مقفلة إلى أجل غير مسمى.",
    "settings.sendDelayOff": "متوقف (إرسال فوري)",
    "settings.sendDelay15": "15 ثانية",
    "settings.sendDelay30": "30 ثانية (موصى به)",
    "settings.sendDelay60": "60 ثانية",
    "feedback.title": "طلبات الميزات",
    "feedback.subtitle": "اطّلع على ما يطلبه المستخدمون الآخرون، وصوّت للطلبات التي تريدها أنت أيضًا، أو انشر طلبك. هذه القائمة عامة -- وبها نقرر ما سنبنيه لاحقًا.",
    "feedback.titlePlaceholder": "عنوان قصير (مثل «الوضع الداكن»)",
    "feedback.descPlaceholder": "مزيد من التفاصيل (اختياري)",
    "feedback.submitBtn": "نشر الطلب",
    "feedback.submittingStatus": "جارٍ النشر...",
    "feedback.submittedStatus": "شكرًا لك! طلبك منشور أدناه.",
    "feedback.listTitle": "الطلبات",
    "feedback.empty": "لا توجد طلبات بعد -- كن الأول!",
    "feedback.loadError": "تعذّر تحميل الطلبات. حاول مرة أخرى بعد قليل.",
    "feedback.titleRequired": "أعطه عنوانًا قصيرًا أولًا.",
    "feedback.upvoteBtn": "تصويت",
    "feedback.upvotedBtn": "تم التصويت",
    "feedback.contactLine": "تفضّل البريد الإلكتروني؟ راسلنا على msandersod@gmail.com",
    "wc.title": "WalletConnect",
    "wc.subtitle": "اتصل بأي dapp يوفّر خيار «WalletConnect» -- الصق أدناه معرّف wc:... من رمز QR لربط المحفظة.",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "اتصال",
    "wc.notConfigured": "يحتاج WalletConnect إلى معرّف مشروع مجاني قبل أن يتمكن من الاتصال بأي شيء -- راجع lib/walletconnect-config.js.",
    "wc.sessionsTitle": "تطبيقات dapp المتصلة",
    "wc.sessionsEmpty": "لا توجد تطبيقات dapp متصلة بعد.",
    "wc.disconnectBtn": "قطع الاتصال",
    "wc.invalidUri": "لا يبدو هذا معرّف WalletConnect -- يجب أن يبدأ بـ «wc:».",
    "wc.pairingStatus": "جارٍ الاقتران... يجب أن يظهر طلب اتصال بعد لحظات.",
    "wc.pairedStatus": "تم الاقتران -- ابحث عن نافذة جديدة تطلب منك الموافقة على الاتصال.",
    "swap.appFeeValue": "{percent} ({amount} {symbol})",
    "main.findNftsBtn": "🔍 البحث عن NFT",
    "findNfts.title": "البحث عن NFT",
    "findNfts.description": "يفحص عنوان هذا الحساب على الشبكة الحالية ويعرض ما يملكه، باستخدام واجهة NFT API من Alchemy. يقرأ هذا بيانات الملكية العامة على السلسلة فقط -- ولا يُرسل أي شيء عن محفظتك إلى أي مكان سوى العنوان الذي تستخدمه بالفعل.",
    "findNfts.loadMore": "تحميل المزيد",
    "swap.flipBtnTitle": "عكس اتجاه المبادلة",
    "findNfts.loading": "جارٍ البحث عن NFT...",
    "findNfts.notConfigured": "البحث عن NFT غير مُعدّ على هذا الخادم بعد.",
    "findNfts.notSupported": "البحث عن NFT غير متاح على هذه الشبكة.",
    "findNfts.empty": "لم يتم العثور على NFT لهذا الحساب على هذه الشبكة.",
    "findNfts.loadError": "تعذّر تحميل NFT. حاول مرة أخرى بعد قليل.",
    "findNfts.addedBtn": "تمت إضافته بالفعل",
    "findNfts.addBtn": "إضافة إلى NFT الخاصة بي",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "كيف أنشئ محفظة؟",
      keywords: ["انشاء محفظة", "انشاء محفظة جديدة", "محفظة جديدة", "اعداد محفظة", "بداية", "اول مرة"],
      answer: "اضغط على «إنشاء محفظة جديدة» في شاشة الترحيب، واختر كلمة مرور (تُستخدم فقط لفتح المحفظة على هذا الجهاز -- ولا يمكنها استرداد أموالك)، وستظهر لك عبارة استرداد من 12 كلمة. دوّنها في مكان آمن قبل المتابعة -- فهذه العبارة هي الوسيلة الوحيدة لاسترداد أموالك في حال فقدان هذا الجهاز.",
    },
    {
      id: "import-wallet",
      chip: "كيف أستورد محفظة موجودة؟",
      keywords: ["استيراد محفظة", "استيراد محفظة موجودة", "استعادة محفظة", "محفظة موجودة", "استيراد عبارة الاسترداد", "استيراد seed"],
      answer: "في شاشة الترحيب اضغط على «استيراد محفظة موجودة»، وأدخل عبارة الاسترداد المكوّنة من 12 أو 24 كلمة كما هي بالضبط (بأحرف صغيرة ومفصولة بمسافات)، ثم عيّن كلمة مرور جديدة لهذا الجهاز. العبارة نفسها لا تغادر جهازك أبدًا -- تُستخدم محليًا فقط لاشتقاق حساباتك.",
    },
    {
      id: "forgot-password",
      chip: "نسيت كلمة المرور الخاصة بي",
      keywords: ["نسيت كلمة المرور", "نسيت كلمة السر", "كلمة مرور خاطئة", "لا استطيع فتح القفل", "المحفظة مقفلة", "كلمة المرور لا تعمل"],
      answer: "كلمة المرور تُستخدم فقط لفتح المحفظة على هذا الجهاز -- Token Exchange لا يخزّنها في أي مكان ولا يمكنه إعادة تعيينها نيابةً عنك. إن كنت لا تتذكرها، اضغط على «إعادة تعيين المحفظة بدلاً من ذلك» في شاشة فتح القفل، ثم استورد محفظتك مجددًا باستخدام عبارة الاسترداد المكوّنة من 12 كلمة. وإن لم تكن قد حفظت هذه العبارة، فللأسف لا يمكن استرداد الأموال الموجودة في هذه المحفظة -- وهذا هو الثمن المصاحب لمحفظة غير احتجازية: لا أحد سواك يمكنه فتحها في الأصل، وهو ما يعني أيضًا أن لا أحد سواك يمكنه إنقاذها.",
    },
    {
      id: "lost-seed-phrase",
      chip: "فقدت عبارة الاسترداد الخاصة بي",
      keywords: ["فقدت عبارة الاسترداد", "فقدان seed", "فقدت seed", "لا املك العبارة", "نسيت عبارتي", "لم احفظها"],
      answer: "إن كنت لا تزال مسجّلاً للدخول، اذهب إلى الإعدادات ← «عرض عبارة الاسترداد»، أعد إدخال كلمة المرور، ودوّنها الآن في مكان آمن. أما إن كنت خارج المحفظة ولم تحفظ العبارة من قبل، فلا توجد طريقة لاسترداد المحفظة أو الأموال بداخلها. Token Exchange لا يخزّن عبارتك في أي مكان -- لا على خادم ولا في أي سحابة -- لذا لا يمكن لأحد، ولا حتى المطوّر، استعادتها لك.",
    },
    {
      id: "balance-not-showing",
      chip: "رصيدي لا يظهر",
      keywords: ["الرصيد", "رصيد صفر", "0.00", "لا يظهر", "رصيد خاطئ", "الرصيد عالق", "لا يزال يحمّل", "الرصيد 0"],
      answer: "بقاء الرصيد عالقًا عند «...» يعني عادةً أن نقطة RPC الخاصة بتلك الشبكة بطيئة أو متوقفة مؤقتًا -- تعيد هذه المحفظة تلقائيًا المحاولة عبر نقطة احتياطية بعد ثوانٍ قليلة، لذا عادةً ما يُحل الأمر من تلقاء نفسه. وإن استقر الرصيد عند 0 وشعرت أن ذلك غير صحيح، تأكد من أنك على الشبكة الصحيحة والحساب الصحيح (كلتا القائمتين المنسدلتين موجودتان في الشاشة الرئيسية) -- فالأرصدة تُتابَع بشكل منفصل لكل شبكة وكل حساب، فمثلاً أموالك على Base لن تظهر عند اختيار Ethereum Mainnet.",
    },
    {
      id: "swap-failed",
      chip: "فشلت عملية المبادلة",
      keywords: ["فشلت المبادلة", "المبادلة عالقة", "المبادلة لا تعمل", "خطا في المبادلة", "فشل عرض السعر", "swap فشل"],
      answer: "تتم المبادلات على الشبكة مباشرةً عبر موجّه بورصة لامركزية عامة، لذا يعود الفشل عادةً إلى واحد من ثلاثة أسباب: رصيد غير كافٍ لتغطية المبلغ إضافةً إلى رسوم الغاز، أو نسبة تحمّل انزلاق سعري ضيّقة جدًا في ظل سعر يتحرك بسرعة (جرّب 1% أو 3% بدلاً من 0.5%)، أو أن زوج العملات هذا لا يملك بعد سيولة كافية على موجّه تلك الشبكة. الخطأ الذي يظهر في شاشة المبادلة بعد «احصل على عرض سعر» يشير عادةً إلى السبب -- وإن لم يكن واضحًا، جرّب مجددًا بمبلغ أصغر أولاً.",
    },
    {
      id: "swap-fee",
      chip: "كم تكلفة المبادلة؟",
      keywords: ["رسوم المبادلة", "كم التكلفة", "0.5%", "عمولة المبادلة", "رسوم على swap", "ما هي الرسوم"],
      answer: "تُفرض على المبادلات رسوم ثابتة بنسبة 0.5% من المبلغ الذي تبادله، وتظهر بوضوح في عرض السعر قبل التأكيد -- وهي جزء من معاملة المبادلة نفسها، وليست هامشًا خفيًا داخل سعر الصرف. وهذا منفصل عن رسوم الغاز التي تذهب إلى الشبكة نفسها وليس إلى Token Exchange.",
    },
    {
      id: "gas-fees",
      chip: "ما هي رسوم الغاز؟",
      keywords: ["رسوم الغاز", "رسوم الشبكة", "رسوم المعاملة", "ما هو الغاز", "تكلفة الغاز"],
      answer: "الغاز هو الرسم الذي تفرضه شبكة البلوكشين نفسها لمعالجة أي معاملة -- وهو منفصل عن رسوم المبادلة البالغة 0.5% الخاصة بـ Token Exchange، ويذهب بالكامل إلى الشبكة وليس إلينا. تتغيّر قيمته حسب ازدحام الشبكة في تلك اللحظة. تأكد من امتلاكك ما يكفي من العملة الأصلية لتلك الشبكة (ETH، BNB، POL، إلخ) لتغطية الغاز، حتى عند إرسال عملة أخرى وليس العملة الأصلية.",
    },
    {
      id: "add-network",
      chip: "كيف أضيف شبكة؟",
      keywords: ["اضافة شبكة", "شبكة جديدة", "شبكة مخصصة", "سلسلة اخرى", "شبكة اخرى"],
      answer: "اذهب إلى الإعدادات ← «إضافة شبكة» وأدخل اسم الشبكة ومعرّف السلسلة ورابط RPC ورمز العملة الأصلية. إذا أضفت أيضًا عنوان موجّه مبادلة موثّقًا هناك، ستعمل المبادلة على تلك الشبكة أيضًا -- وإلا فستقتصر وظيفتها على الإرسال والاستلام. استخدم فقط قيمًا تحققت منها بنفسك من الوثائق الرسمية لتلك الشبكة أو من مستكشف الكتل الخاص بها.",
    },
    {
      id: "add-token",
      chip: "كيف أتابع عملة؟",
      keywords: ["اضافة عملة", "متابعة عملة", "عملة جديدة", "عملة مخصصة", "erc-20", "erc20", "تتبع عملة"],
      answer: "في الشاشة الرئيسية اضغط على «+ إضافة عملة»، الصق عنوان عقد العملة لشبكتك الحالية، ثم اضغط على «بحث» -- ستقرأ المحفظة اسم العملة ورمزها وخاناتها العشرية مباشرةً من العقد لتتمكن من التحقق قبل إضافتها. لا تضف إلا عملة حصلت على عنوان عقدها من مصدر تثق به؛ فالمحفظة لا يمكنها التمييز بين عملة حقيقية وأخرى مزيفة تحمل نفس الاسم والرمز.",
    },
    {
      id: "send-crypto",
      chip: "كيف أرسل عملات رقمية؟",
      keywords: ["كيف ارسل", "ارسال عملات رقمية", "ارسال عملات", "تحويل عملات", "ارسال eth", "ارسال اموال"],
      answer: "اضغط على «إرسال» في الشاشة الرئيسية، اختر العملة الأصلية أو عملة أخرى (عبر عنوان عقدها)، أدخل عنوان المستلم والمبلغ، ثم أكّد. تحقق جيدًا من العنوان قبل التأكيد -- فعمليات الإرسال على هذه الشبكات لا رجعة فيها بمجرد إتمامها.",
    },
    {
      id: "connect-dapp",
      chip: "كيف أتصل بموقع؟",
      keywords: ["الاتصال بموقع", "الاتصال بتطبيق لامركزي", "زر connect wallet", "الاتصال بموقع الكتروني", "لا يتصل"],
      answer: "أي موقع يحتوي على زر «Connect Wallet» ويدعم إضافات محافظ المتصفح يجب أن يعرض Token Exchange بنفس الطريقة التي يعرض بها MetaMask أو Coinbase Wallet. إذا لم يظهر الموقع كخيار، جرّب تحديث الصفحة بعد تثبيت المحفظة وفتحها -- فبعض المواقع لا تكتشف إضافات المحافظ إلا عند تحميل الصفحة.",
    },
    {
      id: "buy-not-working",
      chip: "الشراء أو البيع لا يعمل",
      keywords: ["زر الشراء", "زر البيع", "الشراء لا يعمل", "البيع لا يعمل", "شراء غير مهيأ", "بيع غير مهيأ", "transak", "لا أستطيع الشراء", "لا أستطيع البيع"],
      answer: "يفتح كل من الشراء والبيع خدمة Transak، وهي خدمة خارجية منفصلة للشراء والبيع، في تبويب جديد. إذا ظهرت رسالة تفيد بأن الخدمة «غير مهيأة بعد»، فهذا يعني أن مطوّر هذه المحفظة لم يضف بعد بيانات اعتماد Transak -- وهذا أمر لا يمكنك إصلاحه من داخل المحفظة نفسها. وبمجرد تهيئتها، يُملأ عنوان استلامك ويُقفل تلقائيًا عند الشراء؛ فـ Token Exchange لا يرسله نيابةً عنك أبدًا.",
    },
    {
      id: "reset-wallet",
      chip: "كيف أعيد تعيين محفظتي؟",
      keywords: ["اعادة تعيين المحفظة", "حذف المحفظة", "البدء من جديد", "ازالة المحفظة", "مسح المحفظة"],
      answer: "الإعدادات ← «إعادة تعيين المحفظة» يحذف بشكل نهائي المحفظة المشفّرة من هذا المتصفح. تأكد تمامًا من أن لديك نسخة احتياطية من عبارة الاسترداد أولاً -- فهذا الإجراء لا يمكن التراجع عنه، ولن تكون هناك طريقة لاستعادة المحفظة بعد ذلك دون تلك العبارة.",
    },
    {
      id: "is-it-safe",
      chip: "هل هذه المحفظة آمنة؟",
      keywords: ["هل هذا امن", "هل هي امنة", "الثقة بها", "غير احتجازية", "احتجازية", "هل هذا موثوق", "هل هذا احتيال", "شرعي"],
      answer: "Token Exchange محفظة غير احتجازية: عبارة الاسترداد ومفاتيحك الخاصة مشفّرة ومخزّنة فقط في متصفحك -- ولا تُرسَل أبدًا إلى أي خادم، لأنه لا يوجد خادم أصلاً. وهذا يعني أيضًا أنه لا يمكن لأحد، ولا حتى المطوّر، استرداد أموالك إذا فقدت كلمة المرور وعبارة الاسترداد معًا. كما يتم فحص عمليات الإرسال والمبادلة مقابل قائمة عقوبات مرفقة قبل إرسالها، وذلك بالكامل على جهازك، وتظهر رسوم المبادلة دائمًا مسبقًا قبل التأكيد.",
    },
    {
      id: "pending-transaction",
      chip: "معاملتي عالقة",
      keywords: ["معلقة", "معاملة عالقة", "المعاملة لا تتاكد", "لا تزال معلقة", "المعاملة عالقة"],
      answer: "قد تبقى المعاملة «معلقة» إذا كانت الشبكة مزدحمة أو كان سعر الغاز المستخدم منخفضًا جدًا بالنسبة للظروف الحالية. ينبغي أن تتأكد في النهاية من تلقاء نفسها. وإذا ظلت عالقة لفترة طويلة، يمكنك البحث عن المعاملة في مستكشف كتل تلك الشبكة باستخدام عنوان حسابك لمعرفة حالتها الفعلية.",
    },
    {
      id: "wrong-network",
      chip: "ما هي الشبكات المدعومة؟",
      keywords: ["اي شبكة", "شبكة خاطئة", "تبديل الشبكة", "الشبكات المدعومة", "اي سلاسل", "السلاسل المدعومة", "ما هي الشبكات"],
      answer: "المدمج ضمن التطبيق: Ethereum وBase وPolygon وBNB Chain وArbitrum One وOP Mainnet، ويمكن التبديل بينها من القائمة المنسدلة أسفل الشاشة الرئيسية -- رصيدك وعملاتك وخيارات المبادلة كلها خاصة بالشبكة المختارة هناك. يمكنك إضافة أي شبكة أخرى متوافقة مع EVM بنفسك من الإعدادات ← «إضافة شبكة».",
    },
    {
      id: "contact-human",
      chip: "أحتاج إلى مزيد من المساعدة",
      keywords: ["التحدث الى شخص", "شخص حقيقي", "التواصل مع الدعم", "التواصل معكم", "ما زلت بحاجة الى مساعدة", "احتاج مساعدة اكثر", "التحدث مع احد"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "مرحبًا! أنا روبوت مساعدة بسيط ومدمج -- لا يمكنني الإجابة إلا عن أسئلة من قائمة ثابتة مُعدّة مسبقًا، لا أكثر. اضغط على أحد المواضيع أدناه أو اكتب سؤالك الخاص.";
  const fallbackWithEmail = "ليس لدي إجابة مكتوبة عن ذلك بعد. يمكنك التواصل مع أحد الأشخاص عبر {email} -- ويُستحسن ذكر الشاشة التي كنت فيها وما كنت تتوقع حدوثه.";
  const fallbackNoEmail = "ليس لدي إجابة مكتوبة عن ذلك بعد، كما أن هذه المحفظة لا تملك بعد خط دعم بشري مباشر. جرّب إعادة صياغة سؤالك، أو راجع ملف README الخاص بالإضافة لمزيد من التفاصيل حول طريقة عمل كل ميزة.";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.ar = {
    name: "العربية",
    dir: "rtl",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
