// lib/i18n/en.js
// Canonical English source for the popup UI's text and the Help & support
// chat's knowledge base. Every other lib/i18n/<code>.js file must define
// the exact same `strings` keys and the exact same FAQ `id`s as this file
// -- lib/i18n.js falls back to this file for anything missing elsewhere,
// and test-i18n.js checks the key sets match.
(function () {
  const strings = {
    "common.needHelp": "Need help?",
    "common.languageLabel": "Language",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.copy": "Copy",
    "common.send": "Send",
    "common.swap": "Swap",
    "common.buy": "Buy",
    "common.sell": "Sell",
    "common.livePrices": "Live prices",
    "common.seeAll": "See all",
    "common.reject": "Reject",
    "common.passwordPlaceholder": "Password",
    "common.confirmPasswordPlaceholder": "Confirm password",
    "common.newPasswordLabel": "New password (min 8 characters)",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "Token address (0x...)",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "Native coin",

    "onboarding.title": "Welcome",
    "onboarding.subtitle": "Set up your wallet to get started.",
    "onboarding.createBtn": "Create a new wallet",
    "onboarding.importBtn": "Import an existing wallet",

    "create.title": "Create wallet",
    "create.passwordLabel": "New password (min 8 characters)",
    "create.passwordWarning": "This password unlocks your wallet on this device. There is no recovery for it -- only your seed phrase can restore your funds.",
    "create.continueBtn": "Continue",
    "create.backupWarning": "Write down this recovery phrase and store it somewhere safe. Anyone with it can take everything in this wallet. Token Exchange cannot recover it for you.",
    "create.backupCheckbox": "I've saved my recovery phrase",
    "create.finishBtn": "Finish",

    "import.title": "Import wallet",
    "import.mnemonicLabel": "Recovery phrase (12 or 24 words)",
    "import.mnemonicPlaceholder": "word1 word2 word3 ...",
    "import.submitBtn": "Import",

    "unlock.title": "Unlock",
    "unlock.submitBtn": "Unlock",
    "unlock.resetInsteadBtn": "Reset wallet instead",

    "main.settingsTitle": "Settings",
    "main.portfolioLabel": "Total balance",
    "main.addAccountOption": "+ Add account",
    "main.showQrBtn": "Show QR",
    "main.hideQrBtn": "Hide QR",
    "main.tokensTitle": "Tokens",
    "main.addTokenBtn": "+ Add token",
    "main.tokensEmpty": "No tokens added yet -- tap “+ Add token” and enter a contract address to track one.",
    "main.nftsTitle": "NFTs",
    "main.addNftBtn": "+ Add NFT",
    "main.nftsEmpty": "No NFTs added yet -- tap “+ Add NFT” and enter a contract address and token ID to track one.",
    "main.networkLabel": "Network",
    "main.balanceFetchErrorPrefix": "Couldn't fetch balance: ",
    "main.watchOnlySuffix": "(Watching)",
    "main.watchOnlyNotice": "You're viewing a watch-only address -- there's no private key for it in this wallet, so Send and Swap are turned off here.",
    "main.livePricesTitle": "Live Prices",
    "main.predictionsTitle": "Trending Markets",

    "tokens.loadError": "Couldn't load balance",
    "tokens.removeTitle": "Remove",

    "addToken.title": "Add token",
    "addToken.description": "Enter the token's contract address on the current network. Only add a token whose contract address you got from a source you trust -- a wallet can't tell a real token apart from a fake one with the same name.",
    "addToken.addressLabel": "Token contract address",
    "addToken.lookupBtn": "Look up",
    "addToken.nameLabel": "Name:",
    "addToken.symbolLabel": "Symbol:",
    "addToken.decimalsLabel": "Decimals:",
    "addToken.confirmBtn": "Add to my wallet",
    "addToken.invalidAddress": "Enter a valid contract address.",
    "addToken.noName": "(no name)",
    "addToken.swapUnavailableSuffix": " (swap unavailable)",

    "nfts.loadError": "Couldn't load",
    "nfts.removeTitle": "Remove",
    "addNft.title": "Add NFT",
    "addNft.description": "Enter the NFT's contract address and token ID on the current network. Works for ERC-721 and ERC-1155 collections. Only add an NFT whose contract address you got from a source you trust -- artwork and names shown here come from the collection's own metadata, which anyone can set to anything.",
    "addNft.addressLabel": "NFT contract address",
    "addNft.tokenIdLabel": "Token ID",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "Standard:",
    "addNft.invalidAddress": "Enter a valid contract address.",
    "addNft.invalidTokenId": "Enter a valid token ID (a non-negative whole number).",
    "addNft.metaWarning": "Couldn't load this NFT's image/name from its metadata URI, but the contract and token ID check out -- you can still add it and try again later.",
    "addNft.noName": "(no name)",

    "prices.description": "Live prices from CoinGecko's public API, in whichever currency you pick in Settings. Purely informational -- nothing about your wallet is sent to look these up.",
    "prices.loading": "Loading...",
    "prices.naText": "n/a",
    "prices.watchlistToggle": "Star to pin to top",
    "prices.cardUnavailable": "Prices unavailable right now.",
    "prices.tabCrypto": "Crypto",
    "prices.tabCurrencies": "Currencies",
    "prices.searchPlaceholder": "Search...",
    "prices.currenciesNote": "What 1 unit of each currency is worth in your display currency.",
    "prices.noResults": "No results.",
    "prices.viewCoin": "View {name}",
    "coin.swapBtn": "Swap for {symbol}",
    "coin.swapHint": "You'll choose which of your holdings to pay with on the next screen.",
    "coin.swapNeedsWallet": "Unlock your wallet to swap.",
    "coin.swapNoRouter": "Swapping isn't enabled on this network yet.",
    "coin.swapUnavailableNetwork": "{symbol} can't be swapped on {network} yet. It has to be the network's own coin, or a token you've added with Add token.",
    "coin.swapUnavailableSwitchNetwork": "{symbol} is {network}'s own coin, so it can't be swapped here. Switch to {network} to swap it directly, or use Add token below if you meant a different, bridged version.",
    "coin.switchNetworkBtn": "Switch to {network} to swap",
    "coin.holding": "You hold {amount} {symbol}",
    "coin.statsTitle": "Market stats",
    "coin.aboutTitle": "About",
    "coin.aboutUnavailable": "No description available right now.",
    "coin.marketCap": "Market cap",
    "coin.volume24h": "24h volume",
    "coin.high24h": "24h high",
    "coin.low24h": "24h low",
    "coin.supply": "Circulating supply",
    "coin.ath": "All-time high",
    "coin.viewCoingecko": "View on CoinGecko",
    "coin.loadError": "Couldn't load more details for this coin right now.",
    "coin.chartUnavailable": "Chart unavailable right now.",
    "swap.customAddressOption": "Other token (paste address)...",

    "predictions.title": "Trending Markets",
    "predictions.description": "Public odds from Polymarket's prediction markets -- informational only. Token Exchange does not place bets or hold positions on your behalf; nothing about your wallet is sent to look these up.",
    "predictions.loading": "Loading...",
    "predictions.empty": "No trending markets right now.",
    "predictions.cardUnavailable": "Markets unavailable right now.",
    "predictions.volSuffix": "24h vol",

    "buy.title": "Buy crypto",
    "buy.description1": "Buy is powered by MoonPay, a separate third-party service -- Token Exchange never touches your payment details.",
    "buy.noThirdPartyCallout": "Already hold some crypto? Skip MoonPay entirely -- swap it for what you need directly on-chain, no third party, no signup.",
    "buy.noThirdPartySwapBtn": "Swap instead",
    "buy.description2Html": "MoonPay opens right here, below. Since this wallet can't safely sign requests with a secret key (that must never live inside a browser extension -- see <code>lib/buy-config.js</code>), <strong>paste in your receiving address yourself</strong> once it loads:",
    "buy.description2AutoFill": "MoonPay opens right here, below, with your receiving address already filled in -- nothing to paste.",
    "buy.continueBtn": "Continue to MoonPay",

    "sell.title": "Sell for cash",
    "sell.description1": "Sell is powered by MoonPay, the same third-party service Buy uses -- Token Exchange never touches your payout details.",
    "sell.description2": "MoonPay opens right here, below, and quotes you a cash payout. It will show you a deposit address to send your crypto to -- once MoonPay receives it, it converts and pays out to your linked bank account or card.",
    "sell.description3Html": "Come back here and use <strong>Send</strong> with the address MoonPay gives you -- this wallet never sends funds anywhere on its own.",
    "sell.continueBtn": "Continue to MoonPay",

    "support.title": "Help & support",
    "support.description": "Ask a question or tap a topic below. This runs entirely on your device -- nothing you type here is sent anywhere.",
    "support.inputPlaceholder": "Type a question...",

    "send.title": "Send",
    "send.assetLabel": "Asset",
    "send.assetToken": "Token (enter contract address)",
    "send.tokenAddressPlaceholder": "Token contract address (0x...)",
    "send.toLabel": "To address",
    "send.contactsBtn": "Contacts",

    "contacts.title": "Address book",
    "contacts.pickerHint": "Tap a contact to fill it in as the recipient.",
    "contacts.namePlaceholder": "Name",
    "contacts.addBtn": "Save contact",
    "contacts.empty": "No saved contacts yet.",
    "contacts.removeBtn": "Remove",
    "contacts.nameRequired": "Give this contact a name.",
    "contacts.invalidAddress": "Enter a valid 0x address.",
    "send.amountLabel": "Amount",
    "send.speedSlow": "Slow",
    "send.speedStandard": "Standard",
    "send.speedFast": "Fast",
    "send.invalidRecipient": "Enter a valid recipient address.",
    "send.invalidTokenAddress": "Enter a valid token contract address.",
    "send.sentStatus": "Sent! Tx hash: {txHash}",
    "send.confirmIntro": "Sending in {seconds}s -- you can still cancel.",
    "send.confirmSummary": "{amount} {asset} to {to}",
    "send.newAddressWarning": "You haven't sent to this address from this device before -- double check it's correct.",
    "send.poisonWarning": "This address looks a lot like one you've used before ({match}) but it isn't the same -- it starts and ends the same way while the middle is different. This is a common scam pattern (\"address poisoning\") where a lookalike is planted in your history hoping you'll copy the wrong one. Check every character before sending.",
    "send.cancelBtn": "Cancel send",
    "send.cancelledStatus": "Send cancelled -- nothing was sent.",
    "send.feeEstimateLoading": "Estimating network fee...",
    "send.feeEstimate": "Estimated network fee: ~{fee} {symbol} (~{usd})",
    "send.feeEstimateNoUsd": "Estimated network fee: ~{fee} {symbol}",
    "send.feeEstimateUnavailable": "Network fee estimate unavailable -- you'll still see the real fee before anything is broadcast.",
    "send.confirmFeeLine": "Network fee: ~{fee} {symbol}",
    "send.toPlaceholder": "0x... or name.eth",
    "send.resolvingName": "Looking up {name}...",
    "send.resolvedName": "Resolves to {address}",
    "send.nameNotFound": "Couldn't find an address for {name} -- double-check the name, or paste the address directly.",
    "send.nameResolutionUnsupported": "Name lookups aren't available on this network -- paste the address directly.",

    "swap.unsupportedWarning": "Swapping isn't enabled on this network yet -- no verified router configured. Add one in Settings → Networks first.",
    "swap.fromLabel": "From",
    "swap.toLabel": "To",
    "swap.getQuoteBtn": "Get quote",
    "swap.appFeeLine": "App fee ({percent}): {amount}",
    "swap.netAmountLine": "Net amount swapped: {amount}",
    "swap.estimatedOutLine": "Estimated out: {amount}",
    "swap.slippageLabel": "Slippage tolerance",
    "swap.approveBtn": "Approve token first",
    "swap.approvingStatus": "Approving...",
    "swap.approvedStatus": "Approved. You can swap now.",
    "swap.sendingStatus": "Sending fee + swapping...",
    "swap.swappedStatus": "Swapped! Fee tx: {feeTx} | Swap tx: {tx}",
    "swap.feeTxNa": "n/a",

    "settings.title": "Settings",
    "settings.addAccountBtn": "Add account",
    "settings.importKeyBtn": "Import private key",
    "settings.addWatchBtn": "Add watch-only address",
    "settings.approvalsBtn": "Manage approvals",
    "settings.addNetworkBtn": "Add network",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "Address book",
    "settings.currencyLabel": "Display currency",
    "settings.viewSeedBtn": "View recovery phrase",
    "settings.helpBtn": "Help & support",
    "settings.feedbackBtn": "Request a feature",
    "settings.sendDelayLabel": "Send delay (cancel window)",
    "settings.sendDelayHint": "Holds every outgoing send for this long so you have a chance to cancel it before it's broadcast. This only covers sends made here in Token Exchange -- it can't protect a wallet whose private key or recovery phrase has already been exposed outside the app.",

    "settings.autoLockLabel": "Auto-lock after inactivity",
    "settings.autoLockOff": "Off (never auto-lock)",
    "settings.autoLock1": "1 minute",
    "settings.autoLock5": "5 minutes (recommended)",
    "settings.autoLock15": "15 minutes",
    "settings.autoLock30": "30 minutes",
    "settings.autoLockHint": "Locks the wallet automatically after this much time with no clicks, taps, or keystrokes here -- since a browser tab you leave open otherwise stays unlocked indefinitely.",
    "settings.sendDelayOff": "Off (send immediately)",
    "settings.sendDelay15": "15 seconds",
    "settings.sendDelay30": "30 seconds (recommended)",
    "settings.sendDelay60": "60 seconds",
    "settings.lockBtn": "Lock wallet",
    "settings.resetBtn": "Reset wallet",

    "feedback.title": "Feature requests",
    "feedback.subtitle": "See what other users are asking for, upvote the ones you want too, or post your own. This list is public -- it's how we decide what to build next.",
    "feedback.titlePlaceholder": "Short title (e.g. \"Dark mode\")",
    "feedback.descPlaceholder": "A bit more detail (optional)",
    "feedback.submitBtn": "Post request",
    "feedback.submittingStatus": "Posting...",
    "feedback.submittedStatus": "Thanks! Your request is live below.",
    "feedback.listTitle": "REQUESTS",
    "feedback.empty": "No requests yet -- be the first!",
    "feedback.loadError": "Couldn't load requests. Try again in a moment.",
    "feedback.titleRequired": "Give it a short title first.",
    "feedback.upvoteBtn": "Upvote",
    "feedback.upvotedBtn": "Upvoted",
    "feedback.contactLine": "Prefer email? Reach us at msandersod@gmail.com",

    "importKey.title": "Import private key",
    "importKey.description": "This adds a separate account to this wallet from a raw private key, not from your recovery phrase -- back it up on its own, since your recovery phrase won't restore it. Never share a private key with anyone; anyone who has it can spend everything in that account.",
    "importKey.placeholder": "0x private key",

    "addWatch.title": "Add watch-only address",
    "addWatch.description": "Tracks an address's balance, tokens, and activity without holding a key for it -- there's nothing here to sign with, so Send and Swap stay off for it. Useful for keeping an eye on a cold-storage or hardware-wallet address from here.",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "Label (optional)",
    "addWatch.submitBtn": "Add",

    "approvals.title": "Manage approvals",
    "approvals.description": "Shows token spending approvals for this wallet's own swap router, plus a manual lookup for any other token and spender. Revoking sets the allowance back to zero -- the spender can no longer move that token on your behalf until you approve it again.",
    "approvals.emptyText": "No approvals found for the tokens you've added.",
    "approvals.loading": "Checking allowances...",
    "approvals.manualHeading": "Check a specific approval",
    "approvals.tokenPlaceholder": "Token contract address (0x...)",
    "approvals.spenderPlaceholder": "Spender contract address (0x...)",
    "approvals.checkBtn": "Check",
    "approvals.tokenLabel": "Token:",
    "approvals.spenderLabel": "Spender:",
    "approvals.allowanceLabel": "Allowance:",
    "approvals.revokeBtn": "Revoke",
    "approvals.revokingBtn": "Revoking...",
    "approvals.rowError": "Couldn't check this one -- try again in a moment.",

    "wc.title": "WalletConnect",
    "wc.subtitle": "Connect to any dapp that offers a \"WalletConnect\" option -- paste the wc:... URI from its connect-wallet QR code below.",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "Connect",
    "wc.notConfigured": "WalletConnect needs a free Project ID before it can connect to anything -- see lib/walletconnect-config.js.",
    "wc.sessionsTitle": "Connected dapps",
    "wc.sessionsEmpty": "No dapps connected yet.",
    "wc.disconnectBtn": "Disconnect",
    "wc.invalidUri": "That doesn't look like a WalletConnect URI -- it should start with \"wc:\".",
    "wc.pairingStatus": "Pairing... a connection request should appear in a moment.",
    "wc.pairedStatus": "Paired -- check for a new window asking you to approve the connection.",

    "addNetwork.title": "Add network",
    "addNetwork.namePlaceholder": "Network name",
    "addNetwork.chainIdPlaceholder": "Chain ID (number)",
    "addNetwork.rpcPlaceholder": "RPC URL",
    "addNetwork.symbolPlaceholder": "Native currency symbol",
    "addNetwork.explorerPlaceholder": "Block explorer URL (optional)",
    "addNetwork.routerPlaceholder": "Verified swap router address (optional)",
    "addNetwork.routerWarning": "Only fill in the router address if you've personally verified it against the project's official docs or the chain's block explorer. Leave blank if unsure -- swapping will simply be disabled for this network until you add one.",
    "addNetwork.addBtn": "Add",

    "viewSeed.title": "Recovery phrase",
    "viewSeed.passwordPlaceholder": "Enter password to reveal",
    "viewSeed.revealBtn": "Reveal",

    "reset.title": "Reset wallet",
    "reset.warning": "This deletes the encrypted wallet from this browser. Make sure you have your recovery phrase backed up -- this cannot be undone.",
    "reset.confirmBtn": "Yes, delete everything",

    "approve.unlockTitle": "Unlock to continue",
    "approve.unlockOriginText": "{origin} is requesting access.",
    "approve.connectTitle": "Connection request",
    "approve.connectWantsText": "{origin} wants to connect to your wallet.",
    "approve.accountLabel": "Account: ",
    "approve.acceptConnectBtn": "Connect",
    "approve.txTitle": "Transaction request",
    "approve.toLabel": "To:",
    "approve.valueLabel": "Value:",
    "approve.dataLabel": "Data:",
    "approve.txWarning": "Only approve this if you trust the site and understand what it's asking you to sign.",
    "approve.confirmBtn": "Confirm",
    "approve.signTitle": "Signature request",
    "approve.signBtn": "Sign",
    "approve.addNetTitle": "Add network request",
    "approve.addNetNameLabel": "Name:",
    "approve.addNetChainIdLabel": "Chain ID:",
    "approve.addNetRpcLabel": "RPC:",
    "approve.addNetWarning": "This site's suggested network has no verified swap router. Swapping will stay disabled on it until you add one yourself in Settings.",
    "approve.addNetBtn": "Add network",
    "approve.contractCreation": "(contract creation)",
    "approve.nativeSuffix": " (native)",
    "approve.decodedLoading": "Reading what this actually does...",
    "approve.decodedTransferLine": "This will transfer {amount} to {to}.",
    "approve.decodedApproveLine": "This will approve {amount} for {to} to spend.",
    "approve.decodedUnlimited": "UNLIMITED {symbol}",
    "approve.decodedThisToken": "this token",
    "approve.decodedRawUnitsSuffix": " raw units (couldn't confirm this token's decimals)",
    "approve.decodedGenericIntro": "This calls \"{fn}\" on the contract above with:",

    "loading.text": "Loading...",

    "home.tabHome": "Home",
    "home.tabAssets": "Assets",
    "home.tabActivity": "Activity",
    "home.tabSend": "Send",
    "home.tapToContinue": "Tap to continue",
    "home.continueBtn": "Continue",

    "activity.title": "Activity",
    "activity.subtitle": "A local record of sends made from this wallet, plus incoming transfers this device has noticed -- nothing here is fetched from a server.",
    "activity.empty": "No activity yet -- sends you make (and incoming transfers this device notices) will show up here.",
    "activity.sentLabel": "Sent {amount} {asset}",
    "activity.receivedLabel": "Received {amount} {asset}",
    "activity.toLabel": "to {address}",
    "activity.statusSent": "Sent",
    "activity.statusReceived": "Received",
    "activity.receivedApproxNote": "Detected from a balance change -- approximate, no transaction link available",
    "activity.viewOnExplorer": "View on block explorer",

    "footer.nonCustodial": "Non-custodial — your keys never leave this device",

    "errors.passwordTooShort": "Password must be at least 8 characters.",
    "errors.passwordMismatch": "Passwords don't match.",
    "errors.unknownError": "Unknown error",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "How do I create a wallet?",
      keywords: ["create wallet", "create a wallet", "new wallet", "set up wallet", "setup wallet", "get started", "first time"],
      answer: "Tap “Create a new wallet” on the welcome screen, choose a password (this only unlocks the wallet on this device -- it can't recover your funds), and you'll be shown a 12-word recovery phrase. Write it down somewhere safe before continuing -- that phrase is the only way to recover your funds if this device is ever lost.",
    },
    {
      id: "import-wallet",
      chip: "How do I import an existing wallet?",
      keywords: ["import wallet", "import an existing", "restore wallet", "existing wallet", "import recovery", "import seed"],
      answer: "On the welcome screen tap “Import an existing wallet,” enter your 12- or 24-word recovery phrase exactly as written (lowercase, space-separated), then set a new password for this device. The phrase itself never leaves your device -- it's used locally to derive your accounts.",
    },
    {
      id: "forgot-password",
      chip: "I forgot my password",
      keywords: ["forgot password", "forgot my password", "wrong password", "can't unlock", "cant unlock", "locked out", "password not working", "password isn't working"],
      answer: "Your password only unlocks the wallet on this device -- Token Exchange never stores it anywhere and can't reset it for you. If you don't remember it, tap “Reset wallet instead” on the unlock screen, then import your wallet again using your 12-word recovery phrase. If you don't have that phrase saved, the funds in this wallet unfortunately can't be recovered -- that's the trade-off of a non-custodial wallet: nobody but you can ever unlock it, which also means nobody but you can rescue it.",
    },
    {
      id: "lost-seed-phrase",
      chip: "I lost my recovery phrase",
      keywords: ["lost seed", "lost my seed", "lost recovery phrase", "lost my recovery", "don't have my phrase", "dont have my phrase", "forgot my phrase", "never wrote it down", "didn't save"],
      answer: "If you're still logged in, go to Settings → “View recovery phrase,” re-enter your password, and write it down now somewhere safe. If you're locked out AND you never saved the phrase, there is no way to recover the wallet or the funds in it. Token Exchange never stores your phrase anywhere -- on a server, in the cloud, anywhere -- so no one, including the developer, can retrieve it for you.",
    },
    {
      id: "balance-not-showing",
      chip: "My balance isn't showing",
      keywords: ["balance", "zero balance", "0.00", "not showing", "wrong balance", "balance stuck", "still loading", "balance is 0"],
      answer: "A balance stuck on “...” usually means that network's RPC endpoint is slow or briefly down -- this wallet automatically retries a backup endpoint after a few seconds, so it usually clears up on its own. If it settles on 0 and that seems wrong, double-check you're on the right network and the right account (both dropdowns are on the main screen) -- balances are tracked separately per network and per account, so funds on Base won't show while Ethereum Mainnet is selected, for example.",
    },
    {
      id: "swap-failed",
      chip: "My swap failed",
      keywords: ["swap failed", "swap stuck", "swap not working", "swap error", "quote failed", "swap didn't work", "swap isn't working"],
      answer: "Swaps happen on-chain through a public decentralized exchange router, so a failure is usually one of three things: not enough balance to cover the amount plus network gas, a slippage tolerance set too tight for a fast-moving price (try 1% or 3% instead of 0.5%), or that token pair not having enough liquidity on that network's router yet. The error shown on the Swap screen after “Get quote” usually points to which one -- if it's unclear, try again with a smaller amount first.",
    },
    {
      id: "swap-fee",
      chip: "What does a swap cost?",
      keywords: ["swap fee", "how much does it cost", "0.5%", "swap charge", "fee on swap", "what's the fee", "whats the fee"],
      answer: "Swaps carry a flat 0.5% fee on the amount you're swapping, shown clearly on the quote before you confirm -- it's part of the swap transaction itself, never a hidden markup buried in the exchange rate. That's separate from network gas, which goes to the blockchain, not to Token Exchange.",
    },
    {
      id: "gas-fees",
      chip: "What is a gas fee?",
      keywords: ["gas fee", "network fee", "transaction fee", "what is gas", "gas cost"],
      answer: "Gas is the fee the blockchain network itself charges to process a transaction -- it's separate from Token Exchange's 0.5% swap fee and goes entirely to the network, not to us. The amount varies with network congestion at the time. Make sure you hold enough of that network's native coin (ETH, BNB, POL, etc.) to cover gas, even when you're sending a token rather than the native coin.",
    },
    {
      id: "add-network",
      chip: "How do I add a network?",
      keywords: ["add network", "add a network", "new network", "custom network", "another chain", "different chain"],
      answer: "Go to Settings → “Add network” and fill in the network's name, chain ID, RPC URL, and native currency symbol. If you also add a verified swap router address there, swapping will work on that network too -- otherwise it'll just handle sending and receiving. Only use values you've personally verified against that network's official docs or block explorer.",
    },
    {
      id: "add-token",
      chip: "How do I track a token?",
      keywords: ["add token", "track token", "new token", "custom token", "erc-20", "erc20", "track a token"],
      answer: "On the main screen tap “+ Add token,” paste the token's contract address for your current network, and tap “Look up” -- it reads the token's name, symbol, and decimals straight from the contract so you can confirm before adding it. Only add a token whose contract address came from a source you trust; a wallet can't tell a real token apart from a fake one using the same name and symbol.",
    },
    {
      id: "send-crypto",
      chip: "How do I send crypto?",
      keywords: ["how do i send", "send crypto", "send tokens", "transfer crypto", "send eth", "send funds"],
      answer: "Tap “Send” on the main screen, choose the native coin or a token (by its contract address), enter the recipient's address and an amount, and confirm. Double-check the address before confirming -- sends on these networks are irreversible once they go through.",
    },
    {
      id: "connect-dapp",
      chip: "How do I connect to a website?",
      keywords: ["connect dapp", "connect to a website", "connect wallet button", "connect to a site", "won't connect", "wont connect"],
      answer: "Any site with a “Connect Wallet” button that supports browser wallet extensions should offer Token Exchange the same way it would MetaMask or Coinbase Wallet. If a site doesn't show it as an option, try refreshing the page after the wallet is installed and unlocked -- some sites only detect wallet extensions on page load.",
    },
    {
      id: "buy-not-working",
      chip: "Buy isn't working",
      keywords: ["buy button", "buy isn't working", "buy not working", "buy not configured", "moonpay", "can't buy", "cant buy"],
      answer: "The Buy button opens MoonPay, a separate third-party on-ramp, in a new tab. If it says “Buy isn't configured yet,” that means this wallet's developer hasn't added a MoonPay API key yet -- it's not something you can fix from inside the wallet itself. Once it is configured, you'll paste your own receiving address into MoonPay's page yourself; Token Exchange never sends it on your behalf.",
    },
    {
      id: "reset-wallet",
      chip: "How do I reset my wallet?",
      keywords: ["reset wallet", "delete wallet", "start over", "remove wallet", "wipe wallet"],
      answer: "Settings → “Reset wallet” permanently deletes the encrypted wallet from this browser. Make absolutely sure you have your recovery phrase backed up first -- this can't be undone, and there's no way to get the wallet back afterward without that phrase.",
    },
    {
      id: "is-it-safe",
      chip: "Is this wallet safe?",
      keywords: ["is this safe", "is it safe", "trust this", "non-custodial", "custodial", "is this secure", "is this a scam", "legit"],
      answer: "Token Exchange is non-custodial: your recovery phrase and private keys are encrypted and stored only in your browser -- never sent to any server, because there isn't one. That also means no one, including the developer, can recover your funds if you lose both your password and your recovery phrase. Sends and swaps are also checked against a bundled sanctions list before they go out, entirely on-device, and swap fees are always shown up front before you confirm.",
    },
    {
      id: "pending-transaction",
      chip: "My transaction is stuck",
      keywords: ["pending", "stuck transaction", "transaction not confirming", "still pending", "transaction stuck"],
      answer: "A transaction can sit “pending” if the network is congested or the gas price it used was too low for current conditions. It should confirm eventually on its own. If it's been stuck a long time, you can look up the transaction on that network's block explorer using your account address to see its real-time status.",
    },
    {
      id: "wrong-network",
      chip: "Which networks are supported?",
      keywords: ["which network", "wrong network", "switch network", "supported networks", "which chains", "supported chains", "what networks"],
      answer: "Built in: Ethereum, Base, Polygon, BNB Chain, Arbitrum One, and OP Mainnet, switchable from the dropdown near the bottom of the main screen -- your balance, tokens, and swap options are all specific to whichever network is selected there. You can add any other EVM-compatible network yourself from Settings → “Add network.”",
    },
    {
      id: "contact-human",
      chip: "I need more help",
      keywords: ["talk to a human", "real person", "contact support", "contact you", "still need help", "need more help", "speak to someone"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "Hi! I'm a simple built-in help bot -- I can only answer questions from a fixed list written ahead of time, nothing more. Tap a topic below or type your own question.";
  const fallbackWithEmail = "I don't have a written answer for that yet. You can reach a person at {email} -- it helps to mention which screen you were on and what you expected to happen.";
  const fallbackNoEmail = "I don't have a written answer for that yet, and this wallet doesn't have a live human support line set up yet either. Try rephrasing your question, or check the extension's README for more detail on how each feature works.";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.en = {
    name: "English",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
