// lib/i18n/en.js
// Canonical English source for the popup UI's text and the Help & support
// chat's knowledge base. Every other lib/i18n/<code>.js file must define
// the exact same `strings` keys and the exact same FAQ `id`s as this file
// -- lib/i18n.js falls back to this file for anything missing elsewhere,
// and test-i18n.js checks the key sets match.
(function () {
  const strings = {
    "common.needHelp": "Need help?",
    "common.languageLabel": "Language",
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.copy": "Copy",
    "common.send": "Send",
    "common.swap": "Swap",
    "common.buy": "Buy",
    "common.sell": "Sell",
    "common.livePrices": "Live prices",
    "common.seeAll": "See all",
    "common.reject": "Reject",
    "common.passwordPlaceholder": "Password",
    "common.confirmPasswordPlaceholder": "Confirm password",
    "common.newPasswordLabel": "New password (min 8 characters)",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "Token address (0x...)",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "Native coin",

    "onboarding.title": "Welcome",
    "onboarding.subtitle": "Set up your wallet to get started.",
    "onboarding.createBtn": "Create a new wallet",
    "onboarding.importBtn": "Import an existing wallet",

    "create.title": "Create wallet",
    "create.passwordLabel": "New password (min 8 characters)",
    "create.passwordWarning": "No recovery if you lose this -- only your seed phrase can restore your wallet.",
    "create.continueBtn": "Continue",
    "create.backupWarning": "Write this down and keep it safe. Anyone who sees it can empty this wallet, and we can't recover it for you.",
    "create.backupCheckbox": "I've saved my recovery phrase",
    "create.finishBtn": "Finish",

    "import.title": "Import wallet",
    "import.mnemonicLabel": "Recovery phrase (12 or 24 words)",
    "import.mnemonicPlaceholder": "word1 word2 word3 ...",
    "import.submitBtn": "Import",

    "unlock.title": "Unlock",
    "unlock.submitBtn": "Unlock",
    "unlock.resetInsteadBtn": "Reset wallet instead",

    "main.settingsTitle": "Settings",
    "main.portfolioLabel": "Total balance",
    "main.addAccountOption": "+ Add account",
    "main.showQrBtn": "Show QR",
    "main.hideQrBtn": "Hide QR",
    "main.tokensTitle": "Tokens",
    "main.addTokenBtn": "+ Add token",
    "main.tokensEmpty": "No tokens added yet -- tap “+ Add token” and enter a contract address to track one.",
    "main.nftsTitle": "NFTs",
    "main.addNftBtn": "+ Add NFT",
    "main.nftsEmpty": "No NFTs added yet -- tap “+ Add NFT” and enter a contract address and token ID to track one.",
    "main.networkLabel": "Network",
    "main.balanceFetchErrorPrefix": "Couldn't fetch balance: ",
    "main.watchOnlySuffix": "(Watching)",
    "main.watchOnlyNotice": "You're viewing a watch-only address -- there's no private key for it in this wallet, so Send and Swap are turned off here.",
    "main.livePricesTitle": "Live Prices",
    "main.predictionsTitle": "Currencies & Stablecoins",
    "main.currenciesCardTitle": "Currencies",
    "main.exchangesCardTitle": "Hottest Exchanges",

    "tokens.loadError": "Couldn't load balance",
    "tokens.removeTitle": "Remove",
    "tokens.pinTitle": "Pin to top",
    "tokens.unpinTitle": "Unpin",
    "tokens.hideTitle": "Hide from list",
    "tokens.unhideTitle": "Show in list",
    "tokens.showHidden": "Show {count} hidden",
    "tokens.hideHidden": "Hide hidden tokens",

    "addToken.title": "Add token",
    "addToken.description": "Only add tokens from a source you trust.",
    "addToken.addressLabel": "Contract address",
    "addToken.lookupBtn": "Look up",
    "addToken.quickAddLabel": "Quick add:",
    "addToken.quickAddChip": "+ {symbol}",
    "addToken.nameLabel": "Name:",
    "addToken.symbolLabel": "Symbol:",
    "addToken.decimalsLabel": "Decimals:",
    "addToken.confirmBtn": "Add to my wallet",
    "addToken.invalidAddress": "Enter a valid contract address.",
    "addToken.noName": "(no name)",
    "addToken.searchPlaceholder": "Search by name or symbol",
    "addToken.orPaste": "Or paste a contract address",
    "addToken.swapUnavailableSuffix": " (swap unavailable)",

    "nfts.loadError": "Couldn't load",
    "nfts.removeTitle": "Remove",
    "addNft.title": "Add NFT",
    "addNft.description": "Works for ERC-721 and ERC-1155. Only add from a source you trust.",
    "addNft.addressLabel": "Contract address",
    "addNft.tokenIdLabel": "Token ID",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "Standard:",
    "addNft.invalidAddress": "Enter a valid contract address.",
    "addNft.invalidTokenId": "Enter a valid token ID (a non-negative whole number).",
    "addNft.metaWarning": "Couldn't load image or name, but you can still add it.",
    "addNft.noName": "(no name)",

    "prices.description": "Live prices from CoinGecko's public API, in whichever currency you pick in Settings. Purely informational -- nothing about your wallet is sent to look these up.",
    "prices.loading": "Loading...",
    "prices.naText": "n/a",
    "prices.watchlistToggle": "Star to pin to top",
    "prices.cardUnavailable": "Prices unavailable right now.",
    "prices.tabCrypto": "Crypto",
    "prices.tabCurrencies": "Currencies",
    "prices.searchPlaceholder": "Search...",
    "prices.currenciesNote": "What 1 unit of each currency is worth in your display currency.",
    "prices.noResults": "No results.",
    "prices.viewCoin": "View {name}",
    "prices.volShort": "Vol",
    "prices.viewPeggedCoin": "View {name}, the stablecoin pegged to {currency}",
    "prices.availableOn": "✓ On {networks}",
    "coin.swapBtn": "Swap for {symbol}",
    "coin.swapHint": "You'll choose which of your holdings to pay with on the next screen.",
    "coin.swapNeedsWallet": "Unlock your wallet to swap.",
    "coin.swapNoRouter": "Swapping isn't enabled on this network yet.",
    "coin.swapUnavailableNetwork": "{symbol} can't be swapped on {network} yet. It has to be the network's own coin, or a token you've added with Add token.",
    "coin.swapUnavailableSwitchNetwork": "{symbol} is {network}'s own coin. Switch networks to swap or hold it there.",
    "coin.swapUnavailableSwitchNetworkTracked": "You've already added {symbol} on {network}. Switch there to use it.",
    "coin.swapUnavailableKnownElsewhere": "{symbol} is a verified token on {network}. Switch there to add it automatically.",
    "coin.switchNetworkBtn": "Switch to {network}",
    "coin.addOnNetworkBtn": "Add on {network}",
    "coin.buyBtn": "Buy {symbol}",
    "coin.holding": "You hold {amount} {symbol}",
    "coin.statsTitle": "Market stats",
    "coin.aboutTitle": "About",
    "coin.aboutUnavailable": "No description available right now.",
    "coin.marketCap": "Market cap",
    "coin.volume24h": "24h volume",
    "coin.high24h": "24h high",
    "coin.low24h": "24h low",
    "coin.supply": "Circulating supply",
    "coin.ath": "All-time high",
    "coin.viewCoingecko": "View on CoinGecko",
    "coin.loadError": "Couldn't load more details for this coin right now.",
    "coin.chartUnavailable": "Chart unavailable right now.",
    "swap.customAddressOption": "Other token (paste address)...",

    "predictions.title": "Currencies & Stablecoins",
    "predictions.description": "National currencies and the stablecoins pegged to them, with live prices -- informational only. Nothing about your wallet is sent to look these up.",
    "predictions.tabStable": "Stablecoins",
    "predictions.tabTop": "Top coins",
    "predictions.loading": "Loading...",
    "predictions.empty": "No stablecoin prices right now.",
    "predictions.cardUnavailable": "Stablecoin prices unavailable right now.",
    "predictions.volSuffix": "24h vol",

    "exchanges.title": "Hottest Exchanges",
    "exchanges.description": "CoinGecko's trust-score ranking of centralized crypto exchanges, refreshed automatically -- informational only. Token Exchange is self-custody and never routes trades through any of these; nothing about your wallet is sent to look this up.",
    "exchanges.loading": "Loading...",
    "exchanges.empty": "No exchange data available right now.",
    "exchanges.cardUnavailable": "Exchanges unavailable right now.",
    "exchanges.foundedYear": "Est. {year}",

    "buy.title": "Buy crypto",
    "buy.description1": "Buy is powered by Transak, a separate third-party service -- Token Exchange never touches your payment details.",
    "buy.noThirdPartyCallout": "Already hold some crypto? Skip Transak entirely -- swap it for what you need directly on-chain, no third party, no signup.",
    "buy.noThirdPartySwapBtn": "Swap instead",
    "buy.description2": "Transak's buy flow opens right here in the app, with your receiving address already filled in and locked -- nothing to paste, and purchased crypto can only go to your own wallet.",
    "buy.presetNote": "Preset to buy {symbol} -- you can still pick a different asset once Transak opens.",
    "buy.continueBtn": "Continue to Transak",
    "buy.pickerTitle": "Choose what to buy",
    "buy.pickerSearchPlaceholder": "Search coins by name or symbol",
    "buy.pickerCurrencies": "Currencies",
    "buy.pickerCrypto": "Crypto",
    "buy.changeCoinBtn": "Change coin",
    "buy.closeWidgetBtn": "← Close",

    "sell.title": "Sell for cash",
    "sell.description1": "Sell is powered by Transak, the same third-party service Buy uses -- Token Exchange never touches your payout details.",
    "sell.description2": "Transak's sell flow opens right here in the app and quotes you a cash payout. It will show you a deposit address to send your crypto to -- once Transak receives it, it converts and pays out to your linked bank account or card.",
    "sell.continueBtn": "Continue to Transak",
    "sell.closeWidgetBtn": "← Close",

    "support.title": "Help & support",
    "support.description": "Ask a question or tap a topic below. This runs entirely on your device -- nothing you type here is sent anywhere.",
    "support.inputPlaceholder": "Type a question...",

    "send.title": "Send",
    "send.assetLabel": "Asset",
    "send.assetToken": "Token (enter contract address)",
    "send.tokenAddressPlaceholder": "Token contract address (0x...)",
    "send.toLabel": "To address",
    "send.contactsBtn": "Contacts",

    "contacts.title": "Address book",
    "contacts.pickerHint": "Tap a contact to fill it in as the recipient.",
    "contacts.namePlaceholder": "Name",
    "contacts.addBtn": "Save contact",
    "contacts.empty": "No saved contacts yet.",
    "contacts.removeBtn": "Remove",
    "contacts.nameRequired": "Give this contact a name.",
    "contacts.invalidAddress": "Enter a valid 0x address.",
    "send.amountLabel": "Amount",
    "send.speedSlow": "Slow",
    "send.speedStandard": "Standard",
    "send.speedFast": "Fast",
    "send.invalidRecipient": "Enter a valid recipient address.",
    "send.invalidTokenAddress": "Enter a valid token contract address.",
    "send.sentStatus": "Sent! Tx hash: {txHash}",
    "send.confirmIntro": "Sending in {seconds}s -- you can still cancel.",
    "send.confirmSummary": "{amount} {asset} to {to}",
    "send.newAddressWarning": "You haven't sent to this address from this device before -- double check it's correct.",
    "send.poisonWarning": "This address looks a lot like one you've used before ({match}) but it isn't the same -- it starts and ends the same way while the middle is different. This is a common scam pattern (\"address poisoning\") where a lookalike is planted in your history hoping you'll copy the wrong one. Check every character before sending.",
    "send.cancelBtn": "Cancel send",
    "send.cancelledStatus": "Send cancelled -- nothing was sent.",
    "send.feeEstimateLoading": "Estimating network fee...",
    "send.feeEstimate": "Estimated network fee: ~{fee} {symbol} (~{usd})",
    "send.feeEstimateNoUsd": "Estimated network fee: ~{fee} {symbol}",
    "fee.burned": "Of that, ~{burn} {symbol} is burned (permanently removed from supply)",
    "send.scanBtn": "Scan QR code",
    "send.scanTitle": "Scan a wallet QR code",
    "send.scanClose": "Close",
    "send.scanHint": "Point the camera at a wallet address QR code.",
    "send.scanUnsupported": "QR scanning isn't supported in this browser. Paste the address instead.",
    "send.scanDenied": "Camera access was blocked. Allow the camera for this site, or paste the address.",
    "send.scanNoAddress": "That QR code doesn't contain a valid wallet address.",
    "send.scanFilled": "Address filled in. Double-check it before sending.",
    "activity.exportCsv": "Export as CSV",
    "activity.exportEmpty": "Nothing to export yet.",
    "settings.themeLabel": "Appearance",
    "settings.themeDark": "Dark (default)",
    "settings.themeLight": "Light",
    "settings.notifyLabel": "Notifications",
    "settings.notifyOff": "Off",
    "settings.notifyOn": "On",
    "settings.notifyHint": "Alerts you when a transaction confirms, funds arrive, or a price alert fires. Works only while this page is open in your browser.",
    "settings.notifyUnsupported": "This browser doesn't support system notifications. You'll still see messages inside the page.",
    "settings.notifyDenied": "Notifications are blocked for this site in your browser settings.",
    "settings.alertLabel": "Price alert (native coin)",
    "settings.alertAbove": "goes above",
    "settings.alertBelow": "drops below",
    "settings.alertPlaceholder": "Price",
    "settings.alertAdd": "Add",
    "settings.alertHint": "Uses your display currency. Each alert fires once, and only while this page is open.",
    "settings.alertRemove": "Remove alert",
    "settings.alertBadPrice": "Enter a price above zero.",
    "settings.alertNoFeed": "No price feed is available for this network right now.",
    "notify.txConfirmed": "Transaction confirmed",
    "notify.txFailed": "Transaction failed",
    "notify.received": "Funds received",
    "notify.priceAlert": "Price alert",
    "swap.bridgeLink": "Moving to another chain? Bridge your funds \u2197",
    "send.feeEstimateUnavailable": "Network fee estimate unavailable -- you'll still see the real fee before anything is broadcast.",
    "send.confirmFeeLine": "Network fee: ~{fee} {symbol}",
    "send.toPlaceholder": "0x... or name.eth",
    "send.resolvingName": "Looking up {name}...",
    "send.resolvedName": "Resolves to {address}",
    "send.nameNotFound": "Couldn't find an address for {name} -- double-check the name, or paste the address directly.",
    "send.nameResolutionUnsupported": "Name lookups aren't available on this network -- paste the address directly.",

    "swap.unsupportedWarning": "Swapping isn't enabled on this network yet -- no verified router configured. Add one in Settings → Networks first.",
    "swap.fromLabel": "From",
    "swap.toLabel": "To",
    "swap.selectBtn": "Select",
    "swap.balanceLabel": "Balance: {amount} {symbol}",
    "swap.maxBtn": "Max",
    "swap.quotingHint": "Getting quote…",
    "swap.emptyHint": "Pick the token you want to swap from, then the one you want to receive.",
    "swap.quickPickLabel": "Quick pick:",
    "swap.verifiedBadge": "Verified",
    "swap.verifiedTitle": "Contract address checked against the issuer's own published list",
    "swap.unverifiedBadge": "Unverified",
    "swap.unverifiedNote": "This token isn't on the verified list. Double-check the contract address before you swap -- anyone can create a token with any name.",
    "swap.rateLabel": "Rate",
    "swap.appFeeShortLabel": "App fee",
    "swap.priceImpactLabel": "Price impact",
    "swap.priceImpactWarn": "Price impact is about {percent}. Not much of this token is available to trade, so you'll get noticeably less than the going rate. Consider a smaller amount.",
    "swap.priceImpactHigh": "Price impact is very high (about {percent}). A large part of your amount is lost to the price move. Try a much smaller amount.",
    "swap.priceImpactConfirm": "Price impact is about {percent}. You will receive much less than the market rate. Swap anyway?",
    "app.name": "Token Exchange",
    "app.copyright": "© 2026 Token Exchange",
    "scan.button": "🔍 Scan wallet",
    "scan.title": "Scan wallet",
    "scan.intro": "Checks this account on the current network for popular, market-listed tokens and lists the ones it holds. Only public balances are read -- nothing is added until you tap Add, and tokens outside that list (including airdropped look-alikes) are never shown.",
    "scan.addAll": "Add all",
    "scan.again": "Scan again",
    "scan.scanning": "Scanning this account for tokens…",
    "scan.unsupported": "Scanning isn't available on this network yet. Use \"+ Add token\" and paste a contract address instead.",
    "scan.noAccount": "No account is selected.",
    "scan.noCatalog": "Couldn't reach CoinGecko, so only the verified stablecoins were checked.",
    "scan.none": "No new tokens found on this account.",
    "scan.add": "Add",
    "scan.adding": "Adding…",
    "scan.added": "Added ✓",
    "swap.minReceivedLabel": "Minimum received",
    "swap.networkFeeLabel": "Network fee",
    "swap.gasStep_approve": "Approve",
    "swap.gasStep_fee": "App fee transfer",
    "swap.gasStep_swap": "Swap",
    "swap.gasPriceLabel": "Gas price",
    "swap.gasUnavailable": "Unavailable",
    "swap.gasLowEth": "Heads up: network fees for this swap are about {need} {symbol}, but this account only has {have}. Add a little {symbol} first or the transaction will fail.",
    "swap.selectAssetTitle": "Select asset",
    "swap.selectTokenTitle": "Select token",
    "swap.pickerSearchPlaceholder": "Enter token name or paste address",
    "swap.pickerNoFavs": "No starred tokens on this network yet. Tap the star on a token to add it.",
    "swap.pickerInfoTitle": "View on block explorer",
    "swap.pickerStarTitle": "Star token",
    "swap.pickerNoMatch": "No matching token on this network.",
    "swap.pickerLoadFailed": "Couldn't load the token list. Check your connection and try again.",
    "swap.pickerNothingHeld": "Nothing on this network has a balance yet. Add funds, or switch network above.",
    "swap.pickerUseAddress": "Use this token address",
    "swap.pickerLoadingTokens": "Searching tokens...",
    "swap.pickerTopTokens": "Top tokens on this network",
    "swap.pickerSearchResults": "Search results",
    "swap.pickerSuggested": "Suggested stablecoins (issuer-verified)",
    "swap.pickerNoSwapHere": "Swapping isn't enabled on this network yet. Pick another network above.",
    "swap.noAssetsHint": "Nothing available here yet.",
    "swap.appFeeLine": "App fee ({percent}): {amount}",
    "swap.slippageLabel": "Slippage tolerance",
    "swap.approveBtn": "Approve token first",
    "swap.approvingStatus": "Approving...",
    "swap.approvedStatus": "Approved. You can swap now.",
    "swap.sendingStatus": "Sending fee + swapping...",
    "swap.swappedStatus": "Swapped! Fee tx: {feeTx} | Swap tx: {tx}",
    "swap.feeTxNa": "n/a",

    "settings.title": "Settings",
    "settings.addAccountBtn": "Add account",
    "settings.importKeyBtn": "Import private key",
    "settings.addWatchBtn": "Add watch-only address",
    "settings.approvalsBtn": "Manage approvals",
    "settings.addNetworkBtn": "Add network",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "Address book",
    "settings.currencyLabel": "Display currency",
    "settings.navStyleLabel": "Navigation style",
    "settings.navCube": "Cube",
    "settings.navGlobe": "Globe",
    "settings.viewSeedBtn": "View recovery phrase",
    "settings.helpBtn": "Help & support",
    "settings.feedbackBtn": "Request a feature",
    "settings.sendDelayLabel": "Send delay (cancel window)",
    "settings.sendDelayHint": "Holds every outgoing send for this long so you have a chance to cancel it before it's broadcast. This only covers sends made here in Token Exchange -- it can't protect a wallet whose private key or recovery phrase has already been exposed outside the app.",

    "settings.autoLockLabel": "Auto-lock after inactivity",
    "settings.autoLockOff": "Off (never auto-lock)",
    "settings.autoLock1": "1 minute",
    "settings.autoLock5": "5 minutes",
    "settings.autoLock15": "15 minutes",
    "settings.autoLock21": "21 minutes (default)",
    "settings.autoLock30": "30 minutes",
    "settings.autoLockHint": "Locks the wallet automatically after this much time with no clicks, taps, or keystrokes here -- since a browser tab you leave open otherwise stays unlocked indefinitely.",
    "settings.sendDelayOff": "Off (send immediately)",
    "settings.sendDelay15": "15 seconds",
    "settings.sendDelay30": "30 seconds (recommended)",
    "settings.sendDelay60": "60 seconds",
    "settings.lockBtn": "Lock wallet",
    "settings.resetBtn": "Reset wallet",

    "feedback.title": "Feature requests",
    "feedback.subtitle": "See what other users are asking for, upvote the ones you want too, or post your own. This list is public -- it's how we decide what to build next.",
    "feedback.titlePlaceholder": "Short title (e.g. \"Dark mode\")",
    "feedback.descPlaceholder": "A bit more detail (optional)",
    "feedback.submitBtn": "Post request",
    "feedback.submittingStatus": "Posting...",
    "feedback.submittedStatus": "Thanks! Your request is live below.",
    "feedback.listTitle": "REQUESTS",
    "feedback.empty": "No requests yet -- be the first!",
    "feedback.loadError": "Couldn't load requests. Try again in a moment.",
    "feedback.titleRequired": "Give it a short title first.",
    "feedback.upvoteBtn": "Upvote",
    "feedback.upvotedBtn": "Upvoted",
    "feedback.contactLine": "Prefer email? Reach us at msandersod@gmail.com",

    "importKey.title": "Import private key",
    "importKey.description": "This adds a separate account to this wallet from a raw private key, not from your recovery phrase -- back it up on its own, since your recovery phrase won't restore it. Never share a private key with anyone; anyone who has it can spend everything in that account.",
    "importKey.placeholder": "0x private key",

    "addWatch.title": "Add watch-only address",
    "addWatch.description": "Tracks an address's balance, tokens, and activity without holding a key for it -- there's nothing here to sign with, so Send and Swap stay off for it. Useful for keeping an eye on a cold-storage or hardware-wallet address from here.",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "Label (optional)",
    "addWatch.submitBtn": "Add",

    "approvals.title": "Manage approvals",
    "approvals.description": "Shows token spending approvals for this wallet's own swap router, plus a manual lookup for any other token and spender. Revoking sets the allowance back to zero -- the spender can no longer move that token on your behalf until you approve it again.",
    "approvals.emptyText": "No approvals found for the tokens you've added.",
    "approvals.loading": "Checking allowances...",
    "approvals.manualHeading": "Check a specific approval",
    "approvals.tokenPlaceholder": "Token contract address (0x...)",
    "approvals.spenderPlaceholder": "Spender contract address (0x...)",
    "approvals.checkBtn": "Check",
    "approvals.tokenLabel": "Token:",
    "approvals.spenderLabel": "Spender:",
    "approvals.allowanceLabel": "Allowance:",
    "approvals.revokeBtn": "Revoke",
    "approvals.revokingBtn": "Revoking...",
    "approvals.rowError": "Couldn't check this one -- try again in a moment.",

    "wc.title": "WalletConnect",
    "wc.subtitle": "Connect to any dapp that offers a \"WalletConnect\" option -- paste the wc:... URI from its connect-wallet QR code below.",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "Connect",
    "wc.notConfigured": "WalletConnect needs a free Project ID before it can connect to anything -- see lib/walletconnect-config.js.",
    "wc.sessionsTitle": "Connected dapps",
    "wc.sessionsEmpty": "No dapps connected yet.",
    "wc.disconnectBtn": "Disconnect",
    "wc.invalidUri": "That doesn't look like a WalletConnect URI -- it should start with \"wc:\".",
    "wc.pairingStatus": "Pairing... a connection request should appear in a moment.",
    "wc.pairedStatus": "Paired -- check for a new window asking you to approve the connection.",

    "addNetwork.title": "Add network",
    "addNetwork.namePlaceholder": "Network name",
    "addNetwork.chainIdPlaceholder": "Chain ID (number)",
    "addNetwork.rpcPlaceholder": "RPC URL",
    "addNetwork.symbolPlaceholder": "Native currency symbol",
    "addNetwork.explorerPlaceholder": "Block explorer URL (optional)",
    "addNetwork.routerPlaceholder": "Verified swap router address (optional)",
    "addNetwork.routerWarning": "Only fill in the router address if you've personally verified it against the project's official docs or the chain's block explorer. Leave blank if unsure -- swapping will simply be disabled for this network until you add one.",
    "addNetwork.addBtn": "Add",

    "viewSeed.title": "Recovery phrase",
    "viewSeed.passwordPlaceholder": "Enter password to reveal",
    "viewSeed.revealBtn": "Reveal",

    "reset.title": "Reset wallet",
    "reset.warning": "This deletes the encrypted wallet from this browser. Make sure you have your recovery phrase backed up -- this cannot be undone.",
    "reset.confirmBtn": "Yes, delete everything",

    "approve.unlockTitle": "Unlock to continue",
    "approve.unlockOriginText": "{origin} is requesting access.",
    "approve.connectTitle": "Connection request",
    "approve.connectWantsText": "{origin} wants to connect to your wallet.",
    "approve.accountLabel": "Account: ",
    "approve.acceptConnectBtn": "Connect",
    "approve.txTitle": "Transaction request",
    "approve.toLabel": "To:",
    "approve.valueLabel": "Value:",
    "approve.dataLabel": "Data:",
    "approve.txWarning": "Only approve this if you trust the site and understand what it's asking you to sign.",
    "approve.confirmBtn": "Confirm",
    "approve.signTitle": "Signature request",
    "approve.signBtn": "Sign",
    "approve.addNetTitle": "Add network request",
    "approve.addNetNameLabel": "Name:",
    "approve.addNetChainIdLabel": "Chain ID:",
    "approve.addNetRpcLabel": "RPC:",
    "approve.addNetWarning": "This site's suggested network has no verified swap router. Swapping will stay disabled on it until you add one yourself in Settings.",
    "approve.addNetBtn": "Add network",
    "approve.switchNetTitle": "Switch network request",
    "approve.switchNetText": "{origin} wants to switch your wallet from {from} to {to}.",
    "approve.switchNetWarning": "Only switch if you expect this. Transactions you approve afterwards will be sent on the new network.",
    "approve.switchNetBtn": "Switch network",
    "approve.contractCreation": "(contract creation)",
    "approve.nativeSuffix": " (native)",
    "approve.decodedLoading": "Reading what this actually does...",
    "approve.decodedTransferLine": "This will transfer {amount} to {to}.",
    "approve.decodedApproveLine": "This will approve {amount} for {to} to spend.",
    "approve.decodedUnlimited": "UNLIMITED {symbol}",
    "approve.decodedThisToken": "this token",
    "approve.decodedRawUnitsSuffix": " raw units (couldn't confirm this token's decimals)",
    "approve.decodedGenericIntro": "This calls \"{fn}\" on the contract above with:",

    "loading.text": "Loading...",

    "home.tabHome": "Home",
    "home.tabAssets": "Assets",
    "home.tabActivity": "Activity",
    "home.tabSend": "Send",
    "home.tapToContinue": "Tap to continue",
    "home.continueBtn": "Continue",

    "activity.title": "Activity",
    "activity.subtitle": "A local record of sends made from this wallet, plus incoming transfers this device has noticed -- nothing here is fetched from a server.",
    "activity.empty": "No activity yet -- sends you make (and incoming transfers this device notices) will show up here.",
    "activity.sentLabel": "Sent {amount} {asset}",
    "activity.receivedLabel": "Received {amount} {asset}",
    "activity.toLabel": "to {address}",
    "activity.statusSent": "Sent",
    "activity.tabSends": "Sends",
    "activity.tabSwaps": "Swaps",
    "activity.swapsSubtitle": "A local record of swaps made from this wallet on this device -- nothing here is fetched from a server.",
    "activity.swapsEmpty": "No swaps yet -- swaps you make from this wallet will show up here.",
    "activity.swapLabel": "Swapped {amountIn} {assetIn} for about {amountOut} {assetOut}",
    "activity.statusSwapped": "Swapped",
    "activity.statusReceived": "Received",
    "activity.receivedApproxNote": "Detected from a balance change -- approximate, no transaction link available",
    "activity.viewOnExplorer": "View on block explorer",

    "footer.nonCustodial": "Non-custodial — your keys never leave this device",

    "errors.passwordTooShort": "Password must be at least 8 characters.",
    "errors.passwordMismatch": "Passwords don't match.",
    "common.usernameLabel": "Username (shown when you unlock)",
    "common.usernamePlaceholder": "Username",
    "unlock.welcomeBack": "Welcome back, {name}",
    "errors.usernameRequired": "Enter a username (up to 30 characters).",
    "onboarding.webNoticeSummary": "You're using the website version -- the browser extension is safer for everyday use.",
    "onboarding.webNoticeBody": "This site encrypts your wallet and stores it only in this browser (nowhere else) -- but a website is an easier target for phishing/DNS/lookalike-domain tricks than an installed browser extension, which is why MetaMask and similar wallets don't ship a key-holding website at all. Use the extension for anything you can't afford to lose.",
    "onboarding.signInLink": "Sign in to restore a backed-up wallet",
    "signin.title": "Sign in",
    "signin.intro": "Restore a wallet you've already backed up to a Token Exchange account on another device.",
    "account.title": "Account backup",
    "account.intro": "Optional: back up an encrypted copy of this wallet to a Token Exchange account so you can restore it on another device. Token Exchange never sees your password or your unencrypted wallet -- only your recovery phrase can restore your funds if you forget your account password.",
    "account.unavailable": "Account backup isn't available on this server right now.",
    "account.usernameLabel": "Username",
    "account.passwordLabel": "Password (must match this wallet's password)",
    "account.createBtn": "Create account & back up",
    "account.backupNow": "Back up now",
    "account.signOut": "Sign out",
    "account.changePasswordTitle": "Change password",
    "account.changePasswordNote": "Changes both your wallet password and your account password together -- they always match.",
    "account.currentPasswordPlaceholder": "Current password",
    "account.newPasswordPlaceholder": "New password",
    "account.confirmNewPasswordPlaceholder": "Confirm new password",
    "account.deleteTitle": "Delete account",
    "account.deleteNote": "Deletes your online backup only -- the wallet on this device is unaffected.",
    "account.deleteBtn": "Delete account",
    "scan.button": "🔍 Scan wallet",
    "scan.title": "Scan wallet",
    "scan.intro": "Checks this account on the current network for popular, market-listed tokens and lists the ones it holds. Only public balances are read -- nothing is added until you tap Add, and tokens outside that list (including airdropped look-alikes) are never shown.",
    "scan.addAll": "Add all",
    "scan.again": "Scan again",
    "errors.net.unreachable": "Couldn't reach the network. Check your connection and try again.",
    "errors.net.noFunds": "Not enough of this network's coin (ETH on Base) to pay the network fee. Add a small amount and try again.",
    "errors.net.cancelled": "That request was cancelled.",
    "errors.net.nonce": "That transaction couldn't be sent right now -- please try again.",
    "errors.net.feesChanged": "Network fees just changed -- please try again.",
    "errors.net.timeout": "The network took too long to respond. Please try again.",
    "errors.net.rateLimit": "Too many requests right now -- please wait a moment and try again.",
    "errors.net.rejected": "The network rejected this request. Double-check the details and try again.",
    "errors.net.gasEstimate": "The network wouldn't accept this transaction. Check you have enough ETH for the network fee, then try again.",
    "errors.net.noResponse": "Couldn't get a response from the network. Please try again.",
    "errors.net.generic": "Something went wrong talking to the network. Please try again.",
    "errors.unknownError": "Unknown error",

    "swap.getQuoteBtn": "Get quote",
    "swap.netAmountLine": "Net amount swapped: {amount}",
    "swap.estimatedOutLine": "Estimated to receive: {amount}",
    "swap.appFeeValue": "{percent} ({amount} {symbol})",
    "main.findNftsBtn": "🔍 Find NFTs",
    "findNfts.title": "Find NFTs",
    "findNfts.description": "Scans this account's address on the current network and lists what it holds, using Alchemy's NFT API. This only reads public on-chain ownership data -- nothing about your wallet is sent anywhere except the address you're already using.",
    "findNfts.loadMore": "Load more",
    "swap.flipBtnTitle": "Swap direction",
    "findNfts.loading": "Looking for NFTs...",
    "findNfts.notConfigured": "NFT lookup isn't set up on this server yet.",
    "findNfts.notSupported": "NFT lookup isn't available on this network.",
    "findNfts.empty": "No NFTs found for this account on this network.",
    "findNfts.loadError": "Couldn't load NFTs. Try again in a moment.",
    "findNfts.addedBtn": "Already added",
    "findNfts.addBtn": "Add to my NFTs",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "How do I create a wallet?",
      keywords: ["create wallet", "create a wallet", "new wallet", "set up wallet", "setup wallet", "get started", "first time"],
      answer: "Tap “Create a new wallet” on the welcome screen, choose a password (this only unlocks the wallet on this device -- it can't recover your funds), and you'll be shown a 12-word recovery phrase. Write it down somewhere safe before continuing -- that phrase is the only way to recover your funds if this device is ever lost.",
    },
    {
      id: "import-wallet",
      chip: "How do I import an existing wallet?",
      keywords: ["import wallet", "import an existing", "restore wallet", "existing wallet", "import recovery", "import seed"],
      answer: "On the welcome screen tap “Import an existing wallet,” enter your 12- or 24-word recovery phrase exactly as written (lowercase, space-separated), then set a new password for this device. The phrase itself never leaves your device -- it's used locally to derive your accounts.",
    },
    {
      id: "forgot-password",
      chip: "I forgot my password",
      keywords: ["forgot password", "forgot my password", "wrong password", "can't unlock", "cant unlock", "locked out", "password not working", "password isn't working"],
      answer: "Your password only unlocks the wallet on this device -- Token Exchange never stores it anywhere and can't reset it for you. If you don't remember it, tap “Reset wallet instead” on the unlock screen, then import your wallet again using your 12-word recovery phrase. If you don't have that phrase saved, the funds in this wallet unfortunately can't be recovered -- that's the trade-off of a non-custodial wallet: nobody but you can ever unlock it, which also means nobody but you can rescue it.",
    },
    {
      id: "lost-seed-phrase",
      chip: "I lost my recovery phrase",
      keywords: ["lost seed", "lost my seed", "lost recovery phrase", "lost my recovery", "don't have my phrase", "dont have my phrase", "forgot my phrase", "never wrote it down", "didn't save"],
      answer: "If you're still logged in, go to Settings → “View recovery phrase,” re-enter your password, and write it down now somewhere safe. If you're locked out AND you never saved the phrase, there is no way to recover the wallet or the funds in it. Token Exchange never stores your phrase anywhere -- on a server, in the cloud, anywhere -- so no one, including the developer, can retrieve it for you.",
    },
    {
      id: "balance-not-showing",
      chip: "My balance isn't showing",
      keywords: ["balance", "zero balance", "0.00", "not showing", "wrong balance", "balance stuck", "still loading", "balance is 0"],
      answer: "A balance stuck on “...” usually means that network's RPC endpoint is slow or briefly down -- this wallet automatically retries a backup endpoint after a few seconds, so it usually clears up on its own. If it settles on 0 and that seems wrong, double-check you're on the right network and the right account (both dropdowns are on the main screen) -- balances are tracked separately per network and per account, so funds on Base won't show while Ethereum Mainnet is selected, for example.",
    },
    {
      id: "swap-failed",
      chip: "My swap failed",
      keywords: ["swap failed", "swap stuck", "swap not working", "swap error", "quote failed", "swap didn't work", "swap isn't working"],
      answer: "Swaps happen on-chain through a public decentralized exchange router, so a failure is usually one of three things: not enough balance to cover the amount plus network gas, a slippage tolerance set too tight for a fast-moving price (try 1% or 3% instead of 0.5%), or that token pair not having enough liquidity on that network's router yet. The error shown on the Swap screen after “Get quote” usually points to which one -- if it's unclear, try again with a smaller amount first.",
    },
    {
      id: "swap-fee",
      chip: "What does a swap cost?",
      keywords: ["swap fee", "how much does it cost", "0.5%", "swap charge", "fee on swap", "what's the fee", "whats the fee"],
      answer: "Swaps carry a flat 0.5% fee on the amount you're swapping, shown clearly on the quote before you confirm -- it's part of the swap transaction itself, never a hidden markup buried in the exchange rate. That's separate from network gas, which goes to the blockchain, not to Token Exchange.",
    },
    {
      id: "gas-fees",
      chip: "What is a gas fee?",
      keywords: ["gas fee", "network fee", "transaction fee", "what is gas", "gas cost"],
      answer: "Gas is the fee the blockchain network itself charges to process a transaction -- it's separate from Token Exchange's 0.5% swap fee and goes entirely to the network, not to us. The amount varies with network congestion at the time. Make sure you hold enough of that network's native coin (ETH, BNB, POL, etc.) to cover gas, even when you're sending a token rather than the native coin.",
    },
    {
      id: "add-network",
      chip: "How do I add a network?",
      keywords: ["add network", "add a network", "new network", "custom network", "another chain", "different chain"],
      answer: "Go to Settings → “Add network” and fill in the network's name, chain ID, RPC URL, and native currency symbol. If you also add a verified swap router address there, swapping will work on that network too -- otherwise it'll just handle sending and receiving. Only use values you've personally verified against that network's official docs or block explorer.",
    },
    {
      id: "add-token",
      chip: "How do I track a token?",
      keywords: ["add token", "track token", "new token", "custom token", "erc-20", "erc20", "track a token"],
      answer: "On the main screen tap “+ Add token,” paste the token's contract address for your current network, and tap “Look up” -- it reads the token's name, symbol, and decimals straight from the contract so you can confirm before adding it. Only add a token whose contract address came from a source you trust; a wallet can't tell a real token apart from a fake one using the same name and symbol.",
    },
    {
      id: "send-crypto",
      chip: "How do I send crypto?",
      keywords: ["how do i send", "send crypto", "send tokens", "transfer crypto", "send eth", "send funds"],
      answer: "Tap “Send” on the main screen, choose the native coin or a token (by its contract address), enter the recipient's address and an amount, and confirm. Double-check the address before confirming -- sends on these networks are irreversible once they go through.",
    },
    {
      id: "connect-dapp",
      chip: "How do I connect to a website?",
      keywords: ["connect dapp", "connect to a website", "connect wallet button", "connect to a site", "won't connect", "wont connect"],
      answer: "Any site with a “Connect Wallet” button that supports browser wallet extensions should offer Token Exchange the same way it would MetaMask or Coinbase Wallet. If a site doesn't show it as an option, try refreshing the page after the wallet is installed and unlocked -- some sites only detect wallet extensions on page load.",
    },
    {
      id: "buy-not-working",
      chip: "Buy or Sell isn't working",
      keywords: ["buy button", "sell button", "buy isn't working", "sell isn't working", "buy not working", "sell not working", "buy not configured", "sell not configured", "transak", "can't buy", "cant buy", "can't sell", "cant sell"],
      answer: "Buy and Sell both open Transak, a separate third-party on-ramp/off-ramp, in a new tab. If it says the service “isn't set up yet,” that means this wallet's developer hasn't added Transak credentials yet -- it's not something you can fix from inside the wallet itself. Once it is configured, your receiving address is filled in and locked automatically for Buy; Token Exchange never sends it on your behalf.",
    },
    {
      id: "reset-wallet",
      chip: "How do I reset my wallet?",
      keywords: ["reset wallet", "delete wallet", "start over", "remove wallet", "wipe wallet"],
      answer: "Settings → “Reset wallet” permanently deletes the encrypted wallet from this browser. Make absolutely sure you have your recovery phrase backed up first -- this can't be undone, and there's no way to get the wallet back afterward without that phrase.",
    },
    {
      id: "is-it-safe",
      chip: "Is this wallet safe?",
      keywords: ["is this safe", "is it safe", "trust this", "non-custodial", "custodial", "is this secure", "is this a scam", "legit"],
      answer: "Token Exchange is non-custodial: your recovery phrase and private keys are encrypted and stored only in your browser -- never sent to any server, because there isn't one. That also means no one, including the developer, can recover your funds if you lose both your password and your recovery phrase. Sends and swaps are also checked against a bundled sanctions list before they go out, entirely on-device, and swap fees are always shown up front before you confirm.",
    },
    {
      id: "pending-transaction",
      chip: "My transaction is stuck",
      keywords: ["pending", "stuck transaction", "transaction not confirming", "still pending", "transaction stuck"],
      answer: "A transaction can sit “pending” if the network is congested or the gas price it used was too low for current conditions. It should confirm eventually on its own. If it's been stuck a long time, you can look up the transaction on that network's block explorer using your account address to see its real-time status.",
    },
    {
      id: "wrong-network",
      chip: "Which networks are supported?",
      keywords: ["which network", "wrong network", "switch network", "supported networks", "which chains", "supported chains", "what networks"],
      answer: "Built in: Ethereum, Base, Polygon, BNB Chain, Arbitrum One, and OP Mainnet, switchable from the dropdown near the bottom of the main screen -- your balance, tokens, and swap options are all specific to whichever network is selected there. You can add any other EVM-compatible network yourself from Settings → “Add network.”",
    },
    {
      id: "contact-human",
      chip: "I need more help",
      keywords: ["talk to a human", "real person", "contact support", "contact you", "still need help", "need more help", "speak to someone"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "Hi! I'm a simple built-in help bot -- I can only answer questions from a fixed list written ahead of time, nothing more. Tap a topic below or type your own question.";
  const fallbackWithEmail = "I don't have a written answer for that yet. You can reach a person at {email} -- it helps to mention which screen you were on and what you expected to happen.";
  const fallbackNoEmail = "I don't have a written answer for that yet, and this wallet doesn't have a live human support line set up yet either. Try rephrasing your question, or check the extension's README for more detail on how each feature works.";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.en = {
    name: "English",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
