// lib/i18n/es.js
// Spanish (neutral/international) localization. Must define the exact same
// `strings` keys and the exact same FAQ `id`s as lib/i18n/en.js -- see that
// file's header comment for details.
(function () {
  const strings = {
    "common.needHelp": "¿Necesitas ayuda?",
    "common.languageLabel": "Idioma",
    "common.back": "Atrás",
    "common.cancel": "Cancelar",
    "common.copy": "Copiar",
    "common.send": "Enviar",
    "common.swap": "Intercambiar",
    "common.buy": "Comprar",
    "common.livePrices": "Precios en vivo",
    "common.reject": "Rechazar",
    "common.passwordPlaceholder": "Contraseña",
    "common.confirmPasswordPlaceholder": "Confirmar contraseña",
    "common.newPasswordLabel": "Nueva contraseña (mín. 8 caracteres)",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "Dirección del token (0x...)",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "Moneda nativa",

    "onboarding.title": "Bienvenido",
    "onboarding.subtitle": "Configura tu billetera para comenzar.",
    "onboarding.createBtn": "Crear una billetera nueva",
    "onboarding.importBtn": "Importar una billetera existente",

    "create.title": "Crear billetera",
    "create.passwordLabel": "Nueva contraseña (mín. 8 caracteres)",
    "create.passwordWarning": "Esta contraseña desbloquea tu billetera en este dispositivo. No existe forma de recuperarla -- solo tu frase de recuperación puede restaurar tus fondos.",
    "create.continueBtn": "Continuar",
    "create.backupWarning": "Anota esta frase de recuperación y guárdala en un lugar seguro. Cualquiera que la tenga puede apoderarse de todo lo que hay en esta billetera. Token Exchange no puede recuperarla por ti.",
    "create.backupCheckbox": "Ya guardé mi frase de recuperación",
    "create.finishBtn": "Finalizar",

    "import.title": "Importar billetera",
    "import.mnemonicLabel": "Frase de recuperación (12 o 24 palabras)",
    "import.mnemonicPlaceholder": "palabra1 palabra2 palabra3 ...",
    "import.submitBtn": "Importar",

    "unlock.title": "Desbloquear",
    "unlock.submitBtn": "Desbloquear",
    "unlock.resetInsteadBtn": "Restablecer billetera en su lugar",

    "main.settingsTitle": "Configuración",
    "main.portfolioLabel": "Saldo total",
    "main.addAccountOption": "+ Agregar cuenta",
    "main.tokensTitle": "Tokens",
    "main.addTokenBtn": "+ Agregar token",
    "main.tokensEmpty": "Aún no has agregado tokens -- toca “+ Agregar token” e ingresa una dirección de contrato para hacer seguimiento de uno.",
    "main.networkLabel": "Red",
    "main.balanceFetchErrorPrefix": "No se pudo obtener el saldo: ",
    "main.watchOnlySuffix": "(Observando)",
    "main.watchOnlyNotice": "Estás viendo una dirección de solo observación -- no hay una clave privada para ella en esta wallet, así que Enviar e Intercambiar están desactivados aquí.",

    "tokens.loadError": "No se pudo cargar el saldo",
    "tokens.removeTitle": "Eliminar",

    "addToken.title": "Agregar token",
    "addToken.description": "Ingresa la dirección del contrato del token en la red actual. Agrega solo un token cuya dirección de contrato provenga de una fuente de confianza -- una billetera no puede distinguir un token real de uno falso con el mismo nombre.",
    "addToken.addressLabel": "Dirección de contrato del token",
    "addToken.lookupBtn": "Buscar",
    "addToken.nameLabel": "Nombre:",
    "addToken.symbolLabel": "Símbolo:",
    "addToken.decimalsLabel": "Decimales:",
    "addToken.confirmBtn": "Agregar a mi billetera",
    "addToken.invalidAddress": "Ingresa una dirección de contrato válida.",
    "addToken.noName": "(sin nombre)",
    "addToken.swapUnavailableSuffix": " (intercambio no disponible)",

    "prices.description": "Precios en USD de la API pública de CoinGecko. Solo con fines informativos -- no se envía ningún dato de tu billetera para consultarlos.",
    "prices.loading": "Cargando...",
    "prices.naText": "n/d",

    "buy.title": "Comprar criptomonedas",
    "buy.description1": "La función Comprar funciona con MoonPay, un servicio de terceros independiente -- Token Exchange nunca tiene acceso a tus datos de pago.",
    "buy.noThirdPartyCallout": "¿Ya tienes algo de cripto? Sáltate MoonPay por completo: intercámbialo directamente en la cadena por lo que necesites, sin terceros ni registro.",
    "buy.noThirdPartySwapBtn": "Intercambiar en su lugar",
    "buy.description2Html": "MoonPay se abre aquí mismo, abajo. Como esta billetera no puede firmar solicitudes de forma segura con una clave secreta (esa clave nunca debe existir dentro de una extensión de navegador -- consulta <code>lib/buy-config.js</code>), <strong>pega tu dirección de recepción tú mismo</strong> una vez que se cargue:",
    "buy.continueBtn": "Continuar a MoonPay",

    "support.title": "Ayuda y soporte",
    "support.description": "Haz una pregunta o toca un tema abajo. Esto funciona por completo en tu dispositivo -- nada de lo que escribas aquí se envía a ningún lugar.",
    "support.inputPlaceholder": "Escribe una pregunta...",

    "send.title": "Enviar",
    "send.assetLabel": "Activo",
    "send.assetToken": "Token (ingresa la dirección de contrato)",
    "send.tokenAddressPlaceholder": "Dirección de contrato del token (0x...)",
    "send.toLabel": "Dirección de destino",
    "send.amountLabel": "Monto",
    "send.speedSlow": "Lenta",
    "send.speedStandard": "Estándar",
    "send.speedFast": "Rápida",
    "send.invalidRecipient": "Ingresa una dirección de destinatario válida.",
    "send.invalidTokenAddress": "Ingresa una dirección de contrato de token válida.",
    "send.sentStatus": "¡Enviado! Hash de la transacción: {txHash}",
    "send.poisonWarning": "Esta dirección se parece mucho a una que ya usaste ({match}) pero no es la misma -- empieza y termina igual, pero el medio es diferente. Este es un patrón de estafa común (\"envenenamiento de direcciones\") en el que se planta una dirección similar en tu historial esperando que copies la incorrecta. Revisa cada carácter antes de enviar.",

    "swap.unsupportedWarning": "El intercambio aún no está habilitado en esta red -- no hay un router verificado configurado. Agrega uno primero en Configuración → Redes.",
    "swap.fromLabel": "De",
    "swap.toLabel": "A",
    "swap.getQuoteBtn": "Obtener cotización",
    "swap.appFeeLine": "Comisión de la app ({percent}): {amount}",
    "swap.netAmountLine": "Monto neto intercambiado: {amount}",
    "swap.estimatedOutLine": "Estimado a recibir: {amount}",
    "swap.slippageLabel": "Tolerancia de deslizamiento",
    "swap.approveBtn": "Aprobar token primero",
    "swap.approvingStatus": "Aprobando...",
    "swap.approvedStatus": "Aprobado. Ya puedes intercambiar.",
    "swap.sendingStatus": "Enviando comisión e intercambiando...",
    "swap.swappedStatus": "¡Intercambio realizado! Tx de comisión: {feeTx} | Tx de intercambio: {tx}",
    "swap.feeTxNa": "n/d",

    "settings.title": "Configuración",
    "settings.addAccountBtn": "Agregar cuenta",
    "settings.importKeyBtn": "Importar clave privada",
    "settings.addWatchBtn": "Agregar dirección de solo observación",
    "settings.approvalsBtn": "Gestionar aprobaciones",
    "settings.addNetworkBtn": "Agregar red",
    "settings.viewSeedBtn": "Ver frase de recuperación",
    "settings.helpBtn": "Ayuda y soporte",
    "settings.lockBtn": "Bloquear billetera",
    "settings.resetBtn": "Restablecer billetera",

    "importKey.title": "Importar clave privada",
    "importKey.description": "Esto agrega una cuenta independiente a esta wallet a partir de una clave privada sin procesar, no de tu frase de recuperación -- haz una copia de seguridad de esta clave por separado, ya que tu frase de recuperación no la restaurará. Nunca compartas una clave privada con nadie; cualquiera que la tenga puede gastar todo lo que hay en esa cuenta.",
    "importKey.placeholder": "Clave privada 0x",

    "addWatch.title": "Agregar dirección de solo observación",
    "addWatch.description": "Rastrea el saldo, los tokens y la actividad de una dirección sin tener su clave -- no hay nada aquí con qué firmar, así que Enviar e Intercambiar permanecen desactivados para ella. Útil para vigilar una dirección de almacenamiento en frío o de hardware wallet desde aquí.",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "Etiqueta (opcional)",
    "addWatch.submitBtn": "Agregar",

    "approvals.title": "Gestionar aprobaciones",
    "approvals.description": "Muestra las aprobaciones de gasto de tokens para el router de intercambio propio de esta wallet, además de una búsqueda manual para cualquier otro token y gastador. Revocar deja la aprobación en cero -- el gastador ya no podrá mover ese token en tu nombre hasta que lo apruebes de nuevo.",
    "approvals.emptyText": "No se encontraron aprobaciones para los tokens que agregaste.",
    "approvals.loading": "Comprobando aprobaciones...",
    "approvals.manualHeading": "Comprobar una aprobación específica",
    "approvals.tokenPlaceholder": "Dirección del contrato del token (0x...)",
    "approvals.spenderPlaceholder": "Dirección del contrato del gastador (0x...)",
    "approvals.checkBtn": "Comprobar",
    "approvals.tokenLabel": "Token:",
    "approvals.spenderLabel": "Gastador:",
    "approvals.allowanceLabel": "Aprobación:",
    "approvals.revokeBtn": "Revocar",
    "approvals.revokingBtn": "Revocando...",
    "approvals.rowError": "No se pudo comprobar esta -- intenta de nuevo en un momento.",

    "addNetwork.title": "Agregar red",
    "addNetwork.namePlaceholder": "Nombre de la red",
    "addNetwork.chainIdPlaceholder": "ID de cadena (número)",
    "addNetwork.rpcPlaceholder": "URL de RPC",
    "addNetwork.symbolPlaceholder": "Símbolo de la moneda nativa",
    "addNetwork.explorerPlaceholder": "URL del explorador de bloques (opcional)",
    "addNetwork.routerPlaceholder": "Dirección del router de intercambio verificado (opcional)",
    "addNetwork.routerWarning": "Completa la dirección del router solo si la has verificado personalmente contra la documentación oficial del proyecto o el explorador de bloques de la cadena. Déjala en blanco si no estás seguro -- el intercambio simplemente quedará deshabilitado para esta red hasta que agregues una.",
    "addNetwork.addBtn": "Agregar",

    "viewSeed.title": "Frase de recuperación",
    "viewSeed.passwordPlaceholder": "Ingresa la contraseña para revelarla",
    "viewSeed.revealBtn": "Revelar",

    "reset.title": "Restablecer billetera",
    "reset.warning": "Esto elimina la billetera cifrada de este navegador. Asegúrate de tener respaldada tu frase de recuperación -- esta acción no se puede deshacer.",
    "reset.confirmBtn": "Sí, eliminar todo",

    "approve.unlockTitle": "Desbloquea para continuar",
    "approve.unlockOriginText": "{origin} está solicitando acceso.",
    "approve.connectTitle": "Solicitud de conexión",
    "approve.connectWantsText": "{origin} quiere conectarse a tu billetera.",
    "approve.accountLabel": "Cuenta: ",
    "approve.acceptConnectBtn": "Conectar",
    "approve.txTitle": "Solicitud de transacción",
    "approve.toLabel": "Para:",
    "approve.valueLabel": "Valor:",
    "approve.dataLabel": "Datos:",
    "approve.txWarning": "Aprueba esto solo si confías en el sitio y entiendes lo que te está pidiendo firmar.",
    "approve.confirmBtn": "Confirmar",
    "approve.signTitle": "Solicitud de firma",
    "approve.signBtn": "Firmar",
    "approve.addNetTitle": "Solicitud para agregar red",
    "approve.addNetNameLabel": "Nombre:",
    "approve.addNetChainIdLabel": "ID de cadena:",
    "approve.addNetRpcLabel": "RPC:",
    "approve.addNetWarning": "La red sugerida por este sitio no tiene un router de intercambio verificado. El intercambio seguirá deshabilitado en ella hasta que agregues uno tú mismo en Configuración.",
    "approve.addNetBtn": "Agregar red",
    "approve.contractCreation": "(creación de contrato)",
    "approve.nativeSuffix": " (nativo)",
    "approve.decodedLoading": "Leyendo qué hace esto realmente...",
    "approve.decodedTransferLine": "Esto transferirá {amount} a {to}.",
    "approve.decodedApproveLine": "Esto aprobará {amount} para que {to} lo gaste.",
    "approve.decodedUnlimited": "ILIMITADO {symbol}",
    "approve.decodedThisToken": "este token",
    "approve.decodedRawUnitsSuffix": " unidades sin procesar (no se pudieron confirmar los decimales de este token)",
    "approve.decodedGenericIntro": "Esto llama a \"{fn}\" en el contrato de arriba con:",

    "loading.text": "Cargando...",

    "home.tabHome": "Inicio",
    "home.tabAssets": "Activos",
    "home.tabActivity": "Actividad",
    "home.tabSend": "Enviar",
    "home.tapToContinue": "Toca para continuar",
    "home.continueBtn": "Continuar",

    "activity.title": "Actividad",
    "activity.subtitle": "Un registro local de los envíos hechos desde esta wallet, más las transferencias entrantes que este dispositivo ha detectado -- nada aquí se obtiene de un servidor.",
    "activity.empty": "Aún no hay actividad -- los envíos que hagas (y las transferencias entrantes que este dispositivo detecte) aparecerán aquí.",
    "activity.sentLabel": "Enviado {amount} {asset}",
    "activity.receivedLabel": "Recibido {amount} {asset}",
    "activity.toLabel": "a {address}",
    "activity.statusSent": "Enviado",
    "activity.statusReceived": "Recibido",
    "activity.receivedApproxNote": "Detectado por un cambio de saldo -- aproximado, sin enlace a la transacción",
    "activity.viewOnExplorer": "Ver en el explorador de bloques",

    "footer.nonCustodial": "No custodial — tus claves nunca salen de este dispositivo",

    "errors.passwordTooShort": "La contraseña debe tener al menos 8 caracteres.",
    "errors.passwordMismatch": "Las contraseñas no coinciden.",
    "errors.unknownError": "Error desconocido",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "¿Cómo creo una billetera?",
      keywords: ["crear billetera", "crear una billetera", "billetera nueva", "configurar billetera", "cómo empezar", "primera vez", "nueva billetera"],
      answer: "Toca “Crear una billetera nueva” en la pantalla de bienvenida, elige una contraseña (esta solo desbloquea la billetera en este dispositivo -- no puede recuperar tus fondos) y se te mostrará una frase de recuperación de 12 palabras. Anótala en un lugar seguro antes de continuar -- esa frase es la única forma de recuperar tus fondos si alguna vez pierdes este dispositivo.",
    },
    {
      id: "import-wallet",
      chip: "¿Cómo importo una billetera existente?",
      keywords: ["importar billetera", "importar una existente", "restaurar billetera", "billetera existente", "importar frase de recuperación", "importar semilla"],
      answer: "En la pantalla de bienvenida toca “Importar una billetera existente,” ingresa tu frase de recuperación de 12 o 24 palabras exactamente como está escrita (en minúsculas, separada por espacios) y luego establece una nueva contraseña para este dispositivo. La frase en sí nunca sale de tu dispositivo -- se usa localmente para derivar tus cuentas.",
    },
    {
      id: "forgot-password",
      chip: "Olvidé mi contraseña",
      keywords: ["olvidé mi contraseña", "olvide mi contraseña", "contraseña incorrecta", "no puedo desbloquear", "bloqueado", "la contraseña no funciona"],
      answer: "Tu contraseña solo desbloquea la billetera en este dispositivo -- Token Exchange nunca la almacena en ningún lugar ni puede restablecerla por ti. Si no la recuerdas, toca “Restablecer billetera en su lugar” en la pantalla de desbloqueo y luego vuelve a importar tu billetera usando tu frase de recuperación de 12 palabras. Si no tienes esa frase guardada, lamentablemente los fondos de esta billetera no se pueden recuperar -- ese es el precio de una billetera no custodial: nadie más que tú puede desbloquearla jamás, lo cual también significa que nadie más que tú puede rescatarla.",
    },
    {
      id: "lost-seed-phrase",
      chip: "Perdí mi frase de recuperación",
      keywords: ["perdí mi frase", "perdi mi frase", "perdí la semilla", "perdí mi frase de recuperación", "no tengo mi frase", "olvidé mi frase", "nunca la anoté", "no la guardé"],
      answer: "Si todavía tienes la sesión iniciada, ve a Configuración → “Ver frase de recuperación,” vuelve a ingresar tu contraseña y anótala ahora en un lugar seguro. Si estás bloqueado Y nunca guardaste la frase, no hay forma de recuperar la billetera ni los fondos que contiene. Token Exchange nunca almacena tu frase en ningún lugar -- ni en un servidor, ni en la nube, en ninguna parte -- así que nadie, ni siquiera el desarrollador, puede recuperarla por ti.",
    },
    {
      id: "balance-not-showing",
      chip: "Mi saldo no aparece",
      keywords: ["saldo", "saldo en cero", "0.00", "no aparece", "saldo incorrecto", "saldo atascado", "sigue cargando", "el saldo es 0"],
      answer: "Un saldo que se queda en “...” normalmente significa que el endpoint RPC de esa red está lento o momentáneamente caído -- esta billetera reintenta automáticamente con un endpoint de respaldo después de unos segundos, así que suele resolverse solo. Si se queda en 0 y eso te parece incorrecto, verifica que estés en la red y la cuenta correctas (ambos menús desplegables están en la pantalla principal) -- los saldos se rastrean por separado según la red y la cuenta, así que, por ejemplo, los fondos en Base no aparecerán mientras esté seleccionada Ethereum Mainnet.",
    },
    {
      id: "swap-failed",
      chip: "Mi intercambio falló",
      keywords: ["intercambio falló", "swap falló", "intercambio atascado", "el intercambio no funciona", "error de intercambio", "la cotización falló"],
      answer: "Los intercambios ocurren on-chain a través de un router público de exchange descentralizado, así que una falla suele deberse a una de tres cosas: saldo insuficiente para cubrir el monto más la comisión de gas de la red, una tolerancia de deslizamiento demasiado ajustada para un precio que se mueve rápido (prueba con 1% o 3% en lugar de 0.5%), o que ese par de tokens aún no tenga suficiente liquidez en el router de esa red. El error que se muestra en la pantalla de Intercambio después de “Obtener cotización” normalmente indica cuál es -- si no queda claro, intenta de nuevo con un monto más pequeño primero.",
    },
    {
      id: "swap-fee",
      chip: "¿Cuánto cuesta un intercambio?",
      keywords: ["comisión de intercambio", "cuánto cuesta", "0.5%", "cobro por intercambio", "comisión del swap", "cuál es la comisión"],
      answer: "Los intercambios tienen una comisión fija del 0.5% sobre el monto que estás intercambiando, mostrada claramente en la cotización antes de confirmar -- forma parte de la propia transacción de intercambio, nunca un margen oculto dentro del tipo de cambio. Esto es independiente de la comisión de gas de la red, que va a la blockchain, no a Token Exchange.",
    },
    {
      id: "gas-fees",
      chip: "¿Qué es una comisión de gas?",
      keywords: ["comisión de gas", "comisión de red", "comisión de transacción", "qué es el gas", "costo de gas"],
      answer: "El gas es la comisión que cobra la propia red blockchain por procesar una transacción -- es independiente de la comisión de intercambio del 0.5% de Token Exchange y va enteramente a la red, no a nosotros. El monto varía según la congestión de la red en ese momento. Asegúrate de tener suficiente de la moneda nativa de esa red (ETH, BNB, POL, etc.) para cubrir el gas, incluso cuando estés enviando un token en lugar de la moneda nativa.",
    },
    {
      id: "add-network",
      chip: "¿Cómo agrego una red?",
      keywords: ["agregar red", "agregar una red", "red nueva", "red personalizada", "otra cadena", "cadena diferente"],
      answer: "Ve a Configuración → “Agregar red” y completa el nombre de la red, el ID de cadena, la URL de RPC y el símbolo de la moneda nativa. Si además agregas ahí una dirección de router de intercambio verificado, el intercambio también funcionará en esa red -- de lo contrario, solo permitirá enviar y recibir. Usa únicamente valores que hayas verificado personalmente contra la documentación oficial de esa red o su explorador de bloques.",
    },
    {
      id: "add-token",
      chip: "¿Cómo hago seguimiento de un token?",
      keywords: ["agregar token", "seguir token", "token nuevo", "token personalizado", "erc-20", "erc20", "rastrear un token"],
      answer: "En la pantalla principal toca “+ Agregar token,” pega la dirección de contrato del token para tu red actual y toca “Buscar” -- esto lee el nombre, símbolo y decimales del token directamente del contrato para que puedas confirmarlos antes de agregarlo. Agrega solo un token cuya dirección de contrato provenga de una fuente de confianza; una billetera no puede distinguir un token real de uno falso que use el mismo nombre y símbolo.",
    },
    {
      id: "send-crypto",
      chip: "¿Cómo envío criptomonedas?",
      keywords: ["cómo envío", "enviar cripto", "enviar tokens", "transferir cripto", "enviar eth", "enviar fondos"],
      answer: "Toca “Enviar” en la pantalla principal, elige la moneda nativa o un token (por su dirección de contrato), ingresa la dirección del destinatario y un monto, y confirma. Verifica bien la dirección antes de confirmar -- los envíos en estas redes son irreversibles una vez que se completan.",
    },
    {
      id: "connect-dapp",
      chip: "¿Cómo me conecto a un sitio web?",
      keywords: ["conectar dapp", "conectar a un sitio", "botón conectar billetera", "conectar a un sitio web", "no se conecta"],
      answer: "Cualquier sitio con un botón “Connect Wallet” que admita extensiones de billetera de navegador debería ofrecer Token Exchange de la misma forma que ofrecería MetaMask o Coinbase Wallet. Si un sitio no lo muestra como opción, intenta actualizar la página después de que la billetera esté instalada y desbloqueada -- algunos sitios solo detectan las extensiones de billetera al cargar la página.",
    },
    {
      id: "buy-not-working",
      chip: "La función Comprar no funciona",
      keywords: ["botón comprar", "comprar no funciona", "comprar no configurado", "moonpay", "no puedo comprar"],
      answer: "El botón Comprar abre MoonPay, un servicio externo de rampa de entrada independiente, en una pestaña nueva. Si dice “Buy isn't configured yet,” significa que el desarrollador de esta billetera aún no ha agregado una clave de API de MoonPay -- no es algo que puedas solucionar desde la billetera misma. Una vez configurado, tú mismo pegarás tu dirección de recepción en la página de MoonPay; Token Exchange nunca la envía en tu nombre.",
    },
    {
      id: "reset-wallet",
      chip: "¿Cómo restablezco mi billetera?",
      keywords: ["restablecer billetera", "eliminar billetera", "empezar de nuevo", "borrar billetera", "reiniciar billetera"],
      answer: "Configuración → “Restablecer billetera” elimina permanentemente la billetera cifrada de este navegador. Asegúrate por completo de tener respaldada tu frase de recuperación antes de hacerlo -- esto no se puede deshacer, y no hay forma de recuperar la billetera después sin esa frase.",
    },
    {
      id: "is-it-safe",
      chip: "¿Es segura esta billetera?",
      keywords: ["es segura", "es seguro", "confiar en esto", "no custodial", "custodial", "es esto un fraude", "es legítima"],
      answer: "Token Exchange es no custodial: tu frase de recuperación y tus claves privadas están cifradas y se almacenan solo en tu navegador -- nunca se envían a ningún servidor, porque no existe ninguno. Esto también significa que nadie, ni siquiera el desarrollador, puede recuperar tus fondos si pierdes tanto tu contraseña como tu frase de recuperación. Los envíos e intercambios también se verifican contra una lista de sanciones incluida antes de salir, todo en el propio dispositivo, y las comisiones de intercambio siempre se muestran por adelantado antes de confirmar.",
    },
    {
      id: "pending-transaction",
      chip: "Mi transacción está atascada",
      keywords: ["pendiente", "transacción atascada", "la transacción no confirma", "sigue pendiente", "transacción estancada"],
      answer: "Una transacción puede quedar en estado “pendiente” si la red está congestionada o si el precio de gas usado fue demasiado bajo para las condiciones actuales. Debería confirmarse eventualmente por sí sola. Si lleva mucho tiempo atascada, puedes buscar la transacción en el explorador de bloques de esa red usando la dirección de tu cuenta para ver su estado en tiempo real.",
    },
    {
      id: "wrong-network",
      chip: "¿Qué redes son compatibles?",
      keywords: ["qué red", "red incorrecta", "cambiar de red", "redes compatibles", "qué cadenas", "cadenas compatibles", "qué redes"],
      answer: "Incluidas de forma nativa: Ethereum, Base, Polygon, BNB Chain, Arbitrum One y OP Mainnet, seleccionables desde el menú desplegable cerca de la parte inferior de la pantalla principal -- tu saldo, tokens y opciones de intercambio son específicos de la red que esté seleccionada ahí. Puedes agregar cualquier otra red compatible con EVM tú mismo desde Configuración → “Agregar red.”",
    },
    {
      id: "contact-human",
      chip: "Necesito más ayuda",
      keywords: ["hablar con una persona", "persona real", "contactar soporte", "contactarlos", "sigo necesitando ayuda", "necesito más ayuda", "hablar con alguien"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "¡Hola! Soy un bot de ayuda simple e integrado -- solo puedo responder preguntas de una lista fija escrita de antemano, nada más. Toca un tema abajo o escribe tu propia pregunta.";
  const fallbackWithEmail = "Todavía no tengo una respuesta redactada para eso. Puedes contactar a una persona en {email} -- ayuda mencionar en qué pantalla estabas y qué esperabas que sucediera.";
  const fallbackNoEmail = "Todavía no tengo una respuesta redactada para eso, y esta billetera tampoco tiene configurada una línea de soporte humano en vivo. Intenta reformular tu pregunta o consulta el README de la extensión para más detalles sobre cómo funciona cada función.";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.es = {
    name: "Español",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
