// lib/i18n/fr.js
// French localization. Must define the exact same `strings` keys and the
// exact same FAQ `id`s as lib/i18n/en.js (the canonical source) --
// lib/i18n.js falls back to en.js for anything missing here, and
// test-i18n.js checks the key sets match.
(function () {
  const strings = {
    "common.needHelp": "Besoin d'aide ?",
    "common.languageLabel": "Langue",
    "common.back": "Retour",
    "common.cancel": "Annuler",
    "common.copy": "Copier",
    "common.send": "Envoyer",
    "common.swap": "Échanger",
    "common.buy": "Acheter",
    "common.livePrices": "Cours en direct",
    "common.reject": "Refuser",
    "common.passwordPlaceholder": "Mot de passe",
    "common.confirmPasswordPlaceholder": "Confirmer le mot de passe",
    "common.newPasswordLabel": "Nouveau mot de passe (8 caractères minimum)",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "Adresse du token (0x...)",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "Monnaie native",

    "onboarding.title": "Bienvenue",
    "onboarding.subtitle": "Configurez votre portefeuille pour commencer.",
    "onboarding.createBtn": "Créer un nouveau portefeuille",
    "onboarding.importBtn": "Importer un portefeuille existant",

    "create.title": "Créer un portefeuille",
    "create.passwordLabel": "Nouveau mot de passe (8 caractères minimum)",
    "create.passwordWarning": "Ce mot de passe déverrouille votre portefeuille sur cet appareil. Il ne peut pas être récupéré -- seule votre phrase de récupération peut restaurer vos fonds.",
    "create.continueBtn": "Continuer",
    "create.backupWarning": "Notez cette phrase de récupération et conservez-la en lieu sûr. Toute personne qui la possède peut s'emparer de tout ce qui se trouve dans ce portefeuille. Token Exchange ne peut pas la récupérer pour vous.",
    "create.backupCheckbox": "J'ai sauvegardé ma phrase de récupération",
    "create.finishBtn": "Terminer",

    "import.title": "Importer un portefeuille",
    "import.mnemonicLabel": "Phrase de récupération (12 ou 24 mots)",
    "import.mnemonicPlaceholder": "mot1 mot2 mot3 ...",
    "import.submitBtn": "Importer",

    "unlock.title": "Déverrouiller",
    "unlock.submitBtn": "Déverrouiller",
    "unlock.resetInsteadBtn": "Réinitialiser le portefeuille à la place",

    "main.settingsTitle": "Paramètres",
    "main.portfolioLabel": "Solde total",
    "main.addAccountOption": "+ Ajouter un compte",
    "main.tokensTitle": "Tokens",
    "main.addTokenBtn": "+ Ajouter un token",
    "main.tokensEmpty": "Aucun token ajouté pour l'instant -- appuyez sur « + Ajouter un token » et saisissez une adresse de contrat pour en suivre un.",
    "main.networkLabel": "Réseau",
    "main.balanceFetchErrorPrefix": "Impossible de récupérer le solde : ",
    "main.watchOnlySuffix": "(Observation)",
    "main.watchOnlyNotice": "Vous consultez une adresse en lecture seule -- il n'y a pas de clé privée pour elle dans ce portefeuille, donc Envoyer et Échanger sont désactivés ici.",

    "tokens.loadError": "Impossible de charger le solde",
    "tokens.removeTitle": "Supprimer",

    "addToken.title": "Ajouter un token",
    "addToken.description": "Saisissez l'adresse du contrat du token sur le réseau actuel. N'ajoutez un token que si vous avez obtenu son adresse de contrat d'une source de confiance -- un portefeuille ne peut pas distinguer un vrai token d'un faux portant le même nom.",
    "addToken.addressLabel": "Adresse du contrat du token",
    "addToken.lookupBtn": "Rechercher",
    "addToken.nameLabel": "Nom :",
    "addToken.symbolLabel": "Symbole :",
    "addToken.decimalsLabel": "Décimales :",
    "addToken.confirmBtn": "Ajouter à mon portefeuille",
    "addToken.invalidAddress": "Saisissez une adresse de contrat valide.",
    "addToken.noName": "(sans nom)",
    "addToken.swapUnavailableSuffix": " (échange indisponible)",

    "prices.description": "Cours en USD fournis par l'API publique de CoinGecko. À titre purement informatif -- aucune information sur votre portefeuille n'est envoyée pour obtenir ces données.",
    "prices.loading": "Chargement...",
    "prices.naText": "n/d",
    "prices.tabCrypto": "Crypto",
    "prices.tabCurrencies": "Devises",
    "prices.searchPlaceholder": "Rechercher...",
    "prices.currenciesNote": "Ce que vaut 1 unité de chaque devise dans votre devise d'affichage.",
    "prices.noResults": "Aucun résultat.",
    "prices.viewCoin": "Voir {name}",
    "coin.swapBtn": "Échanger contre {symbol}",
    "coin.swapHint": "Vous choisirez avec quel actif payer à l'écran suivant.",
    "coin.swapNeedsWallet": "Déverrouillez votre portefeuille pour échanger.",
    "coin.swapNoRouter": "L'échange n'est pas encore activé sur ce réseau.",
    "coin.swapUnavailableNetwork": "{symbol} ne peut pas encore être échangé sur {network}. Il doit s'agir de la monnaie native du réseau ou d'un jeton ajouté via Ajouter un jeton.",
    "coin.holding": "Vous détenez {amount} {symbol}",
    "coin.statsTitle": "Données de marché",
    "coin.aboutTitle": "À propos",
    "coin.aboutUnavailable": "Aucune description disponible pour le moment.",
    "coin.marketCap": "Capitalisation",
    "coin.volume24h": "Volume 24 h",
    "coin.high24h": "Plus haut 24 h",
    "coin.low24h": "Plus bas 24 h",
    "coin.supply": "Offre en circulation",
    "coin.ath": "Plus haut historique",
    "coin.viewCoingecko": "Voir sur CoinGecko",
    "coin.loadError": "Impossible de charger plus de détails sur cette crypto pour le moment.",
    "coin.chartUnavailable": "Graphique indisponible pour le moment.",
    "swap.customAddressOption": "Autre jeton (coller l'adresse)...",

    "buy.title": "Acheter des cryptos",
    "buy.description1": "L'achat est propulsé par Transak, un service tiers indépendant -- Token Exchange n'a jamais accès à vos informations de paiement.",
    "buy.noThirdPartyCallout": "Vous avez déjà des cryptos ? Passez complètement Transak : échangez-les directement on-chain contre ce dont vous avez besoin, sans tiers ni inscription.",
    "buy.noThirdPartySwapBtn": "Échanger à la place",
    "buy.continueBtn": "Continuer vers Transak",
    "buy.pickerTitle": "Choisissez quoi acheter",
    "buy.pickerSearchPlaceholder": "Rechercher une crypto par nom ou symbole",
    "buy.pickerCurrencies": "Devises",
    "buy.pickerCrypto": "Crypto",
    "buy.changeCoinBtn": "Changer de crypto",

    "support.title": "Aide et assistance",
    "support.description": "Posez une question ou appuyez sur un sujet ci-dessous. Cela fonctionne entièrement sur votre appareil -- rien de ce que vous saisissez ici n'est envoyé où que ce soit.",
    "support.inputPlaceholder": "Saisissez une question...",

    "send.title": "Envoyer",
    "send.assetLabel": "Actif",
    "send.assetToken": "Token (saisir l'adresse du contrat)",
    "send.tokenAddressPlaceholder": "Adresse du contrat du token (0x...)",
    "send.toLabel": "Adresse de destination",
    "send.amountLabel": "Montant",
    "send.speedSlow": "Lente",
    "send.speedStandard": "Standard",
    "send.speedFast": "Rapide",
    "send.invalidRecipient": "Saisissez une adresse de destinataire valide.",
    "send.invalidTokenAddress": "Saisissez une adresse de contrat de token valide.",
    "send.sentStatus": "Envoyé ! Hash de transaction : {txHash}",
    "send.poisonWarning": "Cette adresse ressemble beaucoup à une que vous avez déjà utilisée ({match}) mais ce n'est pas la même -- elle commence et se termine de la même façon alors que le milieu est différent. Il s'agit d'un schéma d'arnaque courant (« empoisonnement d'adresse ») où une adresse similaire est glissée dans votre historique en espérant que vous copiiez la mauvaise. Vérifiez chaque caractère avant d'envoyer.",

    "swap.unsupportedWarning": "L'échange n'est pas encore activé sur ce réseau -- aucun routeur vérifié n'est configuré. Ajoutez-en un dans Paramètres → Réseaux d'abord.",
    "swap.fromLabel": "De",
    "swap.toLabel": "Vers",
    "swap.getQuoteBtn": "Obtenir un devis",
    "swap.appFeeLine": "Frais de l'application ({percent}) : {amount}",
    "swap.netAmountLine": "Montant net échangé : {amount}",
    "swap.estimatedOutLine": "Montant estimé reçu : {amount}",
    "swap.slippageLabel": "Tolérance de glissement",
    "swap.approveBtn": "Approuver le token d'abord",
    "swap.approvingStatus": "Approbation en cours...",
    "swap.approvedStatus": "Approuvé. Vous pouvez maintenant échanger.",
    "swap.sendingStatus": "Envoi des frais et échange en cours...",
    "swap.swappedStatus": "Échangé ! Tx des frais : {feeTx} | Tx de l'échange : {tx}",
    "swap.feeTxNa": "n/d",

    "settings.title": "Paramètres",
    "settings.addAccountBtn": "Ajouter un compte",
    "settings.importKeyBtn": "Importer une clé privée",
    "settings.addWatchBtn": "Ajouter une adresse en lecture seule",
    "settings.approvalsBtn": "Gérer les autorisations",
    "settings.addNetworkBtn": "Ajouter un réseau",
    "settings.viewSeedBtn": "Afficher la phrase de récupération",
    "settings.helpBtn": "Aide et assistance",
    "settings.lockBtn": "Verrouiller le portefeuille",
    "settings.resetBtn": "Réinitialiser le portefeuille",

    "importKey.title": "Importer une clé privée",
    "importKey.description": "Cela ajoute un compte distinct à ce portefeuille à partir d'une clé privée brute, et non de votre phrase de récupération -- sauvegardez-la séparément, car votre phrase de récupération ne permettra pas de la restaurer. Ne partagez jamais une clé privée avec qui que ce soit ; quiconque la possède peut dépenser tout ce qui se trouve sur ce compte.",
    "importKey.placeholder": "Clé privée 0x",

    "addWatch.title": "Ajouter une adresse en lecture seule",
    "addWatch.description": "Suit le solde, les tokens et l'activité d'une adresse sans en détenir la clé -- il n'y a rien ici avec quoi signer, donc Envoyer et Échanger restent désactivés pour elle. Utile pour surveiller depuis ici une adresse de stockage à froid ou de portefeuille matériel.",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "Étiquette (facultatif)",
    "addWatch.submitBtn": "Ajouter",

    "approvals.title": "Gérer les autorisations",
    "approvals.description": "Affiche les autorisations de dépense de tokens pour le routeur d'échange propre à ce portefeuille, ainsi qu'une recherche manuelle pour tout autre token et dépensier. Révoquer ramène l'autorisation à zéro -- le dépensier ne pourra plus déplacer ce token en votre nom tant que vous ne l'aurez pas approuvé à nouveau.",
    "approvals.emptyText": "Aucune autorisation trouvée pour les tokens que vous avez ajoutés.",
    "approvals.loading": "Vérification des autorisations...",
    "approvals.manualHeading": "Vérifier une autorisation spécifique",
    "approvals.tokenPlaceholder": "Adresse du contrat du token (0x...)",
    "approvals.spenderPlaceholder": "Adresse du contrat du dépensier (0x...)",
    "approvals.checkBtn": "Vérifier",
    "approvals.tokenLabel": "Token :",
    "approvals.spenderLabel": "Dépensier :",
    "approvals.allowanceLabel": "Autorisation :",
    "approvals.revokeBtn": "Révoquer",
    "approvals.revokingBtn": "Révocation...",
    "approvals.rowError": "Impossible de vérifier celle-ci -- réessayez dans un instant.",

    "addNetwork.title": "Ajouter un réseau",
    "addNetwork.namePlaceholder": "Nom du réseau",
    "addNetwork.chainIdPlaceholder": "ID de chaîne (nombre)",
    "addNetwork.rpcPlaceholder": "URL RPC",
    "addNetwork.symbolPlaceholder": "Symbole de la monnaie native",
    "addNetwork.explorerPlaceholder": "URL de l'explorateur de blocs (facultatif)",
    "addNetwork.routerPlaceholder": "Adresse du routeur d'échange vérifié (facultatif)",
    "addNetwork.routerWarning": "Ne renseignez l'adresse du routeur que si vous l'avez personnellement vérifiée par rapport à la documentation officielle du projet ou à l'explorateur de blocs de la chaîne. Laissez vide en cas de doute -- l'échange sera simplement désactivé sur ce réseau jusqu'à ce que vous en ajoutiez un.",
    "addNetwork.addBtn": "Ajouter",

    "viewSeed.title": "Phrase de récupération",
    "viewSeed.passwordPlaceholder": "Saisissez le mot de passe pour l'afficher",
    "viewSeed.revealBtn": "Afficher",

    "reset.title": "Réinitialiser le portefeuille",
    "reset.warning": "Cette action supprime le portefeuille chiffré de ce navigateur. Assurez-vous d'avoir sauvegardé votre phrase de récupération -- cette action est irréversible.",
    "reset.confirmBtn": "Oui, tout supprimer",

    "approve.unlockTitle": "Déverrouiller pour continuer",
    "approve.unlockOriginText": "{origin} demande l'accès.",
    "approve.connectTitle": "Demande de connexion",
    "approve.connectWantsText": "{origin} souhaite se connecter à votre portefeuille.",
    "approve.accountLabel": "Compte : ",
    "approve.acceptConnectBtn": "Connecter",
    "approve.txTitle": "Demande de transaction",
    "approve.toLabel": "À :",
    "approve.valueLabel": "Valeur :",
    "approve.dataLabel": "Données :",
    "approve.txWarning": "N'approuvez cette demande que si vous faites confiance au site et que vous comprenez ce qu'il vous demande de signer.",
    "approve.confirmBtn": "Confirmer",
    "approve.signTitle": "Demande de signature",
    "approve.signBtn": "Signer",
    "approve.addNetTitle": "Demande d'ajout de réseau",
    "approve.addNetNameLabel": "Nom :",
    "approve.addNetChainIdLabel": "ID de chaîne :",
    "approve.addNetRpcLabel": "RPC :",
    "approve.addNetWarning": "Le réseau suggéré par ce site n'a pas de routeur d'échange vérifié. L'échange y restera désactivé jusqu'à ce que vous en ajoutiez un vous-même dans les Paramètres.",
    "approve.addNetBtn": "Ajouter le réseau",
    "approve.switchNetTitle": "Demande de changement de réseau",
    "approve.switchNetText": "{origin} souhaite faire passer votre portefeuille de {from} à {to}.",
    "approve.switchNetWarning": "Ne changez que si vous vous y attendiez. Les transactions que vous approuverez ensuite seront envoyées sur le nouveau réseau.",
    "approve.switchNetBtn": "Changer de réseau",
    "approve.contractCreation": "(création de contrat)",
    "approve.nativeSuffix": " (natif)",
    "approve.decodedLoading": "Analyse de ce que cela fait réellement...",
    "approve.decodedTransferLine": "Ceci transférera {amount} à {to}.",
    "approve.decodedApproveLine": "Ceci autorisera {to} à dépenser {amount}.",
    "approve.decodedUnlimited": "ILLIMITÉ {symbol}",
    "approve.decodedThisToken": "ce token",
    "approve.decodedRawUnitsSuffix": " unités brutes (impossible de confirmer les décimales de ce token)",
    "approve.decodedGenericIntro": "Ceci appelle « {fn} » sur le contrat ci-dessus avec :",

    "loading.text": "Chargement...",

    "home.tabHome": "Accueil",
    "home.tabAssets": "Actifs",
    "home.tabActivity": "Activité",
    "home.tabSend": "Envoyer",
    "home.tapToContinue": "Appuyez pour continuer",
    "home.continueBtn": "Continuer",

    "activity.title": "Activité",
    "activity.subtitle": "Un historique local des envois effectués depuis ce portefeuille, ainsi que des transferts entrants remarqués par cet appareil -- rien ici n'est récupéré depuis un serveur.",
    "activity.empty": "Aucune activité pour l'instant -- les envois que vous effectuez (et les transferts entrants remarqués par cet appareil) apparaîtront ici.",
    "activity.sentLabel": "Envoyé {amount} {asset}",
    "activity.receivedLabel": "Reçu {amount} {asset}",
    "activity.toLabel": "à {address}",
    "activity.statusSent": "Envoyé",
    "activity.tabSends": "Envois",
    "activity.tabSwaps": "Échanges",
    "activity.swapsSubtitle": "Un registre local des échanges effectués avec ce portefeuille sur cet appareil -- rien ici n'est récupéré depuis un serveur.",
    "activity.swapsEmpty": "Aucun échange pour l'instant -- ceux que vous ferez avec ce portefeuille apparaîtront ici.",
    "activity.swapLabel": "Échange de {amountIn} {assetIn} contre environ {amountOut} {assetOut}",
    "activity.statusSwapped": "Échangé",
    "activity.statusReceived": "Reçu",
    "activity.receivedApproxNote": "Détecté à partir d'une variation de solde -- approximatif, aucun lien de transaction disponible",
    "activity.viewOnExplorer": "Voir sur l'explorateur de blocs",

    "footer.nonCustodial": "Non dépositaire — vos clés ne quittent jamais cet appareil",

    "errors.passwordTooShort": "Le mot de passe doit contenir au moins 8 caractères.",
    "errors.passwordMismatch": "Les mots de passe ne correspondent pas.",
    "errors.unknownError": "Erreur inconnue",

    "common.sell": "Vendre",
    "common.seeAll": "Tout voir",
    "main.showQrBtn": "Afficher le QR",
    "main.hideQrBtn": "Masquer le QR",
    "main.nftsTitle": "NFT",
    "main.addNftBtn": "+ Ajouter un NFT",
    "main.nftsEmpty": "Aucun NFT ajouté pour l'instant -- touchez « + Ajouter un NFT » et saisissez une adresse de contrat et un ID de token pour en suivre un.",
    "main.livePricesTitle": "Cours en direct",
    "main.predictionsTitle": "Cryptos tendance",
    "main.currenciesCardTitle": "Devises",
    "main.exchangesCardTitle": "Plateformes d'échange les plus populaires",
    "addToken.quickAddLabel": "Ajout rapide :",
    "addToken.quickAddChip": "+ {symbol}",
    "nfts.loadError": "Chargement impossible",
    "nfts.removeTitle": "Retirer",
    "addNft.title": "Ajouter un NFT",
    "addNft.description": "Fonctionne avec ERC-721 et ERC-1155. N'ajoutez que depuis une source de confiance.",
    "addNft.addressLabel": "Adresse du contrat",
    "addNft.tokenIdLabel": "ID du token",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "Standard :",
    "addNft.invalidAddress": "Saisissez une adresse de contrat valide.",
    "addNft.invalidTokenId": "Saisissez un ID de token valide (un nombre entier non négatif).",
    "addNft.metaWarning": "Impossible de charger l'image ou le nom, mais vous pouvez quand même l'ajouter.",
    "addNft.noName": "(sans nom)",
    "prices.watchlistToggle": "Étoile pour épingler en haut",
    "prices.cardUnavailable": "Cours indisponibles pour le moment.",
    "prices.viewPeggedCoin": "Voir {name}, le stablecoin indexé sur {currency}",
    "prices.availableOn": "✓ Sur {networks}",
    "coin.swapUnavailableSwitchNetwork": "{symbol} est la monnaie native de {network}. Changez de réseau pour l'échanger ou la conserver là-bas.",
    "coin.swapUnavailableSwitchNetworkTracked": "Vous avez déjà ajouté {symbol} sur {network}. Passez sur ce réseau pour l'utiliser.",
    "coin.swapUnavailableKnownElsewhere": "{symbol} est un token vérifié sur {network}. Passez sur ce réseau pour l'ajouter automatiquement.",
    "coin.switchNetworkBtn": "Passer à {network}",
    "coin.addOnNetworkBtn": "Ajouter sur {network}",
    "coin.buyBtn": "Acheter {symbol}",
    "predictions.title": "Cryptos tendance",
    "predictions.description": "Cryptos en tendance sur CoinGecko en ce moment -- à titre informatif uniquement. Aucune donnée de votre portefeuille n'est envoyée pour consulter ces informations.",
    "predictions.loading": "Chargement...",
    "predictions.empty": "Aucune crypto tendance pour le moment.",
    "predictions.cardUnavailable": "Cryptos tendance indisponibles pour le moment.",
    "predictions.volSuffix": "vol. 24 h",
    "exchanges.title": "Plateformes d'échange les plus populaires",
    "exchanges.description": "Classement des plateformes d'échange centralisées de cryptomonnaies selon le score de confiance de CoinGecko, actualisé automatiquement -- à titre informatif uniquement. Token Exchange est en auto-conservation et n'achemine jamais d'opérations via l'une d'elles ; aucune donnée de votre portefeuille n'est envoyée pour consulter ces informations.",
    "exchanges.loading": "Chargement...",
    "exchanges.empty": "Aucune donnée de plateforme disponible pour le moment.",
    "exchanges.cardUnavailable": "Plateformes indisponibles pour le moment.",
    "exchanges.foundedYear": "Fondée en {year}",
    "buy.description2": "L'achat via Transak s'ouvre directement dans l'application, avec votre adresse de réception déjà renseignée et verrouillée -- rien à coller, et les cryptos achetées ne peuvent être envoyées que vers votre propre portefeuille.",
    "buy.presetNote": "Préréglé pour acheter {symbol} -- vous pouvez toujours choisir un autre actif à l'ouverture de Transak.",
    "buy.closeWidgetBtn": "← Fermer",
    "sell.title": "Vendre contre de l'argent",
    "sell.description1": "La vente est assurée par Transak, le même service tiers que celui utilisé pour l'achat -- Token Exchange n'accède jamais à vos coordonnées de paiement.",
    "sell.description2": "La vente via Transak s'ouvre directement dans l'application et vous propose un paiement en espèces. Une adresse de dépôt vous sera indiquée pour y envoyer vos cryptos -- une fois reçues, Transak les convertit et verse le montant sur votre compte bancaire ou votre carte associé(e).",
    "sell.continueBtn": "Continuer vers Transak",
    "sell.closeWidgetBtn": "← Fermer",
    "send.contactsBtn": "Contacts",
    "contacts.title": "Carnet d'adresses",
    "contacts.pickerHint": "Touchez un contact pour le renseigner comme destinataire.",
    "contacts.namePlaceholder": "Nom",
    "contacts.addBtn": "Enregistrer le contact",
    "contacts.empty": "Aucun contact enregistré pour l'instant.",
    "contacts.removeBtn": "Retirer",
    "contacts.nameRequired": "Donnez un nom à ce contact.",
    "contacts.invalidAddress": "Saisissez une adresse 0x valide.",
    "send.confirmIntro": "Envoi dans {seconds} s -- vous pouvez encore annuler.",
    "send.confirmSummary": "{amount} {asset} vers {to}",
    "send.newAddressWarning": "Vous n'avez jamais envoyé à cette adresse depuis cet appareil -- vérifiez bien qu'elle est correcte.",
    "send.cancelBtn": "Annuler l'envoi",
    "send.cancelledStatus": "Envoi annulé -- rien n'a été envoyé.",
    "send.feeEstimateLoading": "Estimation des frais de réseau...",
    "send.feeEstimate": "Frais de réseau estimés : ~{fee} {symbol} (~{usd})",
    "send.feeEstimateNoUsd": "Frais de réseau estimés : ~{fee} {symbol}",
    "fee.burned": "Dont ~{burn} {symbol} sont brûlés (retirés définitivement de l'offre)",
    "send.scanBtn": "Scanner un code QR",
    "send.scanTitle": "Scanner un code QR de portefeuille",
    "send.scanClose": "Fermer",
    "send.scanHint": "Pointez la caméra vers un code QR d'adresse de portefeuille.",
    "send.scanUnsupported": "La lecture de codes QR n'est pas prise en charge par ce navigateur. Collez plutôt l'adresse.",
    "send.scanDenied": "L'accès à la caméra a été bloqué. Autorisez la caméra pour ce site ou collez l'adresse.",
    "send.scanNoAddress": "Ce code QR ne contient pas d'adresse de portefeuille valide.",
    "send.scanFilled": "Adresse renseignée. Vérifiez-la avant d'envoyer.",
    "activity.exportCsv": "Exporter en CSV",
    "activity.exportEmpty": "Rien à exporter pour l'instant.",
    "settings.themeLabel": "Apparence",
    "settings.themeDark": "Sombre (par défaut)",
    "settings.themeLight": "Clair",
    "settings.notifyLabel": "Notifications",
    "settings.notifyOff": "Désactivées",
    "settings.notifyOn": "Activées",
    "settings.notifyHint": "Vous avertit lorsqu'une transaction est confirmée, que des fonds arrivent ou qu'une alerte de prix se déclenche. Fonctionne uniquement tant que cette page est ouverte dans votre navigateur.",
    "settings.notifyUnsupported": "Ce navigateur ne prend pas en charge les notifications système. Vous verrez toujours les messages dans la page.",
    "settings.notifyDenied": "Les notifications sont bloquées pour ce site dans les paramètres de votre navigateur.",
    "settings.alertLabel": "Alerte de prix (monnaie native)",
    "settings.alertAbove": "passe au-dessus de",
    "settings.alertBelow": "passe en dessous de",
    "settings.alertPlaceholder": "Prix",
    "settings.alertAdd": "Ajouter",
    "settings.alertHint": "Utilise votre devise d'affichage. Chaque alerte ne se déclenche qu'une fois, et seulement tant que cette page est ouverte.",
    "settings.alertRemove": "Supprimer l'alerte",
    "settings.alertBadPrice": "Saisissez un prix supérieur à zéro.",
    "settings.alertNoFeed": "Aucun flux de prix n'est disponible pour ce réseau pour le moment.",
    "notify.txConfirmed": "Transaction confirmée",
    "notify.txFailed": "Échec de la transaction",
    "notify.received": "Fonds reçus",
    "notify.priceAlert": "Alerte de prix",
    "swap.bridgeLink": "Vous passez sur une autre chaîne ? Transférez vos fonds via un bridge ↗",
    "send.feeEstimateUnavailable": "Estimation des frais de réseau indisponible -- vous verrez quand même les frais réels avant toute diffusion.",
    "send.confirmFeeLine": "Frais de réseau : ~{fee} {symbol}",
    "send.toPlaceholder": "0x... ou nom.eth",
    "send.resolvingName": "Recherche de {name}...",
    "send.resolvedName": "Correspond à {address}",
    "send.nameNotFound": "Aucune adresse trouvée pour {name} -- vérifiez le nom ou collez directement l'adresse.",
    "send.nameResolutionUnsupported": "La recherche de noms n'est pas disponible sur ce réseau -- collez directement l'adresse.",
    "swap.selectBtn": "Choisir",
    "swap.balanceLabel": "Solde : {amount} {symbol}",
    "swap.maxBtn": "Max",
    "swap.quotingHint": "Obtention du devis…",
    "swap.rateLabel": "Taux",
    "swap.appFeeShortLabel": "Frais de l'application",
    "swap.priceImpactLabel": "Impact sur le prix",
    "swap.priceImpactWarn": "L'impact sur le prix est d'environ {percent}. Il y a peu de ce token disponible à l'échange : vous recevrez nettement moins que le cours actuel. Pensez à un montant plus petit.",
    "swap.priceImpactHigh": "L'impact sur le prix est très élevé (environ {percent}). Une grande partie de votre montant est perdue à cause du mouvement du prix. Essayez un montant bien plus petit.",
    "swap.priceImpactConfirm": "L'impact sur le prix est d'environ {percent}. Vous recevrez bien moins que le prix du marché. Échanger quand même ?",
    "app.name": "Échange de Tokens",
    "app.copyright": "© 2026 Échange de Tokens",
    "scan.button": "🔍 Analyser le portefeuille",
    "scan.title": "Analyser le portefeuille",
    "scan.intro": "Vérifie ce compte sur le réseau actuel à la recherche de tokens populaires cotés sur le marché et affiche ceux qu'il détient. Seuls les soldes publics sont lus : rien n'est ajouté tant que vous n'appuyez pas sur Ajouter, et les tokens hors de cette liste (y compris les imitations reçues par airdrop) ne sont jamais affichés.",
    "scan.addAll": "Tout ajouter",
    "scan.again": "Analyser à nouveau",
    "scan.scanning": "Analyse du compte en cours…",
    "scan.unsupported": "L'analyse n'est pas encore disponible sur ce réseau. Utilisez « + Ajouter un token » et collez une adresse de contrat.",
    "scan.noAccount": "Aucun compte sélectionné.",
    "scan.noCatalog": "Impossible de joindre CoinGecko : seuls les stablecoins vérifiés ont été contrôlés.",
    "scan.none": "Aucun nouveau token trouvé sur ce compte.",
    "scan.add": "Ajouter",
    "scan.adding": "Ajout…",
    "scan.added": "Ajouté ✓",
    "swap.minReceivedLabel": "Minimum reçu",
    "swap.networkFeeLabel": "Frais de réseau",
    "swap.gasStep_approve": "Approbation",
    "swap.gasStep_fee": "Transfert des frais de l'application",
    "swap.gasStep_swap": "Échange",
    "swap.gasPriceLabel": "Prix du gaz",
    "swap.gasUnavailable": "Indisponible",
    "swap.gasLowEth": "Attention : les frais de réseau de cet échange sont d'environ {need} {symbol}, mais ce compte ne contient que {have}. Ajoutez d'abord un peu de {symbol}, sinon la transaction échouera.",
    "swap.selectAssetTitle": "Choisir un actif",
    "swap.selectTokenTitle": "Choisir un token",
    "swap.pickerSearchPlaceholder": "Saisissez le nom du token ou collez l'adresse",
    "swap.pickerNoFavs": "Aucun token favori sur ce réseau pour l'instant. Touchez l'étoile d'un token pour l'ajouter.",
    "swap.pickerInfoTitle": "Voir dans l'explorateur de blocs",
    "swap.pickerStarTitle": "Mettre le token en favori",
    "swap.pickerNoMatch": "Aucun token correspondant sur ce réseau.",
    "swap.pickerLoadFailed": "Impossible de charger la liste des jetons. Vérifiez votre connexion et réessayez.",
    "swap.pickerNothingHeld": "Aucun actif de ce réseau n'a encore de solde. Ajoutez des fonds ou changez de réseau ci-dessus.",
    "swap.pickerUseAddress": "Utiliser cette adresse de token",
    "swap.pickerLoadingTokens": "Recherche de tokens...",
    "swap.pickerTopTokens": "Principaux tokens sur ce réseau",
    "swap.pickerSearchResults": "Résultats de la recherche",
    "swap.pickerSuggested": "Stablecoins suggérés (vérifiés par l'émetteur)",
    "swap.pickerNoSwapHere": "L'échange n'est pas encore activé sur ce réseau. Choisissez un autre réseau ci-dessus.",
    "swap.noAssetsHint": "Rien de disponible ici pour l'instant.",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "Carnet d'adresses",
    "settings.currencyLabel": "Devise d'affichage",
    "settings.navStyleLabel": "Style de navigation",
    "settings.navCube": "Cube",
    "settings.navGlobe": "Globe",
    "settings.feedbackBtn": "Demander une fonctionnalité",
    "settings.sendDelayLabel": "Délai d'envoi (fenêtre d'annulation)",
    "settings.sendDelayHint": "Retient chaque envoi sortant pendant ce délai afin que vous puissiez l'annuler avant sa diffusion. Cela ne couvre que les envois effectués ici dans Token Exchange -- cela ne peut pas protéger un portefeuille dont la clé privée ou la phrase de récupération a déjà été exposée en dehors de l'application.",
    "settings.autoLockLabel": "Verrouillage automatique après inactivité",
    "settings.autoLockOff": "Désactivé (jamais de verrouillage automatique)",
    "settings.autoLock1": "1 minute",
    "settings.autoLock5": "5 minutes",
    "settings.autoLock15": "15 minutes",
    "settings.autoLock21": "21 minutes (par défaut)",
    "settings.autoLock30": "30 minutes",
    "settings.autoLockHint": "Verrouille automatiquement le portefeuille après ce délai sans clic, toucher ni frappe au clavier ici -- car un onglet de navigateur laissé ouvert resterait sinon déverrouillé indéfiniment.",
    "settings.sendDelayOff": "Désactivé (envoi immédiat)",
    "settings.sendDelay15": "15 secondes",
    "settings.sendDelay30": "30 secondes (recommandé)",
    "settings.sendDelay60": "60 secondes",
    "feedback.title": "Demandes de fonctionnalités",
    "feedback.subtitle": "Découvrez ce que demandent les autres utilisateurs, votez pour celles que vous souhaitez aussi, ou publiez la vôtre. Cette liste est publique -- c'est ainsi que nous décidons de ce que nous développons ensuite.",
    "feedback.titlePlaceholder": "Titre court (p. ex. « Mode sombre »)",
    "feedback.descPlaceholder": "Un peu plus de détails (facultatif)",
    "feedback.submitBtn": "Publier la demande",
    "feedback.submittingStatus": "Publication...",
    "feedback.submittedStatus": "Merci ! Votre demande est en ligne ci-dessous.",
    "feedback.listTitle": "DEMANDES",
    "feedback.empty": "Aucune demande pour l'instant -- soyez le premier !",
    "feedback.loadError": "Impossible de charger les demandes. Réessayez dans un instant.",
    "feedback.titleRequired": "Donnez d'abord un titre court.",
    "feedback.upvoteBtn": "Voter pour",
    "feedback.upvotedBtn": "Voté",
    "feedback.contactLine": "Vous préférez l'e-mail ? Écrivez-nous à msandersod@gmail.com",
    "wc.title": "WalletConnect",
    "wc.subtitle": "Connectez-vous à n'importe quelle dapp proposant une option « WalletConnect » -- collez ci-dessous l'URI wc:... du code QR de connexion de portefeuille.",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "Connecter",
    "wc.notConfigured": "WalletConnect nécessite un identifiant de projet gratuit avant de pouvoir se connecter à quoi que ce soit -- voir lib/walletconnect-config.js.",
    "wc.sessionsTitle": "Dapps connectées",
    "wc.sessionsEmpty": "Aucune dapp connectée pour l'instant.",
    "wc.disconnectBtn": "Déconnecter",
    "wc.invalidUri": "Cela ne ressemble pas à un URI WalletConnect -- il doit commencer par « wc: ».",
    "wc.pairingStatus": "Appairage... une demande de connexion devrait apparaître dans un instant.",
    "wc.pairedStatus": "Appairé -- vérifiez si une nouvelle fenêtre vous demande d'approuver la connexion.",
    "swap.appFeeValue": "{percent} ({amount} {symbol})",
    "main.findNftsBtn": "🔍 Trouver des NFT",
    "findNfts.title": "Trouver des NFT",
    "findNfts.description": "Analyse l'adresse de ce compte sur le réseau actuel et liste ce qu'elle détient, via l'API NFT d'Alchemy. Cela ne lit que des données publiques de propriété sur la blockchain -- rien de votre portefeuille n'est envoyé ailleurs que l'adresse que vous utilisez déjà.",
    "findNfts.loadMore": "Charger plus",
    "swap.flipBtnTitle": "Inverser le sens de l'échange",
    "findNfts.loading": "Recherche de NFT...",
    "findNfts.notConfigured": "La recherche de NFT n'est pas encore configurée sur ce serveur.",
    "findNfts.notSupported": "La recherche de NFT n'est pas disponible sur ce réseau.",
    "findNfts.empty": "Aucun NFT trouvé pour ce compte sur ce réseau.",
    "findNfts.loadError": "Impossible de charger les NFT. Réessayez dans un instant.",
    "findNfts.addedBtn": "Déjà ajouté",
    "findNfts.addBtn": "Ajouter à mes NFT",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "Comment créer un portefeuille ?",
      keywords: ["créer un portefeuille", "créer portefeuille", "nouveau portefeuille", "configurer le portefeuille", "configuration du portefeuille", "pour commencer", "première fois"],
      answer: "Appuyez sur « Créer un nouveau portefeuille » sur l'écran d'accueil, choisissez un mot de passe (celui-ci ne fait que déverrouiller le portefeuille sur cet appareil -- il ne peut pas récupérer vos fonds), puis une phrase de récupération de 12 mots vous sera présentée. Notez-la en lieu sûr avant de continuer -- cette phrase est le seul moyen de récupérer vos fonds si cet appareil venait à être perdu.",
    },
    {
      id: "import-wallet",
      chip: "Comment importer un portefeuille existant ?",
      keywords: ["importer un portefeuille", "importer un portefeuille existant", "restaurer un portefeuille", "portefeuille existant", "importer la phrase de récupération", "importer la seed"],
      answer: "Sur l'écran d'accueil, appuyez sur « Importer un portefeuille existant », saisissez votre phrase de récupération de 12 ou 24 mots exactement comme elle a été notée (en minuscules, séparée par des espaces), puis définissez un nouveau mot de passe pour cet appareil. La phrase elle-même ne quitte jamais votre appareil -- elle est utilisée localement pour dériver vos comptes.",
    },
    {
      id: "forgot-password",
      chip: "J'ai oublié mon mot de passe",
      keywords: ["mot de passe oublié", "j'ai oublié mon mot de passe", "mauvais mot de passe", "impossible de déverrouiller", "verrouillé", "le mot de passe ne fonctionne pas"],
      answer: "Votre mot de passe ne fait que déverrouiller le portefeuille sur cet appareil -- Token Exchange ne le stocke nulle part et ne peut pas le réinitialiser pour vous. Si vous ne vous en souvenez plus, appuyez sur « Réinitialiser le portefeuille à la place » sur l'écran de déverrouillage, puis réimportez votre portefeuille à l'aide de votre phrase de récupération de 12 mots. Si vous n'avez pas sauvegardé cette phrase, les fonds de ce portefeuille ne pourront malheureusement pas être récupérés -- c'est la contrepartie d'un portefeuille non dépositaire : personne d'autre que vous ne peut le déverrouiller, ce qui signifie aussi que personne d'autre que vous ne peut le sauver.",
    },
    {
      id: "lost-seed-phrase",
      chip: "J'ai perdu ma phrase de récupération",
      keywords: ["seed perdue", "j'ai perdu ma seed", "phrase de récupération perdue", "j'ai perdu ma phrase de récupération", "je n'ai pas ma phrase", "j'ai oublié ma phrase", "je ne l'ai jamais notée", "pas sauvegardé"],
      answer: "Si vous êtes toujours connecté, allez dans Paramètres → « Afficher la phrase de récupération », ressaisissez votre mot de passe, et notez-la dès maintenant en lieu sûr. Si vous êtes verrouillé ET que vous n'avez jamais sauvegardé la phrase, il n'existe aucun moyen de récupérer le portefeuille ou les fonds qu'il contient. Token Exchange ne stocke jamais votre phrase où que ce soit -- ni sur un serveur, ni dans le cloud, nulle part -- de sorte que personne, pas même le développeur, ne peut la récupérer pour vous.",
    },
    {
      id: "balance-not-showing",
      chip: "Mon solde ne s'affiche pas",
      keywords: ["solde", "solde nul", "0,00", "ne s'affiche pas", "mauvais solde", "solde bloqué", "chargement en cours", "solde à 0"],
      answer: "Un solde bloqué sur « ... » signifie généralement que le point d'accès RPC de ce réseau est lent ou temporairement indisponible -- ce portefeuille réessaie automatiquement avec un point d'accès de secours après quelques secondes, donc le problème se résout généralement de lui-même. S'il affiche 0 et que cela vous semble incorrect, vérifiez que vous êtes sur le bon réseau et le bon compte (les deux menus déroulants se trouvent sur l'écran principal) -- les soldes sont suivis séparément par réseau et par compte, donc les fonds sur Base ne s'afficheront pas tant qu'Ethereum Mainnet est sélectionné, par exemple.",
    },
    {
      id: "swap-failed",
      chip: "Mon échange a échoué",
      keywords: ["échange échoué", "échange bloqué", "l'échange ne fonctionne pas", "erreur d'échange", "devis échoué", "le swap a échoué", "le swap ne fonctionne pas"],
      answer: "Les échanges se font on-chain via le routeur public d'un exchange décentralisé, donc un échec s'explique généralement par l'une de ces trois raisons : un solde insuffisant pour couvrir le montant plus les frais de gas du réseau, une tolérance de glissement trop stricte pour un prix qui évolue rapidement (essayez 1 % ou 3 % au lieu de 0,5 %), ou cette paire de tokens qui n'a pas encore assez de liquidité sur le routeur de ce réseau. L'erreur affichée sur l'écran d'échange après « Obtenir un devis » indique généralement de laquelle il s'agit -- si ce n'est pas clair, réessayez d'abord avec un montant plus petit.",
    },
    {
      id: "swap-fee",
      chip: "Combien coûte un échange ?",
      keywords: ["frais d'échange", "combien ça coûte", "0,5 %", "frais sur l'échange", "frais du swap", "quels sont les frais"],
      answer: "Les échanges appliquent des frais fixes de 0,5 % sur le montant échangé, clairement indiqués dans le devis avant que vous ne confirmiez -- ils font partie intégrante de la transaction d'échange, jamais d'une majoration cachée dissimulée dans le taux de change. Cela est distinct des frais de gas du réseau, qui reviennent à la blockchain, pas à Token Exchange.",
    },
    {
      id: "gas-fees",
      chip: "Qu'est-ce que les frais de gas ?",
      keywords: ["frais de gas", "frais de réseau", "frais de transaction", "qu'est-ce que le gas", "coût du gas"],
      answer: "Le gas correspond aux frais que le réseau blockchain lui-même facture pour traiter une transaction -- ils sont distincts des frais d'échange de 0,5 % de Token Exchange et reviennent entièrement au réseau, pas à nous. Le montant varie selon la congestion du réseau au moment de la transaction. Assurez-vous de détenir suffisamment de la monnaie native de ce réseau (ETH, BNB, POL, etc.) pour couvrir le gas, même lorsque vous envoyez un token plutôt que la monnaie native.",
    },
    {
      id: "add-network",
      chip: "Comment ajouter un réseau ?",
      keywords: ["ajouter un réseau", "nouveau réseau", "réseau personnalisé", "autre chaîne", "chaîne différente"],
      answer: "Allez dans Paramètres → « Ajouter un réseau » et renseignez le nom du réseau, l'ID de chaîne, l'URL RPC et le symbole de la monnaie native. Si vous ajoutez également une adresse de routeur d'échange vérifiée, l'échange fonctionnera aussi sur ce réseau -- sinon, il ne gérera que l'envoi et la réception. N'utilisez que des valeurs que vous avez personnellement vérifiées par rapport à la documentation officielle ou à l'explorateur de blocs de ce réseau.",
    },
    {
      id: "add-token",
      chip: "Comment suivre un token ?",
      keywords: ["ajouter un token", "suivre un token", "nouveau token", "token personnalisé", "erc-20", "erc20", "suivre un jeton"],
      answer: "Sur l'écran principal, appuyez sur « + Ajouter un token », collez l'adresse du contrat du token pour votre réseau actuel, puis appuyez sur « Rechercher » -- cela lit le nom, le symbole et les décimales du token directement depuis le contrat afin que vous puissiez vérifier avant de l'ajouter. N'ajoutez un token que si son adresse de contrat provient d'une source de confiance ; un portefeuille ne peut pas distinguer un vrai token d'un faux portant le même nom et le même symbole.",
    },
    {
      id: "send-crypto",
      chip: "Comment envoyer des cryptos ?",
      keywords: ["comment envoyer", "envoyer des cryptos", "envoyer des tokens", "transférer des cryptos", "envoyer de l'eth", "envoyer des fonds"],
      answer: "Appuyez sur « Envoyer » sur l'écran principal, choisissez la monnaie native ou un token (via son adresse de contrat), saisissez l'adresse du destinataire et un montant, puis confirmez. Vérifiez bien l'adresse avant de confirmer -- les envois sur ces réseaux sont irréversibles une fois validés.",
    },
    {
      id: "connect-dapp",
      chip: "Comment me connecter à un site web ?",
      keywords: ["connecter dapp", "se connecter à un site", "bouton connecter le portefeuille", "se connecter à un site web", "ça ne se connecte pas", "ne se connecte pas"],
      answer: "Tout site disposant d'un bouton « Connect Wallet » compatible avec les extensions de portefeuille du navigateur devrait proposer Token Exchange de la même façon qu'il proposerait MetaMask ou Coinbase Wallet. Si un site ne l'affiche pas comme option, essayez d'actualiser la page une fois le portefeuille installé et déverrouillé -- certains sites ne détectent les extensions de portefeuille qu'au chargement de la page.",
    },
    {
      id: "buy-not-working",
      chip: "Achat ou vente ne fonctionne pas",
      keywords: ["bouton acheter", "bouton vendre", "acheter ne fonctionne pas", "vendre ne fonctionne pas", "achat non configuré", "vente non configurée", "transak", "impossible d'acheter", "impossible de vendre"],
      answer: "Acheter et Vendre ouvrent tous deux Transak, un service tiers indépendant d'achat/vente, dans un nouvel onglet. S'il indique que le service « n'est pas encore configuré », cela signifie que le développeur de ce portefeuille n'a pas encore ajouté les identifiants Transak -- ce n'est pas quelque chose que vous pouvez corriger depuis le portefeuille lui-même. Une fois configuré, votre adresse de réception est renseignée et verrouillée automatiquement pour l'achat ; Token Exchange ne l'envoie jamais à votre place.",
    },
    {
      id: "reset-wallet",
      chip: "Comment réinitialiser mon portefeuille ?",
      keywords: ["réinitialiser le portefeuille", "supprimer le portefeuille", "recommencer", "retirer le portefeuille", "effacer le portefeuille"],
      answer: "Paramètres → « Réinitialiser le portefeuille » supprime définitivement le portefeuille chiffré de ce navigateur. Assurez-vous absolument d'avoir sauvegardé votre phrase de récupération au préalable -- cette action est irréversible, et il n'existe aucun moyen de récupérer le portefeuille par la suite sans cette phrase.",
    },
    {
      id: "is-it-safe",
      chip: "Ce portefeuille est-il sûr ?",
      keywords: ["est-ce sûr", "c'est sûr", "faire confiance", "non dépositaire", "dépositaire", "est-ce sécurisé", "est-ce une arnaque", "c'est légitime"],
      answer: "Token Exchange est non dépositaire : votre phrase de récupération et vos clés privées sont chiffrées et stockées uniquement dans votre navigateur -- jamais envoyées à un serveur, car il n'y en a pas. Cela signifie également que personne, pas même le développeur, ne peut récupérer vos fonds si vous perdez à la fois votre mot de passe et votre phrase de récupération. Les envois et les échanges sont également vérifiés par rapport à une liste de sanctions intégrée avant d'être exécutés, entièrement sur l'appareil, et les frais d'échange sont toujours affichés à l'avance, avant que vous ne confirmiez.",
    },
    {
      id: "pending-transaction",
      chip: "Ma transaction est bloquée",
      keywords: ["en attente", "transaction bloquée", "transaction ne se confirme pas", "toujours en attente", "transaction coincée"],
      answer: "Une transaction peut rester « en attente » si le réseau est congestionné ou si le prix du gas utilisé était trop bas pour les conditions actuelles. Elle devrait finir par se confirmer d'elle-même. Si elle reste bloquée depuis longtemps, vous pouvez consulter la transaction sur l'explorateur de blocs de ce réseau à l'aide de l'adresse de votre compte pour voir son statut en temps réel.",
    },
    {
      id: "wrong-network",
      chip: "Quels réseaux sont pris en charge ?",
      keywords: ["quel réseau", "mauvais réseau", "changer de réseau", "réseaux pris en charge", "quelles chaînes", "chaînes prises en charge", "quels réseaux"],
      answer: "Intégrés : Ethereum, Base, Polygon, BNB Chain, Arbitrum One et OP Mainnet, sélectionnables depuis le menu déroulant en bas de l'écran principal -- votre solde, vos tokens et vos options d'échange sont tous spécifiques au réseau sélectionné à cet endroit. Vous pouvez ajouter vous-même n'importe quel autre réseau compatible EVM depuis Paramètres → « Ajouter un réseau ».",
    },
    {
      id: "contact-human",
      chip: "J'ai besoin d'aide supplémentaire",
      keywords: ["parler à un humain", "vraie personne", "contacter le support", "vous contacter", "j'ai encore besoin d'aide", "besoin d'aide supplémentaire", "parler à quelqu'un"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "Bonjour ! Je suis un simple robot d'assistance intégré -- je ne peux répondre qu'à des questions issues d'une liste fixe préétablie, rien de plus. Appuyez sur un sujet ci-dessous ou saisissez votre propre question.";
  const fallbackWithEmail = "Je n'ai pas encore de réponse écrite pour cela. Vous pouvez joindre une personne à {email} -- il est utile de préciser sur quel écran vous étiez et ce que vous attendiez.";
  const fallbackNoEmail = "Je n'ai pas encore de réponse écrite pour cela, et ce portefeuille ne dispose pas non plus d'une assistance humaine en direct pour le moment. Essayez de reformuler votre question, ou consultez le README de l'extension pour plus de détails sur le fonctionnement de chaque fonctionnalité.";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.fr = {
    name: "Français",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
