// lib/i18n/ja.js
// Japanese localization. Must define the exact same `strings` keys and the
// exact same FAQ `id`s as lib/i18n/en.js -- lib/i18n.js falls back to en.js
// for anything missing here, and test-i18n.js checks the key sets match.
(function () {
  const strings = {
    "common.needHelp": "お困りですか?",
    "common.languageLabel": "言語",
    "common.back": "戻る",
    "common.cancel": "キャンセル",
    "common.copy": "コピー",
    "common.send": "送金",
    "common.swap": "スワップ",
    "common.buy": "購入",
    "common.livePrices": "リアルタイム価格",
    "common.reject": "拒否",
    "common.passwordPlaceholder": "パスワード",
    "common.confirmPasswordPlaceholder": "パスワード（確認）",
    "common.newPasswordLabel": "新しいパスワード（8文字以上）",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "トークンアドレス（0x...）",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "ネイティブコイン",

    "onboarding.title": "ようこそ",
    "onboarding.subtitle": "まずはウォレットを設定しましょう。",
    "onboarding.createBtn": "新しいウォレットを作成",
    "onboarding.importBtn": "既存のウォレットをインポート",

    "create.title": "ウォレットを作成",
    "create.passwordLabel": "新しいパスワード（8文字以上）",
    "create.passwordWarning": "このパスワードは、このデバイス上でウォレットのロックを解除するためのものです。パスワードを忘れた場合の復旧手段はありません。資産を復元できるのはリカバリーフレーズだけです。",
    "create.continueBtn": "続ける",
    "create.backupWarning": "このリカバリーフレーズを紙に書き留め、安全な場所に保管してください。これを知っている人は誰でもこのウォレット内のすべての資産を持ち出せます。Token Exchange がこれを復元することはできません。",
    "create.backupCheckbox": "リカバリーフレーズを保存しました",
    "create.finishBtn": "完了",

    "import.title": "ウォレットをインポート",
    "import.mnemonicLabel": "リカバリーフレーズ（12語または24語）",
    "import.mnemonicPlaceholder": "word1 word2 word3 ...",
    "import.submitBtn": "インポート",

    "unlock.title": "ロック解除",
    "unlock.submitBtn": "ロック解除",
    "unlock.resetInsteadBtn": "代わりにウォレットをリセット",

    "main.settingsTitle": "設定",
    "main.portfolioLabel": "合計残高",
    "main.addAccountOption": "+ アカウントを追加",
    "main.tokensTitle": "トークン",
    "main.addTokenBtn": "+ トークンを追加",
    "main.tokensEmpty": "まだトークンが追加されていません。「+ トークンを追加」をタップし、コントラクトアドレスを入力すると残高を表示できます。",
    "main.networkLabel": "ネットワーク",
    "main.balanceFetchErrorPrefix": "残高を取得できませんでした: ",
    "main.watchOnlySuffix": "（ウォッチ中）",
    "main.watchOnlyNotice": "ウォッチ専用アドレスを表示しています -- このウォレットにはこのアドレスの秘密鍵がないため、送金とスワップはここでは無効になっています。",

    "tokens.loadError": "残高を読み込めませんでした",
    "tokens.removeTitle": "削除",

    "addToken.title": "トークンを追加",
    "addToken.description": "現在のネットワークでのトークンのコントラクトアドレスを入力してください。信頼できる情報源から入手したコントラクトアドレスのみを追加してください。ウォレットは、同じ名前の本物のトークンと偽物のトークンを見分けることはできません。",
    "addToken.addressLabel": "トークンのコントラクトアドレス",
    "addToken.lookupBtn": "検索",
    "addToken.nameLabel": "名称:",
    "addToken.symbolLabel": "シンボル:",
    "addToken.decimalsLabel": "小数点桁数:",
    "addToken.confirmBtn": "ウォレットに追加",
    "addToken.invalidAddress": "有効なコントラクトアドレスを入力してください。",
    "addToken.noName": "（名称なし）",
    "addToken.swapUnavailableSuffix": "（スワップ利用不可）",

    "prices.description": "CoinGecko の公開 API による米ドル建て価格です。あくまで参考情報であり、この価格取得のためにウォレットの情報が送信されることはありません。",
    "prices.loading": "読み込み中...",
    "prices.naText": "該当なし",
    "prices.tabCrypto": "暗号資産",
    "prices.tabCurrencies": "通貨",
    "prices.searchPlaceholder": "検索...",
    "prices.currenciesNote": "各通貨 1 単位が、表示通貨でいくらになるかを示します。",
    "prices.noResults": "結果がありません。",
    "prices.viewCoin": "{name} を見る",
    "prices.volShort": "出来高",
    "coin.swapBtn": "{symbol} にスワップ",
    "coin.swapHint": "次の画面で、保有資産のうちどれで支払うかを選べます。",
    "coin.swapNeedsWallet": "スワップするにはウォレットのロックを解除してください。",
    "coin.swapNoRouter": "このネットワークではまだスワップを利用できません。",
    "coin.swapUnavailableNetwork": "{network} では {symbol} をまだスワップできません。ネットワークのネイティブコイン、または「トークンを追加」で追加したトークンである必要があります。",
    "coin.holding": "{amount} {symbol} を保有しています",
    "coin.statsTitle": "マーケット情報",
    "coin.aboutTitle": "概要",
    "coin.aboutUnavailable": "現在、説明はありません。",
    "coin.marketCap": "時価総額",
    "coin.volume24h": "24時間取引量",
    "coin.high24h": "24時間高値",
    "coin.low24h": "24時間安値",
    "coin.supply": "流通供給量",
    "coin.ath": "過去最高値",
    "coin.viewCoingecko": "CoinGecko で見る",
    "coin.loadError": "現在、このコインの詳細を読み込めませんでした。",
    "coin.chartUnavailable": "現在、チャートを表示できません。",
    "swap.customAddressOption": "その他のトークン（アドレスを貼り付け）...",

    "buy.title": "暗号資産を購入",
    "buy.description1": "購入機能は、独立した第三者サービスである Transak によって提供されています。Token Exchange がお客様の支払い情報に触れることは一切ありません。",
    "buy.noThirdPartyCallout": "すでに暗号資産をお持ちですか?Transakを使わずに、必要なものへ直接オンチェーンでスワップできます -- 第三者もサインアップも不要です。",
    "buy.noThirdPartySwapBtn": "代わりにスワップする",
    "buy.continueBtn": "Transak に進む",
    "buy.pickerTitle": "購入するコインを選択",
    "buy.pickerSearchPlaceholder": "名前またはシンボルでコインを検索",
    "buy.pickerCurrencies": "通貨",
    "buy.pickerCrypto": "暗号資産",
    "buy.changeCoinBtn": "コインを変更",

    "support.title": "ヘルプ＆サポート",
    "support.description": "質問を入力するか、下のトピックをタップしてください。この機能はすべてお使いのデバイス上で完結しており、ここに入力した内容が外部に送信されることはありません。",
    "support.inputPlaceholder": "質問を入力...",

    "send.title": "送金",
    "send.assetLabel": "資産",
    "send.assetToken": "トークン（コントラクトアドレスを入力）",
    "send.tokenAddressPlaceholder": "トークンのコントラクトアドレス（0x...）",
    "send.toLabel": "送付先アドレス",
    "send.amountLabel": "数量",
    "send.speedSlow": "低速",
    "send.speedStandard": "標準",
    "send.speedFast": "高速",
    "send.invalidRecipient": "有効な送付先アドレスを入力してください。",
    "send.invalidTokenAddress": "有効なトークンのコントラクトアドレスを入力してください。",
    "send.sentStatus": "送金が完了しました。トランザクションハッシュ: {txHash}",
    "send.poisonWarning": "このアドレスは以前使用したアドレス（{match}）によく似ていますが、同じものではありません -- 先頭と末尾は同じでも中間部分が異なります。これは「アドレスポイズニング」と呼ばれる一般的な詐欺の手口で、似たアドレスを履歴に紛れ込ませ、間違った方をコピーさせようとするものです。送金前に一文字ずつ確認してください。",

    "swap.unsupportedWarning": "このネットワークではまだスワップを利用できません（検証済みのルーターが設定されていません）。まず「設定」→「ネットワーク」から追加してください。",
    "swap.fromLabel": "スワップ元",
    "swap.toLabel": "スワップ先",
    "swap.getQuoteBtn": "見積もりを取得",
    "swap.appFeeLine": "アプリ手数料（{percent}）: {amount}",
    "swap.netAmountLine": "実際にスワップされる金額: {amount}",
    "swap.estimatedOutLine": "受け取り予定額: {amount}",
    "swap.slippageLabel": "スリッページ許容度",
    "swap.approveBtn": "先にトークンを承認",
    "swap.approvingStatus": "承認中...",
    "swap.approvedStatus": "承認が完了しました。スワップを実行できます。",
    "swap.sendingStatus": "手数料の送付とスワップを処理中...",
    "swap.swappedStatus": "スワップが完了しました。手数料のトランザクション: {feeTx} | スワップのトランザクション: {tx}",
    "swap.feeTxNa": "該当なし",

    "settings.title": "設定",
    "settings.addAccountBtn": "アカウントを追加",
    "settings.importKeyBtn": "秘密鍵をインポート",
    "settings.addWatchBtn": "ウォッチ専用アドレスを追加",
    "settings.approvalsBtn": "承認を管理",
    "settings.addNetworkBtn": "ネットワークを追加",
    "settings.viewSeedBtn": "リカバリーフレーズを表示",
    "settings.helpBtn": "ヘルプ＆サポート",
    "settings.lockBtn": "ウォレットをロック",
    "settings.resetBtn": "ウォレットをリセット",

    "importKey.title": "秘密鍵をインポート",
    "importKey.description": "これはリカバリーフレーズからではなく、秘密鍵から別のアカウントをこのウォレットに追加します -- リカバリーフレーズではこの鍵を復元できないため、個別にバックアップしてください。秘密鍵は誰とも共有しないでください。持っている人は誰でもそのアカウント内のすべてを使用できます。",
    "importKey.placeholder": "0x から始まる秘密鍵",

    "addWatch.title": "ウォッチ専用アドレスを追加",
    "addWatch.description": "鍵を持たずにアドレスの残高、トークン、アクティビティを追跡します -- 署名できるものがないため、送金とスワップはこのアドレスでは無効のままです。コールドストレージやハードウェアウォレットのアドレスをここから見守るのに便利です。",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "ラベル（任意）",
    "addWatch.submitBtn": "追加",

    "approvals.title": "承認を管理",
    "approvals.description": "このウォレット自身のスワップルーターに対するトークンの使用許可（アプルーバル）を表示し、その他の任意のトークンとスペンダーについては手動で確認できます。取り消すと許可額はゼロに戻ります -- 再度承認するまで、スペンダーはあなたに代わってそのトークンを動かせなくなります。",
    "approvals.emptyText": "追加したトークンに対する承認は見つかりませんでした。",
    "approvals.loading": "承認を確認しています...",
    "approvals.manualHeading": "特定の承認を確認",
    "approvals.tokenPlaceholder": "トークンのコントラクトアドレス（0x...）",
    "approvals.spenderPlaceholder": "スペンダーのコントラクトアドレス（0x...）",
    "approvals.checkBtn": "確認",
    "approvals.tokenLabel": "トークン:",
    "approvals.spenderLabel": "スペンダー:",
    "approvals.allowanceLabel": "許可額:",
    "approvals.revokeBtn": "取り消す",
    "approvals.revokingBtn": "取り消し中...",
    "approvals.rowError": "これを確認できませんでした -- 少し時間をおいて再試行してください。",

    "addNetwork.title": "ネットワークを追加",
    "addNetwork.namePlaceholder": "ネットワーク名",
    "addNetwork.chainIdPlaceholder": "チェーン ID（数値）",
    "addNetwork.rpcPlaceholder": "RPC の URL",
    "addNetwork.symbolPlaceholder": "ネイティブ通貨のシンボル",
    "addNetwork.explorerPlaceholder": "ブロックエクスプローラーの URL（任意）",
    "addNetwork.routerPlaceholder": "検証済みスワップルーターアドレス（任意）",
    "addNetwork.routerWarning": "ルーターアドレスは、プロジェクトの公式ドキュメントまたはそのチェーンのブロックエクスプローラーでご自身で確認できた場合にのみ入力してください。不明な場合は空欄のままにしてください。追加するまでは、このネットワークでのスワップは無効のままになります。",
    "addNetwork.addBtn": "追加",

    "viewSeed.title": "リカバリーフレーズ",
    "viewSeed.passwordPlaceholder": "表示するにはパスワードを入力",
    "viewSeed.revealBtn": "表示する",

    "reset.title": "ウォレットをリセット",
    "reset.warning": "この操作を行うと、このブラウザから暗号化されたウォレットが削除されます。リカバリーフレーズを必ずバックアップしてから実行してください。この操作は取り消せません。",
    "reset.confirmBtn": "はい、すべて削除します",

    "approve.unlockTitle": "続けるにはロックを解除してください",
    "approve.unlockOriginText": "{origin} がアクセスを要求しています。",
    "approve.connectTitle": "接続リクエスト",
    "approve.connectWantsText": "{origin} があなたのウォレットへの接続を求めています。",
    "approve.accountLabel": "アカウント: ",
    "approve.acceptConnectBtn": "接続する",
    "approve.txTitle": "トランザクションリクエスト",
    "approve.toLabel": "宛先:",
    "approve.valueLabel": "金額:",
    "approve.dataLabel": "データ:",
    "approve.txWarning": "このサイトを信頼しており、署名を求められている内容を理解している場合にのみ承認してください。",
    "approve.confirmBtn": "確認",
    "approve.signTitle": "署名リクエスト",
    "approve.signBtn": "署名する",
    "approve.addNetTitle": "ネットワーク追加リクエスト",
    "approve.addNetNameLabel": "名称:",
    "approve.addNetChainIdLabel": "チェーン ID:",
    "approve.addNetRpcLabel": "RPC:",
    "approve.addNetWarning": "このサイトが提案しているネットワークには検証済みのスワップルーターがありません。設定からご自身で追加するまで、このネットワークでのスワップは無効のままになります。",
    "approve.addNetBtn": "ネットワークを追加",
    "approve.switchNetTitle": "ネットワーク切り替えのリクエスト",
    "approve.switchNetText": "{origin} がウォレットを {from} から {to} に切り替えようとしています。",
    "approve.switchNetWarning": "想定している場合のみ切り替えてください。この後に承認するトランザクションは新しいネットワークで送信されます。",
    "approve.switchNetBtn": "ネットワークを切り替える",
    "approve.contractCreation": "（コントラクト作成）",
    "approve.nativeSuffix": "（ネイティブコイン）",
    "approve.decodedLoading": "実際の内容を読み取っています...",
    "approve.decodedTransferLine": "これは{to}に{amount}を送金します。",
    "approve.decodedApproveLine": "これは{to}が{amount}を使用することを承認します。",
    "approve.decodedUnlimited": "無制限 {symbol}",
    "approve.decodedThisToken": "このトークン",
    "approve.decodedRawUnitsSuffix": " 未変換の値（このトークンの小数桁数を確認できませんでした）",
    "approve.decodedGenericIntro": "これは上記のコントラクトの \"{fn}\" を次の内容で呼び出します:",

    "loading.text": "読み込み中...",

    "home.tabHome": "ホーム",
    "home.tabAssets": "資産",
    "home.tabActivity": "アクティビティ",
    "home.tabSend": "送金",
    "home.tapToContinue": "タップして続ける",
    "home.continueBtn": "続ける",

    "activity.title": "アクティビティ",
    "activity.subtitle": "このウォレットから行った送金と、このデバイスが検知した入金の履歴をローカルに記録したものです -- サーバーから取得しているものは一切ありません。",
    "activity.empty": "まだアクティビティはありません -- 送金した内容(および、このデバイスが検知した入金)がここに表示されます。",
    "activity.sentLabel": "{amount} {asset} を送金しました",
    "activity.receivedLabel": "{amount} {asset} を受け取りました",
    "activity.toLabel": "宛先: {address}",
    "activity.statusSent": "送金済み",
    "activity.tabSends": "送金",
    "activity.tabSwaps": "スワップ",
    "activity.swapsSubtitle": "このデバイスでこのウォレットから行ったスワップのローカル記録です -- ここにある内容はサーバーから取得されません。",
    "activity.swapsEmpty": "まだスワップはありません -- このウォレットで行ったスワップがここに表示されます。",
    "activity.swapLabel": "{amountIn} {assetIn} を約 {amountOut} {assetOut} にスワップしました",
    "activity.statusSwapped": "スワップ済み",
    "activity.statusReceived": "受取済み",
    "activity.receivedApproxNote": "残高の変化から検出 -- 概算であり、取引へのリンクはありません",
    "activity.viewOnExplorer": "ブロックエクスプローラーで見る",

    "footer.nonCustodial": "ノンカストディアル — 秘密鍵はこのデバイスの外に出ることはありません",

    "errors.passwordTooShort": "パスワードは8文字以上で入力してください。",
    "errors.passwordMismatch": "パスワードが一致しません。",
    "errors.unknownError": "不明なエラーが発生しました",

    "common.sell": "売却",
    "common.seeAll": "すべて表示",
    "main.showQrBtn": "QRを表示",
    "main.hideQrBtn": "QRを非表示",
    "main.nftsTitle": "NFT",
    "main.addNftBtn": "+ NFTを追加",
    "main.nftsEmpty": "NFTはまだ追加されていません -- 「+ NFTを追加」をタップし、コントラクトアドレスとトークンIDを入力すると追跡できます。",
    "main.livePricesTitle": "リアルタイム価格",
    "main.predictionsTitle": "通貨とステーブルコイン",
    "main.currenciesCardTitle": "通貨",
    "main.exchangesCardTitle": "人気の取引所",
    "addToken.quickAddLabel": "クイック追加：",
    "addToken.quickAddChip": "+ {symbol}",
    "nfts.loadError": "読み込めませんでした",
    "nfts.removeTitle": "削除",
    "addNft.title": "NFTを追加",
    "addNft.description": "ERC-721とERC-1155に対応しています。信頼できる情報源からのみ追加してください。",
    "addNft.addressLabel": "コントラクトアドレス",
    "addNft.tokenIdLabel": "トークンID",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "規格：",
    "addNft.invalidAddress": "有効なコントラクトアドレスを入力してください。",
    "addNft.invalidTokenId": "有効なトークンID（0以上の整数）を入力してください。",
    "addNft.metaWarning": "画像または名前を読み込めませんでしたが、追加は可能です。",
    "addNft.noName": "（名前なし）",
    "prices.watchlistToggle": "星をタップして先頭に固定",
    "prices.cardUnavailable": "現在、価格を取得できません。",
    "prices.viewPeggedCoin": "{currency}に連動するステーブルコイン、{name}を表示",
    "prices.availableOn": "✓ {networks}で利用可能",
    "coin.swapUnavailableSwitchNetwork": "{symbol}は{network}のネイティブコインです。ネットワークを切り替えて、そちらでスワップまたは保有してください。",
    "coin.swapUnavailableSwitchNetworkTracked": "{network}にはすでに{symbol}を追加済みです。切り替えてご利用ください。",
    "coin.swapUnavailableKnownElsewhere": "{symbol}は{network}で検証済みのトークンです。切り替えると自動で追加できます。",
    "coin.switchNetworkBtn": "{network}に切り替える",
    "coin.addOnNetworkBtn": "{network}に追加",
    "coin.buyBtn": "{symbol}を購入",
    "predictions.title": "通貨とステーブルコイン",
    "predictions.description": "各国通貨と、それに連動するステーブルコインのリアルタイム価格です -- 情報提供のみを目的としています。これらの情報の取得にあたりウォレットの情報は一切送信されません。",
    "predictions.tabStable": "ステーブルコイン",
    "predictions.tabTop": "人気コイン",
    "predictions.loading": "読み込み中...",
    "predictions.empty": "現在、ステーブルコインの価格はありません。",
    "predictions.cardUnavailable": "現在、ステーブルコインの価格を取得できません。",
    "predictions.volSuffix": "24時間出来高",
    "exchanges.title": "人気の取引所",
    "exchanges.description": "CoinGeckoの信頼スコアによる中央集権型暗号資産取引所のランキングで、自動的に更新されます -- 情報提供のみを目的としています。Token Exchangeはセルフカストディであり、これらの取引所を経由して取引を行うことはありません。この情報の取得にあたりウォレットの情報は一切送信されません。",
    "exchanges.loading": "読み込み中...",
    "exchanges.empty": "現在、取引所のデータはありません。",
    "exchanges.cardUnavailable": "現在、取引所を取得できません。",
    "exchanges.foundedYear": "{year}年設立",
    "buy.description2": "Transakでの購入はアプリ内でそのまま開き、受取アドレスは入力済みでロックされます -- 貼り付けは不要で、購入した暗号資産はご自身のウォレットにのみ届きます。",
    "buy.presetNote": "{symbol}の購入があらかじめ設定されています -- Transakが開いたあとで別のアセットを選ぶこともできます。",
    "buy.closeWidgetBtn": "← 閉じる",
    "sell.title": "現金化して売却",
    "sell.description1": "売却は、購入と同じサードパーティのサービスであるTransakが提供しています -- Token Exchangeが受取口座の情報に触れることはありません。",
    "sell.description2": "Transakでの売却はアプリ内でそのまま開き、現金での受取額を見積もります。暗号資産の送付先となる入金アドレスが表示され、Transakが受け取ると換金して、連携済みの銀行口座またはカードに支払われます。",
    "sell.continueBtn": "Transakに進む",
    "sell.closeWidgetBtn": "← 閉じる",
    "send.contactsBtn": "連絡先",
    "contacts.title": "アドレス帳",
    "contacts.pickerHint": "連絡先をタップすると、宛先として入力されます。",
    "contacts.namePlaceholder": "名前",
    "contacts.addBtn": "連絡先を保存",
    "contacts.empty": "保存された連絡先はまだありません。",
    "contacts.removeBtn": "削除",
    "contacts.nameRequired": "この連絡先に名前を付けてください。",
    "contacts.invalidAddress": "有効な0xアドレスを入力してください。",
    "send.confirmIntro": "{seconds}秒後に送金します -- まだキャンセルできます。",
    "send.confirmSummary": "{to}へ {amount} {asset}",
    "send.newAddressWarning": "このデバイスからこのアドレスに送金したことはありません -- 正しいアドレスか再確認してください。",
    "send.cancelBtn": "送金をキャンセル",
    "send.cancelledStatus": "送金をキャンセルしました -- 何も送信されていません。",
    "send.feeEstimateLoading": "ネットワーク手数料を見積もり中...",
    "send.feeEstimate": "ネットワーク手数料の目安：約{fee} {symbol}（約{usd}）",
    "send.feeEstimateNoUsd": "ネットワーク手数料の目安：約{fee} {symbol}",
    "fee.burned": "そのうち約{burn} {symbol}はバーン（供給から永久に除外）されます",
    "send.scanBtn": "QRコードをスキャン",
    "send.scanTitle": "ウォレットのQRコードをスキャン",
    "send.scanClose": "閉じる",
    "send.scanHint": "ウォレットアドレスのQRコードにカメラを向けてください。",
    "send.scanUnsupported": "このブラウザではQRスキャンに対応していません。代わりにアドレスを貼り付けてください。",
    "send.scanDenied": "カメラへのアクセスがブロックされました。このサイトでカメラを許可するか、アドレスを貼り付けてください。",
    "send.scanNoAddress": "このQRコードには有効なウォレットアドレスが含まれていません。",
    "send.scanFilled": "アドレスを入力しました。送金前にもう一度確認してください。",
    "activity.exportCsv": "CSVとしてエクスポート",
    "activity.exportEmpty": "エクスポートできるデータはまだありません。",
    "settings.themeLabel": "外観",
    "settings.themeDark": "ダーク（デフォルト）",
    "settings.themeLight": "ライト",
    "settings.notifyLabel": "通知",
    "settings.notifyOff": "オフ",
    "settings.notifyOn": "オン",
    "settings.notifyHint": "トランザクションの承認、着金、価格アラートの発動をお知らせします。このページをブラウザで開いている間のみ動作します。",
    "settings.notifyUnsupported": "このブラウザはシステム通知に対応していません。メッセージはページ内に引き続き表示されます。",
    "settings.notifyDenied": "ブラウザの設定で、このサイトの通知がブロックされています。",
    "settings.alertLabel": "価格アラート（ネイティブコイン）",
    "settings.alertAbove": "を上回ったとき",
    "settings.alertBelow": "を下回ったとき",
    "settings.alertPlaceholder": "価格",
    "settings.alertAdd": "追加",
    "settings.alertHint": "表示通貨を使用します。各アラートは1回だけ発動し、このページを開いている間のみ有効です。",
    "settings.alertRemove": "アラートを削除",
    "settings.alertBadPrice": "0より大きい価格を入力してください。",
    "settings.alertNoFeed": "現在、このネットワークで利用できる価格フィードはありません。",
    "notify.txConfirmed": "トランザクションが承認されました",
    "notify.txFailed": "トランザクションが失敗しました",
    "notify.received": "着金しました",
    "notify.priceAlert": "価格アラート",
    "swap.bridgeLink": "別のチェーンへ移動しますか？ブリッジで資金を移せます ↗",
    "send.feeEstimateUnavailable": "ネットワーク手数料を見積もれません -- ブロードキャスト前に実際の手数料は表示されます。",
    "send.confirmFeeLine": "ネットワーク手数料：約{fee} {symbol}",
    "send.toPlaceholder": "0x... または name.eth",
    "send.resolvingName": "{name}を検索中...",
    "send.resolvedName": "{address}に解決されます",
    "send.nameNotFound": "{name}のアドレスが見つかりませんでした -- 名前を再確認するか、アドレスを直接貼り付けてください。",
    "send.nameResolutionUnsupported": "このネットワークでは名前検索を利用できません -- アドレスを直接貼り付けてください。",
    "swap.selectBtn": "選択",
    "swap.balanceLabel": "残高：{amount} {symbol}",
    "swap.maxBtn": "最大",
    "swap.quotingHint": "見積もりを取得中…",
    "swap.rateLabel": "レート",
    "swap.appFeeShortLabel": "アプリ手数料",
    "swap.priceImpactLabel": "価格への影響",
    "swap.priceImpactWarn": "価格への影響は約 {percent} です。このトークンは取引できる量が少ないため、現在の価格よりかなり少ない額しか受け取れません。金額を減らすことを検討してください。",
    "swap.priceImpactHigh": "価格への影響が非常に大きくなっています（約 {percent}）。金額の大部分が価格変動で失われます。もっと少ない金額で試してください。",
    "swap.priceImpactConfirm": "価格への影響は約 {percent} です。市場価格よりはるかに少ない額しか受け取れません。それでもスワップしますか？",
    "app.name": "トークン取引所",
    "app.copyright": "© 2026 トークン取引所",
    "scan.button": "🔍 ウォレットをスキャン",
    "scan.title": "ウォレットをスキャン",
    "scan.intro": "現在のネットワーク上で、このアカウントが主要な市場上場トークンを保有しているか確認し、保有しているものを一覧表示します。読み取るのは公開残高のみで、「追加」をタップするまで何も追加されません。この一覧にないトークン（エアドロップされた偽物を含む）は表示されません。",
    "scan.addAll": "すべて追加",
    "scan.again": "もう一度スキャン",
    "scan.scanning": "このアカウントのトークンをスキャン中…",
    "scan.unsupported": "このネットワークではまだスキャンできません。「+ トークンを追加」からコントラクトアドレスを貼り付けてください。",
    "scan.noAccount": "アカウントが選択されていません。",
    "scan.noCatalog": "CoinGeckoに接続できなかったため、検証済みのステーブルコインのみ確認しました。",
    "scan.none": "このアカウントに新しいトークンは見つかりませんでした。",
    "scan.add": "追加",
    "scan.adding": "追加中…",
    "scan.added": "追加済み ✓",
    "swap.minReceivedLabel": "最小受取額",
    "swap.networkFeeLabel": "ネットワーク手数料",
    "swap.gasStep_approve": "承認",
    "swap.gasStep_fee": "アプリ手数料の送付",
    "swap.gasStep_swap": "スワップ",
    "swap.gasPriceLabel": "ガス価格",
    "swap.gasUnavailable": "利用不可",
    "swap.gasLowEth": "ご注意：このスワップのネットワーク手数料は約{need} {symbol}ですが、このアカウントには{have}しかありません。先に少額の{symbol}を追加しないと、トランザクションは失敗します。",
    "swap.selectAssetTitle": "アセットを選択",
    "swap.selectTokenTitle": "トークンを選択",
    "swap.pickerSearchPlaceholder": "トークン名を入力、またはアドレスを貼り付け",
    "swap.pickerNoFavs": "このネットワークにはお気に入りのトークンがまだありません。トークンの星をタップして追加してください。",
    "swap.pickerInfoTitle": "ブロックエクスプローラーで表示",
    "swap.pickerStarTitle": "トークンにスターを付ける",
    "swap.pickerNoMatch": "このネットワークに一致するトークンはありません。",
    "swap.pickerLoadFailed": "トークン一覧を読み込めませんでした。接続を確認してもう一度お試しください。",
    "swap.pickerNothingHeld": "このネットワークには残高のある資産がまだありません。入金するか、上でネットワークを切り替えてください。",
    "swap.pickerUseAddress": "このトークンアドレスを使用",
    "swap.pickerLoadingTokens": "トークンを検索中...",
    "swap.pickerTopTokens": "このネットワークの人気トークン",
    "swap.pickerSearchResults": "検索結果",
    "swap.pickerSuggested": "おすすめのステーブルコイン（発行元で検証済み）",
    "swap.pickerNoSwapHere": "このネットワークではまだスワップが有効になっていません。上で別のネットワークを選んでください。",
    "swap.noAssetsHint": "ここにはまだ利用できるものがありません。",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "アドレス帳",
    "settings.currencyLabel": "表示通貨",
    "settings.navStyleLabel": "ナビゲーションのスタイル",
    "settings.navCube": "キューブ",
    "settings.navGlobe": "グローブ",
    "settings.feedbackBtn": "機能をリクエスト",
    "settings.sendDelayLabel": "送金の遅延（キャンセル可能時間）",
    "settings.sendDelayHint": "送信する送金をすべてこの時間だけ保留し、ブロードキャスト前にキャンセルできるようにします。これはここToken Exchangeで行う送金のみが対象で、秘密鍵やリカバリーフレーズがアプリ外ですでに漏えいしているウォレットは保護できません。",
    "settings.autoLockLabel": "操作がない場合の自動ロック",
    "settings.autoLockOff": "オフ（自動ロックしない）",
    "settings.autoLock1": "1分",
    "settings.autoLock5": "5分",
    "settings.autoLock15": "15分",
    "settings.autoLock21": "21分（デフォルト）",
    "settings.autoLock30": "30分",
    "settings.autoLockHint": "ここでのクリック、タップ、キー入力がこの時間なかった場合に、ウォレットを自動でロックします -- 開いたままのブラウザタブは、そのままだとロックされないままになるためです。",
    "settings.sendDelayOff": "オフ（すぐに送金）",
    "settings.sendDelay15": "15秒",
    "settings.sendDelay30": "30秒（推奨）",
    "settings.sendDelay60": "60秒",
    "feedback.title": "機能リクエスト",
    "feedback.subtitle": "他のユーザーがどんな機能を求めているかを確認し、あなたも欲しいものに投票したり、自分のリクエストを投稿したりできます。このリストは公開されており、次に何を開発するかを決める材料になります。",
    "feedback.titlePlaceholder": "短いタイトル（例：「ダークモード」）",
    "feedback.descPlaceholder": "もう少し詳しく（任意）",
    "feedback.submitBtn": "リクエストを投稿",
    "feedback.submittingStatus": "投稿中...",
    "feedback.submittedStatus": "ありがとうございます！リクエストを下に公開しました。",
    "feedback.listTitle": "リクエスト",
    "feedback.empty": "まだリクエストはありません -- 最初の投稿者になりましょう！",
    "feedback.loadError": "リクエストを読み込めませんでした。しばらくしてからもう一度お試しください。",
    "feedback.titleRequired": "先に短いタイトルを入力してください。",
    "feedback.upvoteBtn": "賛成する",
    "feedback.upvotedBtn": "賛成済み",
    "feedback.contactLine": "メールをご希望ですか？msandersod@gmail.com までご連絡ください",
    "wc.title": "WalletConnect",
    "wc.subtitle": "「WalletConnect」オプションがあるdappならどれにでも接続できます -- ウォレット接続のQRコードにあるwc:...のURIを下に貼り付けてください。",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "接続",
    "wc.notConfigured": "WalletConnectは、何かに接続する前に無料のプロジェクトIDが必要です -- lib/walletconnect-config.js を参照してください。",
    "wc.sessionsTitle": "接続中のdapp",
    "wc.sessionsEmpty": "接続中のdappはまだありません。",
    "wc.disconnectBtn": "切断",
    "wc.invalidUri": "WalletConnectのURIではないようです -- 「wc:」で始まる必要があります。",
    "wc.pairingStatus": "ペアリング中... まもなく接続リクエストが表示されます。",
    "wc.pairedStatus": "ペアリング完了 -- 接続の承認を求める新しいウィンドウが開いていないか確認してください。",
    "swap.appFeeValue": "{percent} ({amount} {symbol})",
    "main.findNftsBtn": "🔍 NFTを探す",
    "findNfts.title": "NFTを探す",
    "findNfts.description": "AlchemyのNFT APIを使って、このアカウントのアドレスを現在のネットワークでスキャンし、保有しているものを一覧表示します。読み取るのは公開されているオンチェーンの所有データのみで -- すでに使用しているアドレス以外、ウォレットの情報はどこにも送信されません。",
    "findNfts.loadMore": "さらに読み込む",
    "swap.flipBtnTitle": "スワップの方向を入れ替え",
    "findNfts.loading": "NFTを検索中...",
    "findNfts.notConfigured": "このサーバーではNFT検索がまだ設定されていません。",
    "findNfts.notSupported": "このネットワークではNFT検索を利用できません。",
    "findNfts.empty": "このネットワークでこのアカウントのNFTは見つかりませんでした。",
    "findNfts.loadError": "NFTを読み込めませんでした。しばらくしてからもう一度お試しください。",
    "findNfts.addedBtn": "追加済み",
    "findNfts.addBtn": "マイNFTに追加",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "ウォレットの作成方法は？",
      keywords: ["ウォレット 作成", "ウォレットを作成", "新規ウォレット", "ウォレット 新規作成", "はじめかた", "初めて", "セットアップ", "ウォレット セットアップ"],
      answer: "ようこそ画面で「新しいウォレットを作成」をタップし、パスワードを設定してください（このパスワードはこのデバイス上でウォレットのロックを解除するためだけのもので、資産の復元には使えません）。その後、12語のリカバリーフレーズが表示されます。続ける前に必ず安全な場所に書き留めてください。このデバイスを紛失した場合、資産を復元できる唯一の手段がそのフレーズです。",
    },
    {
      id: "import-wallet",
      chip: "既存のウォレットをインポートするには？",
      keywords: ["ウォレット インポート", "既存のウォレット", "ウォレット 復元", "リカバリーフレーズ インポート", "シードフレーズ インポート", "インポート方法"],
      answer: "ようこそ画面で「既存のウォレットをインポート」をタップし、12語または24語のリカバリーフレーズを記載通り正確に（小文字・半角スペース区切りで）入力したうえで、このデバイス用の新しいパスワードを設定してください。フレーズ自体がデバイスの外に送信されることはなく、アカウントの導出にローカルで使われるだけです。",
    },
    {
      id: "forgot-password",
      chip: "パスワードを忘れました",
      keywords: ["パスワード 忘れた", "パスワードを忘れた", "パスワード 違う", "ロック解除できない", "パスワード 間違い", "パスワード 反映されない", "ログインできない"],
      answer: "パスワードはこのデバイス上でウォレットのロックを解除するためだけのものです。Token Exchange はどこにもパスワードを保存しておらず、代わりにリセットすることもできません。パスワードを思い出せない場合は、ロック解除画面の「代わりにウォレットをリセット」をタップし、12語のリカバリーフレーズを使ってウォレットを再度インポートしてください。そのフレーズを保存していない場合、残念ながらこのウォレットの資産を復元する方法はありません。それがノンカストディアルウォレットの特性です。あなた以外の誰もロックを解除できない代わりに、あなた以外の誰も救済することができません。",
    },
    {
      id: "lost-seed-phrase",
      chip: "リカバリーフレーズを紛失しました",
      keywords: ["シードフレーズ 紛失", "リカバリーフレーズ 紛失", "リカバリーフレーズ ない", "フレーズを失くした", "書き留めていない", "保存し忘れた", "フレーズ 忘れた"],
      answer: "まだログインできている場合は、「設定」→「リカバリーフレーズを表示」からパスワードを再入力し、今すぐ安全な場所に書き留めてください。ロックされていて、かつフレーズを一度も保存していない場合、ウォレットや中の資産を復元する方法はありません。Token Exchange はリカバリーフレーズをサーバーやクラウドなど、どこにも一切保存していないため、開発者を含め誰もそれを取得することはできません。",
    },
    {
      id: "balance-not-showing",
      chip: "残高が表示されません",
      keywords: ["残高", "残高 ゼロ", "残高 0", "残高 表示されない", "残高 おかしい", "読み込み中のまま", "残高 反映されない"],
      answer: "残高が「...」のまま止まっている場合、多くはそのネットワークの RPC エンドポイントが遅延しているか一時的にダウンしていることが原因です。このウォレットは数秒後に自動でバックアップのエンドポイントに切り替えて再試行するため、通常は自然に解消します。0 のまま確定していておかしいと感じる場合は、正しいネットワークと正しいアカウントが選択されているか（どちらもメイン画面のドロップダウンにあります）を確認してください。残高はネットワークごと、アカウントごとに別々に管理されているため、たとえば Ethereum Mainnet が選択されている間は Base 上の資産は表示されません。",
    },
    {
      id: "swap-failed",
      chip: "スワップに失敗しました",
      keywords: ["スワップ 失敗", "スワップ できない", "スワップ エラー", "スワップ 動かない", "見積もり 失敗", "スワップ 止まる"],
      answer: "スワップは公開の分散型取引所のルーターを通じてオンチェーンで行われるため、失敗する原因は主に3つです。1つ目はスワップ額とガス代を合わせた残高が不足している、2つ目は価格変動が速いのにスリッページ許容度が厳しすぎる（0.5% ではなく 1% や 3% を試してください）、3つ目はそのネットワークのルーターにそのトークンペアの十分な流動性がまだない、というものです。「見積もりを取得」の後に表示されるエラー内容が原因の手がかりになります。不明な場合は、まず少額で試してみてください。",
    },
    {
      id: "swap-fee",
      chip: "スワップの手数料はいくらですか？",
      keywords: ["スワップ 手数料", "手数料 いくら", "0.5%", "スワップ 料金", "手数料について", "手数料はいくら"],
      answer: "スワップにはスワップ額に対して一律 0.5% の手数料がかかり、確認する前に見積もり画面に明示されます。これはスワップのトランザクション自体に含まれるもので、為替レートに隠された上乗せではありません。この手数料は、ブロックチェーンに支払われる（Token Exchange には渡らない）ガス代とは別のものです。",
    },
    {
      id: "gas-fees",
      chip: "ガス代とは何ですか？",
      keywords: ["ガス代", "ネットワーク手数料", "トランザクション手数料", "ガスとは", "ガス代 いくら"],
      answer: "ガス代は、トランザクションを処理するためにブロックチェーンのネットワーク自体が徴収する手数料であり、Token Exchange のスワップ手数料（0.5%）とは別物で、全額がネットワークに支払われ、当社には入りません。金額はその時のネットワークの混雑状況によって変動します。トークンを送る場合でも、ガス代を賄うためにそのネットワークのネイティブコイン（ETH、BNB、POL など）を十分に保有しておいてください。",
    },
    {
      id: "add-network",
      chip: "ネットワークを追加するには？",
      keywords: ["ネットワーク 追加", "新しいネットワーク", "カスタムネットワーク", "別のチェーン", "他のチェーン"],
      answer: "「設定」→「ネットワークを追加」から、ネットワーク名、チェーン ID、RPC の URL、ネイティブ通貨のシンボルを入力してください。検証済みのスワップルーターアドレスも併せて入力すれば、そのネットワークでもスワップが利用できるようになります。入力しない場合は送金・受け取りのみ対応します。値は必ずそのネットワークの公式ドキュメントかブロックエクスプローラーでご自身で確認したものを使用してください。",
    },
    {
      id: "add-token",
      chip: "トークンを登録するには？",
      keywords: ["トークン 追加", "トークン 登録", "新しいトークン", "カスタムトークン", "ERC-20", "ERC20", "トークンを追加したい"],
      answer: "メイン画面で「+ トークンを追加」をタップし、現在のネットワークにおけるそのトークンのコントラクトアドレスを貼り付けて「検索」をタップしてください。コントラクトから直接、名称・シンボル・小数点桁数が読み込まれるので、追加する前に内容を確認できます。信頼できる情報源から入手したコントラクトアドレスのみを追加してください。ウォレットは、同じ名前やシンボルを使った偽トークンを本物と見分けることができません。",
    },
    {
      id: "send-crypto",
      chip: "暗号資産を送るには？",
      keywords: ["送金方法", "暗号資産 送る", "トークン 送る", "送金のやり方", "ETH 送金", "資産を送る"],
      answer: "メイン画面で「送金」をタップし、ネイティブコインかトークン（コントラクトアドレスで指定）を選び、送付先のアドレスと数量を入力して確認してください。確定する前に必ずアドレスを再確認してください。これらのネットワーク上での送金は、一度承認されると取り消すことができません。",
    },
    {
      id: "connect-dapp",
      chip: "サイトに接続するには？",
      keywords: ["サイトに接続", "dApp 接続", "接続できない", "ウォレット接続 ボタン", "つながらない"],
      answer: "ブラウザ拡張機能のウォレットに対応した「Connect Wallet」ボタンがあるサイトなら、MetaMask や Coinbase Wallet と同じように Token Exchange も選択肢として表示されるはずです。表示されない場合は、ウォレットをインストールしてロックを解除した状態でページを再読み込みしてみてください。サイトによっては、ページの読み込み時にしかウォレット拡張機能を検出しないことがあります。",
    },
    {
      id: "buy-not-working",
      chip: "購入または売却が使えません",
      keywords: ["購入 使えない", "売却 使えない", "購入できない", "売却できない", "購入 動かない", "売却 動かない", "購入 未設定", "売却 未設定", "Transak", "買えない", "売れない"],
      answer: "「購入」と「売却」はどちらも、独立した第三者のオンランプ/オフランプサービスである Transak を新しいタブで開きます。「このサービスはまだ設定されていません」と表示される場合、このウォレットの開発者がまだ Transak の認証情報を設定していないことを意味しており、ウォレット内から解決できるものではありません。設定が完了すると、購入時の受取アドレスは自動的に入力・ロックされます。Token Exchange が代わりに送信することはありません。",
    },
    {
      id: "reset-wallet",
      chip: "ウォレットをリセットするには？",
      keywords: ["ウォレット リセット", "ウォレット 削除", "最初からやり直す", "ウォレット 消す", "ウォレット 初期化"],
      answer: "「設定」→「ウォレットをリセット」を選ぶと、このブラウザから暗号化されたウォレットが完全に削除されます。実行する前に、必ずリカバリーフレーズをバックアップ済みであることを確認してください。この操作は取り消せず、そのフレーズがなければリセット後にウォレットを元に戻す方法はありません。",
    },
    {
      id: "is-it-safe",
      chip: "このウォレットは安全ですか？",
      keywords: ["安全ですか", "信用できる", "ノンカストディアル", "カストディアル", "セキュリティ", "詐欺ですか", "本物ですか"],
      answer: "Token Exchange はノンカストディアル（非管理型）のウォレットです。リカバリーフレーズと秘密鍵は暗号化された状態でお使いのブラウザにのみ保存され、サーバーへ送信されることはありません。そもそもサーバー自体が存在しないためです。これは同時に、パスワードとリカバリーフレーズの両方を紛失した場合、開発者を含め誰も資産を復元できないことも意味します。送金・スワップは送信前にデバイス上で同梱の制裁リストと照合され、スワップ手数料も確認前に必ず明示されます。",
    },
    {
      id: "pending-transaction",
      chip: "トランザクションが止まっています",
      keywords: ["ペンディング", "トランザクション 止まる", "承認されない", "処理中のまま", "トランザクション 詰まる"],
      answer: "ネットワークが混雑していたり、設定したガス代がその時の状況に対して低すぎたりすると、トランザクションが「保留中（pending）」のままになることがあります。多くの場合は時間が経てば自動的に承認されます。長時間止まったままの場合は、アカウントアドレスを使ってそのネットワークのブロックエクスプローラーでトランザクションを検索し、リアルタイムの状況を確認できます。",
    },
    {
      id: "wrong-network",
      chip: "対応しているネットワークは？",
      keywords: ["対応ネットワーク", "ネットワーク 間違い", "ネットワーク 切り替え", "対応チェーン", "使えるチェーン", "どのネットワーク"],
      answer: "標準で Ethereum、Base、Polygon、BNB Chain、Arbitrum One、OP Mainnet に対応しており、メイン画面下部のドロップダウンから切り替えられます。残高・トークン・スワップの選択肢は、そこで選ばれているネットワークごとに異なります。それ以外の EVM 互換ネットワークも、「設定」→「ネットワークを追加」からご自身で追加できます。",
    },
    {
      id: "contact-human",
      chip: "もっとサポートが必要です",
      keywords: ["人と話したい", "担当者に相談", "サポートに連絡", "問い合わせたい", "まだ解決しない", "もっと助けが必要", "オペレーターに相談"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "こんにちは。私はシンプルな内蔵ヘルプボットです。あらかじめ用意された固定リストの質問にのみお答えできます。下のトピックをタップするか、質問を直接入力してください。";
  const fallbackWithEmail = "その質問に対する回答はまだ用意されていません。{email} まで担当者にご連絡いただけます。どの画面で何が起きたか、何を期待していたかを添えていただけるとスムーズです。";
  const fallbackNoEmail = "その質問に対する回答はまだ用意されておらず、このウォレットには現時点で有人のサポート窓口も設定されていません。質問の言い回しを変えて試すか、拡張機能の README で各機能の詳しい説明をご確認ください。";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.ja = {
    name: "日本語",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
