// lib/i18n/zh.js
// Simplified Chinese localization. Must define the exact same `strings`
// keys and the exact same FAQ `id`s as lib/i18n/en.js -- lib/i18n.js falls
// back to en.js for anything missing here, and test-i18n.js checks the key
// sets match.
(function () {
  const strings = {
    "common.needHelp": "需要帮助？",
    "common.languageLabel": "语言",
    "common.back": "返回",
    "common.cancel": "取消",
    "common.copy": "复制",
    "common.send": "发送",
    "common.swap": "兑换",
    "common.buy": "购买",
    "common.livePrices": "实时价格",
    "common.reject": "拒绝",
    "common.passwordPlaceholder": "密码",
    "common.confirmPasswordPlaceholder": "确认密码",
    "common.newPasswordLabel": "新密码（至少 8 位）",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "代币地址（0x...）",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "原生币",

    "onboarding.title": "欢迎",
    "onboarding.subtitle": "设置您的钱包以开始使用。",
    "onboarding.createBtn": "创建新钱包",
    "onboarding.importBtn": "导入已有钱包",

    "create.title": "创建钱包",
    "create.passwordLabel": "新密码（至少 8 位）",
    "create.passwordWarning": "此密码仅用于解锁您在本设备上的钱包，无法找回——只有助记词才能恢复您的资金。",
    "create.continueBtn": "继续",
    "create.backupWarning": "请写下此助记词并妥善保管在安全的地方。任何人只要获得它，就能取走此钱包中的全部资产。Token Exchange 无法替您找回助记词。",
    "create.backupCheckbox": "我已保存助记词",
    "create.finishBtn": "完成",

    "import.title": "导入钱包",
    "import.mnemonicLabel": "助记词（12 或 24 个单词）",
    "import.mnemonicPlaceholder": "word1 word2 word3 ...",
    "import.submitBtn": "导入",

    "unlock.title": "解锁",
    "unlock.submitBtn": "解锁",
    "unlock.resetInsteadBtn": "改为重置钱包",

    "main.settingsTitle": "设置",
    "main.portfolioLabel": "总余额",
    "main.addAccountOption": "+ 添加账户",
    "main.tokensTitle": "代币",
    "main.addTokenBtn": "+ 添加代币",
    "main.tokensEmpty": "尚未添加任何代币——点击「+ 添加代币」并输入合约地址即可添加追踪。",
    "main.networkLabel": "网络",
    "main.balanceFetchErrorPrefix": "无法获取余额：",
    "main.watchOnlySuffix": "（观察中）",
    "main.watchOnlyNotice": "你正在查看一个仅观察地址 -- 该钱包中没有此地址的私钥，因此这里的发送和兑换已关闭。",

    "tokens.loadError": "无法加载余额",
    "tokens.removeTitle": "移除",

    "addToken.title": "添加代币",
    "addToken.description": "请输入该代币在当前网络上的合约地址。请仅添加来自可信来源的合约地址——钱包无法分辨真代币与使用相同名称的仿冒代币。",
    "addToken.addressLabel": "代币合约地址",
    "addToken.lookupBtn": "查询",
    "addToken.nameLabel": "名称：",
    "addToken.symbolLabel": "符号：",
    "addToken.decimalsLabel": "小数位数：",
    "addToken.confirmBtn": "添加到我的钱包",
    "addToken.invalidAddress": "请输入有效的合约地址。",
    "addToken.noName": "（无名称）",
    "addToken.swapUnavailableSuffix": "（不支持兑换）",

    "prices.description": "美元价格来自 CoinGecko 的公共 API，仅供参考——查询过程中不会发送任何与您钱包相关的信息。",
    "prices.loading": "加载中...",
    "prices.naText": "无数据",
    "prices.tabCrypto": "加密货币",
    "prices.tabCurrencies": "法定货币",
    "prices.searchPlaceholder": "搜索...",
    "prices.currenciesNote": "每种货币 1 单位按您所选显示货币折算的价值。",
    "prices.noResults": "没有结果。",

    "buy.title": "购买加密货币",
    "buy.description1": "购买功能由独立的第三方服务 MoonPay 提供支持——Token Exchange 不会接触您的支付信息。",
    "buy.noThirdPartyCallout": "已经持有一些加密货币了?完全跳过 MoonPay——直接在链上兑换成您需要的资产,无需第三方,无需注册。",
    "buy.noThirdPartySwapBtn": "改为兑换",
    "buy.description2Html": "MoonPay 将在下方直接打开。由于本钱包无法使用密钥安全地对请求进行签名（密钥绝不能存放在浏览器扩展中——详见 <code>lib/buy-config.js</code>），请在加载完成后<strong>自行粘贴您的收款地址</strong>：",
    "buy.continueBtn": "前往 MoonPay",

    "support.title": "帮助与支持",
    "support.description": "在下方提问，或点击一个主题。此功能完全在您的设备本地运行——您在此输入的内容不会被发送到任何地方。",
    "support.inputPlaceholder": "输入您的问题...",

    "send.title": "发送",
    "send.assetLabel": "资产",
    "send.assetToken": "代币（输入合约地址）",
    "send.tokenAddressPlaceholder": "代币合约地址（0x...）",
    "send.toLabel": "收款地址",
    "send.amountLabel": "金额",
    "send.speedSlow": "慢速",
    "send.speedStandard": "标准",
    "send.speedFast": "快速",
    "send.invalidRecipient": "请输入有效的收款地址。",
    "send.invalidTokenAddress": "请输入有效的代币合约地址。",
    "send.sentStatus": "发送成功！交易哈希：{txHash}",
    "send.poisonWarning": "这个地址和你之前用过的一个地址（{match}）非常相似，但并不相同 -- 开头和结尾一样，中间部分却不同。这是一种常见的诈骗手法（“地址投毒”），骗子在你的历史记录中植入相似地址，指望你复制错的那个。发送前请逐字核对。",

    "swap.unsupportedWarning": "当前网络尚未启用兑换功能——尚未配置经过验证的路由合约。请先在「设置 → 网络」中添加。",
    "swap.fromLabel": "从",
    "swap.toLabel": "至",
    "swap.getQuoteBtn": "获取报价",
    "swap.appFeeLine": "应用手续费（{percent}）：{amount}",
    "swap.netAmountLine": "实际兑换金额：{amount}",
    "swap.estimatedOutLine": "预计到账：{amount}",
    "swap.slippageLabel": "滑点容差",
    "swap.approveBtn": "请先授权代币",
    "swap.approvingStatus": "授权中...",
    "swap.approvedStatus": "已授权，现在可以兑换。",
    "swap.sendingStatus": "正在发送手续费并兑换...",
    "swap.swappedStatus": "兑换成功！手续费交易：{feeTx} | 兑换交易：{tx}",
    "swap.feeTxNa": "无",

    "settings.title": "设置",
    "settings.addAccountBtn": "添加账户",
    "settings.importKeyBtn": "导入私钥",
    "settings.addWatchBtn": "添加仅观察地址",
    "settings.approvalsBtn": "管理授权",
    "settings.addNetworkBtn": "添加网络",
    "settings.viewSeedBtn": "查看助记词",
    "settings.helpBtn": "帮助与支持",
    "settings.lockBtn": "锁定钱包",
    "settings.resetBtn": "重置钱包",

    "importKey.title": "导入私钥",
    "importKey.description": "这会通过原始私钥（而非您的助记词）向此钱包添加一个独立账户 -- 请单独备份该私钥，因为您的助记词无法恢复它。切勿与任何人分享私钥；任何拥有它的人都可以花掉该账户中的所有资产。",
    "importKey.placeholder": "0x 私钥",

    "addWatch.title": "添加仅观察地址",
    "addWatch.description": "在不持有密钥的情况下跟踪某地址的余额、代币和活动 -- 这里没有可用于签名的内容，因此该地址的发送和兑换保持关闭。适合从这里留意冷存储或硬件钱包地址。",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "标签（可选）",
    "addWatch.submitBtn": "添加",

    "approvals.title": "管理授权",
    "approvals.description": "显示该钱包自身兑换路由器的代币消费授权，并提供针对其他任意代币和花费方的手动查询。撤销会将授权额度归零 -- 在你重新授权之前，花费方将无法再代表你转移该代币。",
    "approvals.emptyText": "未找到你已添加代币的授权记录。",
    "approvals.loading": "正在检查授权...",
    "approvals.manualHeading": "检查特定授权",
    "approvals.tokenPlaceholder": "代币合约地址（0x...）",
    "approvals.spenderPlaceholder": "花费方合约地址（0x...）",
    "approvals.checkBtn": "检查",
    "approvals.tokenLabel": "代币：",
    "approvals.spenderLabel": "花费方：",
    "approvals.allowanceLabel": "授权额度：",
    "approvals.revokeBtn": "撤销",
    "approvals.revokingBtn": "撤销中...",
    "approvals.rowError": "无法检查此项 -- 请稍后重试。",

    "addNetwork.title": "添加网络",
    "addNetwork.namePlaceholder": "网络名称",
    "addNetwork.chainIdPlaceholder": "链 ID（数字）",
    "addNetwork.rpcPlaceholder": "RPC URL",
    "addNetwork.symbolPlaceholder": "原生代币符号",
    "addNetwork.explorerPlaceholder": "区块浏览器 URL（可选）",
    "addNetwork.routerPlaceholder": "已验证的兑换路由合约地址（可选）",
    "addNetwork.routerWarning": "请仅在您已亲自对照项目官方文档或该链的区块浏览器核实过路由地址后再填写。如不确定，请留空——在您添加之前，该网络的兑换功能将保持禁用状态。",
    "addNetwork.addBtn": "添加",

    "viewSeed.title": "助记词",
    "viewSeed.passwordPlaceholder": "输入密码以查看",
    "viewSeed.revealBtn": "显示",

    "reset.title": "重置钱包",
    "reset.warning": "此操作将从该浏览器中删除已加密的钱包数据。请确保您已备份助记词——此操作无法撤销。",
    "reset.confirmBtn": "是的，删除所有数据",

    "approve.unlockTitle": "解锁以继续",
    "approve.unlockOriginText": "{origin} 正在请求访问权限。",
    "approve.connectTitle": "连接请求",
    "approve.connectWantsText": "{origin} 想要连接您的钱包。",
    "approve.accountLabel": "账户：",
    "approve.acceptConnectBtn": "连接",
    "approve.txTitle": "交易请求",
    "approve.toLabel": "收款方：",
    "approve.valueLabel": "金额：",
    "approve.dataLabel": "数据：",
    "approve.txWarning": "只有在您信任该网站，并清楚了解其要求您签署的内容时，才应确认此操作。",
    "approve.confirmBtn": "确认",
    "approve.signTitle": "签名请求",
    "approve.signBtn": "签名",
    "approve.addNetTitle": "添加网络请求",
    "approve.addNetNameLabel": "名称：",
    "approve.addNetChainIdLabel": "链 ID：",
    "approve.addNetRpcLabel": "RPC：",
    "approve.addNetWarning": "该网站建议添加的网络尚无经过验证的兑换路由合约。在您于「设置」中自行添加之前，该网络的兑换功能将保持禁用状态。",
    "approve.addNetBtn": "添加网络",
    "approve.contractCreation": "（合约创建）",
    "approve.nativeSuffix": "（原生币）",
    "approve.decodedLoading": "正在解析其实际作用...",
    "approve.decodedTransferLine": "这将向 {to} 转账 {amount}。",
    "approve.decodedApproveLine": "这将授权 {to} 使用 {amount}。",
    "approve.decodedUnlimited": "无限量 {symbol}",
    "approve.decodedThisToken": "此代币",
    "approve.decodedRawUnitsSuffix": " 原始单位（无法确认该代币的小数位数）",
    "approve.decodedGenericIntro": "这将以以下参数调用上方合约中的 “{fn}”：",

    "loading.text": "加载中...",

    "home.tabHome": "首页",
    "home.tabAssets": "资产",
    "home.tabActivity": "动态",
    "home.tabSend": "发送",
    "home.tapToContinue": "点击继续",
    "home.continueBtn": "继续",

    "activity.title": "动态",
    "activity.subtitle": "本钱包发送记录的本地记录，以及本设备察觉到的转入记录 -- 这里的内容都不是从服务器获取的。",
    "activity.empty": "暂无动态 -- 您发起的发送(以及本设备察觉到的转入)将显示在这里。",
    "activity.sentLabel": "已发送 {amount} {asset}",
    "activity.receivedLabel": "已收到 {amount} {asset}",
    "activity.toLabel": "至 {address}",
    "activity.statusSent": "已发送",
    "activity.statusReceived": "已收到",
    "activity.receivedApproxNote": "根据余额变化检测得出 -- 为估算值，无可用交易链接",
    "activity.viewOnExplorer": "在区块浏览器中查看",

    "footer.nonCustodial": "非托管钱包 — 您的密钥永远不会离开本设备",

    "errors.passwordTooShort": "密码至少需要 8 个字符。",
    "errors.passwordMismatch": "两次输入的密码不一致。",
    "errors.unknownError": "未知错误",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "如何创建钱包？",
      keywords: ["创建钱包", "新建钱包", "怎么创建钱包", "如何创建钱包", "设置钱包", "新手", "第一次使用"],
      answer: "在欢迎页面点击「创建新钱包」，设置一个密码（该密码仅用于解锁本设备上的钱包，无法用来找回资金），随后系统会显示一组 12 个单词的助记词。请先将它抄写并妥善保存后再继续——如果这台设备日后丢失或损坏，这组助记词是找回资金的唯一方式。",
    },
    {
      id: "import-wallet",
      chip: "如何导入已有钱包？",
      keywords: ["导入钱包", "导入已有钱包", "恢复钱包", "导入助记词", "导入种子短语", "已有钱包怎么导入"],
      answer: "在欢迎页面点击「导入已有钱包」，按原样输入您的 12 个或 24 个单词的助记词（全部小写，以空格分隔），然后为本设备设置一个新密码。助记词本身不会离开您的设备——它仅在本地用于生成您的账户。",
    },
    {
      id: "forgot-password",
      chip: "我忘记密码了",
      keywords: ["忘记密码", "密码忘了", "密码错误", "无法解锁", "打不开钱包", "密码不对", "登录不了"],
      answer: "您的密码仅用于解锁本设备上的钱包——Token Exchange 从不存储该密码，也无法为您重置。如果您想不起密码，请在解锁页面点击「改为重置钱包」，然后使用您的 12 个单词助记词重新导入钱包。如果您没有保存助记词，那么很遗憾，此钱包中的资金将无法找回——这正是非托管钱包的代价：除了您本人，没有任何人能解锁它，这也意味着除了您本人，没有任何人能挽救它。",
    },
    {
      id: "lost-seed-phrase",
      chip: "我的助记词丢失了",
      keywords: ["助记词丢了", "丢失助记词", "没有备份助记词", "忘记保存助记词", "种子短语丢了", "没抄助记词"],
      answer: "如果您目前仍处于登录状态，请前往「设置 → 查看助记词」，重新输入密码，并立即将其抄写并妥善保存。如果您已被锁定在钱包之外，且此前从未保存过助记词，那么该钱包及其中的资金将无法找回。Token Exchange 从不会将您的助记词存储在任何地方——无论是服务器、云端还是其他任何位置——因此包括开发者在内，没有任何人能替您找回它。",
    },
    {
      id: "balance-not-showing",
      chip: "我的余额没有显示",
      keywords: ["余额不显示", "余额为零", "余额不对", "余额一直加载", "余额显示0", "查不到余额"],
      answer: "如果余额一直显示为「...」，通常是该网络的 RPC 节点响应缓慢或暂时不可用——本钱包会在几秒后自动重试备用节点，一般会自行恢复正常。如果余额最终显示为 0 但您认为不对，请仔细检查是否选择了正确的网络和账户（这两个下拉菜单都在主界面上）——余额是按网络和账户分别统计的，例如当前选择 Ethereum Mainnet 时，Base 上的资产是不会显示出来的。",
    },
    {
      id: "swap-failed",
      chip: "我的兑换失败了",
      keywords: ["兑换失败", "闪兑失败", "兑换出错", "兑换卡住", "报价失败", "兑换不成功"],
      answer: "兑换是通过公开的去中心化交易所路由合约在链上完成的，因此失败通常是以下三种情况之一：余额不足以支付兑换金额加燃料费（gas 费）、在价格波动较快时滑点容差设置过紧（可尝试将 0.5% 调整为 1% 或 3%），或者该交易对在该网络路由上的流动性尚不充足。点击「获取报价」后兑换页面显示的错误信息通常会说明具体原因——如果不确定，可以先尝试用较小的金额重试。",
    },
    {
      id: "swap-fee",
      chip: "兑换需要支付什么费用？",
      keywords: ["兑换手续费", "兑换费用", "闪兑手续费", "手续费多少", "0.5%手续费", "收费多少"],
      answer: "每笔兑换会收取固定 0.5% 的手续费，在您确认之前会在报价中清楚显示——这笔费用是兑换交易本身的一部分，绝不会被隐藏在汇率里。这与燃料费（gas 费）是分开的，燃料费支付给区块链网络，而不是 Token Exchange。",
    },
    {
      id: "gas-fees",
      chip: "什么是燃料费（gas 费）？",
      keywords: ["燃料费", "gas费", "网络手续费", "交易费", "什么是gas"],
      answer: "燃料费（gas 费）是区块链网络本身为处理交易而收取的费用——它与 Token Exchange 的 0.5% 兑换手续费无关，全部支付给网络，而非我们。费用高低会随当时的网络拥堵程度变化。请确保您持有足够数量的该网络原生币（如 ETH、BNB、POL 等）以支付燃料费，即使您发送的是代币而非原生币，也同样需要用原生币支付燃料费。",
    },
    {
      id: "add-network",
      chip: "如何添加网络？",
      keywords: ["添加网络", "新增网络", "自定义网络", "添加链", "切换到其他链"],
      answer: "前往「设置 → 添加网络」，填写网络名称、链 ID、RPC URL 以及原生代币符号。如果您同时填写了经过验证的兑换路由合约地址，该网络也将支持兑换功能——否则该网络将仅支持收发功能。请务必只填写您已亲自对照该网络官方文档或区块浏览器核实过的信息。",
    },
    {
      id: "add-token",
      chip: "如何添加代币追踪？",
      keywords: ["添加代币", "追踪代币", "自定义代币", "添加ERC20", "erc-20代币"],
      answer: "在主界面点击「+ 添加代币」，粘贴该代币在当前网络上的合约地址，然后点击「查询」——系统会直接从合约中读取代币的名称、符号和小数位数，供您确认后再添加。请仅添加来自可信来源的合约地址；钱包无法分辨真代币与使用相同名称和符号的仿冒代币。",
    },
    {
      id: "send-crypto",
      chip: "如何发送加密货币？",
      keywords: ["怎么发送", "发送加密货币", "转账", "发送代币", "转账eth", "如何转账"],
      answer: "在主界面点击「发送」，选择原生币或代币（通过合约地址选择），输入收款地址和金额，然后确认。请在确认前仔细核对地址——这些网络上的转账一经完成即不可撤销。",
    },
    {
      id: "connect-dapp",
      chip: "如何连接到网站？",
      keywords: ["连接dapp", "连接网站", "连接钱包按钮", "无法连接", "连不上钱包"],
      answer: "任何带有「连接钱包」按钮且支持浏览器钱包扩展的网站，都应当像识别 MetaMask 或 Coinbase Wallet 一样识别 Token Exchange。如果某个网站没有将其列为可选项，请在钱包安装并解锁后刷新页面重试——部分网站只会在页面加载时检测钱包扩展。",
    },
    {
      id: "buy-not-working",
      chip: "购买功能无法使用",
      keywords: ["购买按钮", "购买不能用", "购买没反应", "moonpay", "无法购买", "买不了"],
      answer: "「购买」按钮会在新标签页中打开第三方法币入金服务 MoonPay。如果提示「购买功能尚未配置」，说明本钱包的开发者尚未添加 MoonPay API 密钥——这不是您在钱包内部可以解决的问题。配置完成后，您需要自行将收款地址粘贴到 MoonPay 页面中；Token Exchange 不会代您发送该地址。",
    },
    {
      id: "reset-wallet",
      chip: "如何重置我的钱包？",
      keywords: ["重置钱包", "删除钱包", "清空钱包", "重新开始", "移除钱包"],
      answer: "「设置 → 重置钱包」会永久删除该浏览器中已加密的钱包数据。请务必先确认您已备份好助记词——此操作无法撤销，一旦执行，若没有助记词将无法再找回该钱包。",
    },
    {
      id: "is-it-safe",
      chip: "这个钱包安全吗？",
      keywords: ["安全吗", "靠谱吗", "是骗局吗", "非托管", "会不会是诈骗", "值得信任吗"],
      answer: "Token Exchange 是一款非托管钱包：您的助记词和私钥经过加密后仅存储在您的浏览器中——绝不会发送到任何服务器，因为本产品根本没有服务器。这也意味着，如果您同时丢失密码和助记词，包括开发者在内的任何人都无法帮您找回资金。发送和兑换在发出前都会在本地对照内置的制裁名单进行检查，且兑换手续费始终会在您确认前提前展示。",
    },
    {
      id: "pending-transaction",
      chip: "我的交易卡住了",
      keywords: ["交易卡住", "交易一直待确认", "交易不确认", "交易pending", "一直显示待处理"],
      answer: "如果网络拥堵，或交易使用的燃料费价格相对当前情况偏低，交易可能会长时间处于「待处理」状态，通常最终仍会自行确认。如果长时间未能确认，您可以使用账户地址在该网络的区块浏览器上查询该交易的实时状态。",
    },
    {
      id: "wrong-network",
      chip: "支持哪些网络？",
      keywords: ["支持哪些网络", "切换网络", "支持的链", "有哪些网络", "网络选错了"],
      answer: "内置支持：Ethereum、Base、Polygon、BNB Chain、Arbitrum One 和 OP Mainnet，可通过主界面底部附近的下拉菜单切换——您的余额、代币和兑换选项都对应于当前选中的网络。您也可以通过「设置 → 添加网络」自行添加任何其他兼容 EVM 的网络。",
    },
    {
      id: "contact-human",
      chip: "我需要更多帮助",
      keywords: ["联系人工", "真人客服", "联系支持", "联系客服", "还需要帮助", "转人工"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "您好！我是内置的简易帮助机器人——我只能回答预先编写好的固定问题列表中的内容，仅此而已。请点击下方主题，或输入您自己的问题。";
  const fallbackWithEmail = "我目前还没有针对这个问题的现成答案。您可以通过 {email} 联系人工客服——建议说明您当时所在的界面以及您期望发生的情况，这样会更有帮助。";
  const fallbackNoEmail = "我目前还没有针对这个问题的现成答案，而且本钱包尚未设置人工客服渠道。您可以尝试换一种方式描述问题，或查阅该扩展的 README 文件，了解各项功能的详细说明。";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.zh = {
    name: "中文（简体）",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
