// lib/i18n/zh.js
// Simplified Chinese localization. Must define the exact same `strings`
// keys and the exact same FAQ `id`s as lib/i18n/en.js -- lib/i18n.js falls
// back to en.js for anything missing here, and test-i18n.js checks the key
// sets match.
(function () {
  const strings = {
    "common.needHelp": "需要帮助？",
    "common.languageLabel": "语言",
    "common.back": "返回",
    "common.cancel": "取消",
    "common.copy": "复制",
    "common.send": "发送",
    "common.swap": "兑换",
    "common.buy": "购买",
    "common.livePrices": "实时价格",
    "common.reject": "拒绝",
    "common.passwordPlaceholder": "密码",
    "common.confirmPasswordPlaceholder": "确认密码",
    "common.newPasswordLabel": "新密码（至少 8 位）",
    "common.addressPlaceholder0x": "0x...",
    "common.tokenAddressPlaceholderParen": "代币地址（0x...）",
    "common.amountPlaceholder": "0.0",
    "common.nativeCoinOption": "原生币",

    "onboarding.title": "欢迎",
    "onboarding.subtitle": "设置您的钱包以开始使用。",
    "onboarding.createBtn": "创建新钱包",
    "onboarding.importBtn": "导入已有钱包",

    "create.title": "创建钱包",
    "create.passwordLabel": "新密码（至少 8 位）",
    "create.passwordWarning": "此密码仅用于解锁您在本设备上的钱包，无法找回——只有助记词才能恢复您的资金。",
    "create.continueBtn": "继续",
    "create.backupWarning": "请写下此助记词并妥善保管在安全的地方。任何人只要获得它，就能取走此钱包中的全部资产。Token Exchange 无法替您找回助记词。",
    "create.backupCheckbox": "我已保存助记词",
    "create.finishBtn": "完成",

    "import.title": "导入钱包",
    "import.mnemonicLabel": "助记词（12 或 24 个单词）",
    "import.mnemonicPlaceholder": "word1 word2 word3 ...",
    "import.submitBtn": "导入",

    "unlock.title": "解锁",
    "unlock.submitBtn": "解锁",
    "unlock.resetInsteadBtn": "改为重置钱包",

    "main.settingsTitle": "设置",
    "main.portfolioLabel": "总余额",
    "main.addAccountOption": "+ 添加账户",
    "main.tokensTitle": "代币",
    "main.addTokenBtn": "+ 添加代币",
    "main.tokensEmpty": "尚未添加任何代币——点击「+ 添加代币」并输入合约地址即可添加追踪。",
    "main.networkLabel": "网络",
    "main.balanceFetchErrorPrefix": "无法获取余额：",
    "main.watchOnlySuffix": "（观察中）",
    "main.watchOnlyNotice": "你正在查看一个仅观察地址 -- 该钱包中没有此地址的私钥，因此这里的发送和兑换已关闭。",

    "tokens.loadError": "无法加载余额",
    "tokens.removeTitle": "移除",

    "addToken.title": "添加代币",
    "addToken.description": "请输入该代币在当前网络上的合约地址。请仅添加来自可信来源的合约地址——钱包无法分辨真代币与使用相同名称的仿冒代币。",
    "addToken.addressLabel": "代币合约地址",
    "addToken.lookupBtn": "查询",
    "addToken.nameLabel": "名称：",
    "addToken.symbolLabel": "符号：",
    "addToken.decimalsLabel": "小数位数：",
    "addToken.confirmBtn": "添加到我的钱包",
    "addToken.invalidAddress": "请输入有效的合约地址。",
    "addToken.noName": "（无名称）",
    "addToken.swapUnavailableSuffix": "（不支持兑换）",

    "prices.description": "美元价格来自 CoinGecko 的公共 API，仅供参考——查询过程中不会发送任何与您钱包相关的信息。",
    "prices.loading": "加载中...",
    "prices.naText": "无数据",
    "prices.tabCrypto": "加密货币",
    "prices.tabCurrencies": "法定货币",
    "prices.searchPlaceholder": "搜索...",
    "prices.currenciesNote": "每种货币 1 单位按您所选显示货币折算的价值。",
    "prices.noResults": "没有结果。",
    "prices.viewCoin": "查看 {name}",
    "coin.swapBtn": "兑换为 {symbol}",
    "coin.swapHint": "下一屏您可以选择用哪种持有资产来支付。",
    "coin.swapNeedsWallet": "请解锁钱包后再兑换。",
    "coin.swapNoRouter": "此网络暂未启用兑换功能。",
    "coin.swapUnavailableNetwork": "暂时无法在 {network} 上兑换 {symbol}。它必须是该网络的原生币，或您已通过“添加代币”添加的代币。",
    "coin.holding": "您持有 {amount} {symbol}",
    "coin.statsTitle": "市场数据",
    "coin.aboutTitle": "简介",
    "coin.aboutUnavailable": "暂无简介。",
    "coin.marketCap": "市值",
    "coin.volume24h": "24 小时成交量",
    "coin.high24h": "24 小时最高价",
    "coin.low24h": "24 小时最低价",
    "coin.supply": "流通量",
    "coin.ath": "历史最高价",
    "coin.viewCoingecko": "在 CoinGecko 上查看",
    "coin.loadError": "暂时无法加载该币的更多详情。",
    "coin.chartUnavailable": "图表暂时不可用。",
    "swap.customAddressOption": "其他代币（粘贴地址）...",

    "buy.title": "购买加密货币",
    "buy.description1": "购买功能由独立的第三方服务 MoonPay 提供支持——Token Exchange 不会接触您的支付信息。",
    "buy.noThirdPartyCallout": "已经持有一些加密货币了?完全跳过 MoonPay——直接在链上兑换成您需要的资产,无需第三方,无需注册。",
    "buy.noThirdPartySwapBtn": "改为兑换",
    "buy.continueBtn": "前往 MoonPay",

    "support.title": "帮助与支持",
    "support.description": "在下方提问，或点击一个主题。此功能完全在您的设备本地运行——您在此输入的内容不会被发送到任何地方。",
    "support.inputPlaceholder": "输入您的问题...",

    "send.title": "发送",
    "send.assetLabel": "资产",
    "send.assetToken": "代币（输入合约地址）",
    "send.tokenAddressPlaceholder": "代币合约地址（0x...）",
    "send.toLabel": "收款地址",
    "send.amountLabel": "金额",
    "send.speedSlow": "慢速",
    "send.speedStandard": "标准",
    "send.speedFast": "快速",
    "send.invalidRecipient": "请输入有效的收款地址。",
    "send.invalidTokenAddress": "请输入有效的代币合约地址。",
    "send.sentStatus": "发送成功！交易哈希：{txHash}",
    "send.poisonWarning": "这个地址和你之前用过的一个地址（{match}）非常相似，但并不相同 -- 开头和结尾一样，中间部分却不同。这是一种常见的诈骗手法（“地址投毒”），骗子在你的历史记录中植入相似地址，指望你复制错的那个。发送前请逐字核对。",

    "swap.unsupportedWarning": "当前网络尚未启用兑换功能——尚未配置经过验证的路由合约。请先在「设置 → 网络」中添加。",
    "swap.fromLabel": "从",
    "swap.toLabel": "至",
    "swap.getQuoteBtn": "获取报价",
    "swap.appFeeLine": "应用手续费（{percent}）：{amount}",
    "swap.netAmountLine": "实际兑换金额：{amount}",
    "swap.estimatedOutLine": "预计到账：{amount}",
    "swap.slippageLabel": "滑点容差",
    "swap.approveBtn": "请先授权代币",
    "swap.approvingStatus": "授权中...",
    "swap.approvedStatus": "已授权，现在可以兑换。",
    "swap.sendingStatus": "正在发送手续费并兑换...",
    "swap.swappedStatus": "兑换成功！手续费交易：{feeTx} | 兑换交易：{tx}",
    "swap.feeTxNa": "无",

    "settings.title": "设置",
    "settings.addAccountBtn": "添加账户",
    "settings.importKeyBtn": "导入私钥",
    "settings.addWatchBtn": "添加仅观察地址",
    "settings.approvalsBtn": "管理授权",
    "settings.addNetworkBtn": "添加网络",
    "settings.viewSeedBtn": "查看助记词",
    "settings.helpBtn": "帮助与支持",
    "settings.lockBtn": "锁定钱包",
    "settings.resetBtn": "重置钱包",

    "importKey.title": "导入私钥",
    "importKey.description": "这会通过原始私钥（而非您的助记词）向此钱包添加一个独立账户 -- 请单独备份该私钥，因为您的助记词无法恢复它。切勿与任何人分享私钥；任何拥有它的人都可以花掉该账户中的所有资产。",
    "importKey.placeholder": "0x 私钥",

    "addWatch.title": "添加仅观察地址",
    "addWatch.description": "在不持有密钥的情况下跟踪某地址的余额、代币和活动 -- 这里没有可用于签名的内容，因此该地址的发送和兑换保持关闭。适合从这里留意冷存储或硬件钱包地址。",
    "addWatch.addressPlaceholder": "0x...",
    "addWatch.labelPlaceholder": "标签（可选）",
    "addWatch.submitBtn": "添加",

    "approvals.title": "管理授权",
    "approvals.description": "显示该钱包自身兑换路由器的代币消费授权，并提供针对其他任意代币和花费方的手动查询。撤销会将授权额度归零 -- 在你重新授权之前，花费方将无法再代表你转移该代币。",
    "approvals.emptyText": "未找到你已添加代币的授权记录。",
    "approvals.loading": "正在检查授权...",
    "approvals.manualHeading": "检查特定授权",
    "approvals.tokenPlaceholder": "代币合约地址（0x...）",
    "approvals.spenderPlaceholder": "花费方合约地址（0x...）",
    "approvals.checkBtn": "检查",
    "approvals.tokenLabel": "代币：",
    "approvals.spenderLabel": "花费方：",
    "approvals.allowanceLabel": "授权额度：",
    "approvals.revokeBtn": "撤销",
    "approvals.revokingBtn": "撤销中...",
    "approvals.rowError": "无法检查此项 -- 请稍后重试。",

    "addNetwork.title": "添加网络",
    "addNetwork.namePlaceholder": "网络名称",
    "addNetwork.chainIdPlaceholder": "链 ID（数字）",
    "addNetwork.rpcPlaceholder": "RPC URL",
    "addNetwork.symbolPlaceholder": "原生代币符号",
    "addNetwork.explorerPlaceholder": "区块浏览器 URL（可选）",
    "addNetwork.routerPlaceholder": "已验证的兑换路由合约地址（可选）",
    "addNetwork.routerWarning": "请仅在您已亲自对照项目官方文档或该链的区块浏览器核实过路由地址后再填写。如不确定，请留空——在您添加之前，该网络的兑换功能将保持禁用状态。",
    "addNetwork.addBtn": "添加",

    "viewSeed.title": "助记词",
    "viewSeed.passwordPlaceholder": "输入密码以查看",
    "viewSeed.revealBtn": "显示",

    "reset.title": "重置钱包",
    "reset.warning": "此操作将从该浏览器中删除已加密的钱包数据。请确保您已备份助记词——此操作无法撤销。",
    "reset.confirmBtn": "是的，删除所有数据",

    "approve.unlockTitle": "解锁以继续",
    "approve.unlockOriginText": "{origin} 正在请求访问权限。",
    "approve.connectTitle": "连接请求",
    "approve.connectWantsText": "{origin} 想要连接您的钱包。",
    "approve.accountLabel": "账户：",
    "approve.acceptConnectBtn": "连接",
    "approve.txTitle": "交易请求",
    "approve.toLabel": "收款方：",
    "approve.valueLabel": "金额：",
    "approve.dataLabel": "数据：",
    "approve.txWarning": "只有在您信任该网站，并清楚了解其要求您签署的内容时，才应确认此操作。",
    "approve.confirmBtn": "确认",
    "approve.signTitle": "签名请求",
    "approve.signBtn": "签名",
    "approve.addNetTitle": "添加网络请求",
    "approve.addNetNameLabel": "名称：",
    "approve.addNetChainIdLabel": "链 ID：",
    "approve.addNetRpcLabel": "RPC：",
    "approve.addNetWarning": "该网站建议添加的网络尚无经过验证的兑换路由合约。在您于「设置」中自行添加之前，该网络的兑换功能将保持禁用状态。",
    "approve.addNetBtn": "添加网络",
    "approve.switchNetTitle": "切换网络请求",
    "approve.switchNetText": "{origin} 想将你的钱包从 {from} 切换到 {to}。",
    "approve.switchNetWarning": "仅在你预期会发生时才切换。之后你批准的交易将在新网络上发送。",
    "approve.switchNetBtn": "切换网络",
    "approve.contractCreation": "（合约创建）",
    "approve.nativeSuffix": "（原生币）",
    "approve.decodedLoading": "正在解析其实际作用...",
    "approve.decodedTransferLine": "这将向 {to} 转账 {amount}。",
    "approve.decodedApproveLine": "这将授权 {to} 使用 {amount}。",
    "approve.decodedUnlimited": "无限量 {symbol}",
    "approve.decodedThisToken": "此代币",
    "approve.decodedRawUnitsSuffix": " 原始单位（无法确认该代币的小数位数）",
    "approve.decodedGenericIntro": "这将以以下参数调用上方合约中的 “{fn}”：",

    "loading.text": "加载中...",

    "home.tabHome": "首页",
    "home.tabAssets": "资产",
    "home.tabActivity": "动态",
    "home.tabSend": "发送",
    "home.tapToContinue": "点击继续",
    "home.continueBtn": "继续",

    "activity.title": "动态",
    "activity.subtitle": "本钱包发送记录的本地记录，以及本设备察觉到的转入记录 -- 这里的内容都不是从服务器获取的。",
    "activity.empty": "暂无动态 -- 您发起的发送(以及本设备察觉到的转入)将显示在这里。",
    "activity.sentLabel": "已发送 {amount} {asset}",
    "activity.receivedLabel": "已收到 {amount} {asset}",
    "activity.toLabel": "至 {address}",
    "activity.statusSent": "已发送",
    "activity.tabSends": "发送",
    "activity.tabSwaps": "兑换",
    "activity.swapsSubtitle": "此设备上通过这个钱包完成的兑换的本地记录——这里的内容不会从服务器获取。",
    "activity.swapsEmpty": "还没有兑换记录——你用这个钱包完成的兑换会显示在这里。",
    "activity.swapLabel": "已将 {amountIn} {assetIn} 兑换为约 {amountOut} {assetOut}",
    "activity.statusSwapped": "已兑换",
    "activity.statusReceived": "已收到",
    "activity.receivedApproxNote": "根据余额变化检测得出 -- 为估算值，无可用交易链接",
    "activity.viewOnExplorer": "在区块浏览器中查看",

    "footer.nonCustodial": "非托管钱包 — 您的密钥永远不会离开本设备",

    "errors.passwordTooShort": "密码至少需要 8 个字符。",
    "errors.passwordMismatch": "两次输入的密码不一致。",
    "errors.unknownError": "未知错误",

    "common.sell": "出售",
    "common.seeAll": "查看全部",
    "main.showQrBtn": "显示二维码",
    "main.hideQrBtn": "隐藏二维码",
    "main.nftsTitle": "NFT",
    "main.addNftBtn": "+ 添加 NFT",
    "main.nftsEmpty": "尚未添加任何 NFT -- 点按“+ 添加 NFT”，输入合约地址和代币 ID 即可追踪。",
    "main.livePricesTitle": "实时价格",
    "main.predictionsTitle": "热门币种",
    "main.currenciesCardTitle": "货币",
    "main.exchangesCardTitle": "热门交易所",
    "addToken.quickAddLabel": "快速添加：",
    "addToken.quickAddChip": "+ {symbol}",
    "nfts.loadError": "无法加载",
    "nfts.removeTitle": "移除",
    "addNft.title": "添加 NFT",
    "addNft.description": "支持 ERC-721 和 ERC-1155。请仅从你信任的来源添加。",
    "addNft.addressLabel": "合约地址",
    "addNft.tokenIdLabel": "代币 ID",
    "addNft.tokenIdPlaceholder": "0",
    "addNft.standardLabel": "标准：",
    "addNft.invalidAddress": "请输入有效的合约地址。",
    "addNft.invalidTokenId": "请输入有效的代币 ID（非负整数）。",
    "addNft.metaWarning": "无法加载图片或名称，但你仍可以添加。",
    "addNft.noName": "（无名称）",
    "prices.watchlistToggle": "点按星标可置顶",
    "prices.cardUnavailable": "暂时无法获取价格。",
    "prices.viewPeggedCoin": "查看 {name}，与 {currency} 挂钩的稳定币",
    "prices.availableOn": "✓ 支持 {networks}",
    "coin.swapUnavailableSwitchNetwork": "{symbol} 是 {network} 的原生币。请切换网络，在那里兑换或持有。",
    "coin.swapUnavailableSwitchNetworkTracked": "你已在 {network} 上添加了 {symbol}。请切换到该网络使用。",
    "coin.swapUnavailableKnownElsewhere": "{symbol} 是 {network} 上经过验证的代币。请切换到该网络以自动添加。",
    "coin.switchNetworkBtn": "切换到 {network}",
    "coin.addOnNetworkBtn": "在 {network} 上添加",
    "coin.buyBtn": "购买 {symbol}",
    "predictions.title": "热门币种",
    "predictions.description": "CoinGecko 上当前的热门币种 -- 仅供参考。查询这些信息时不会发送你的钱包的任何信息。",
    "predictions.loading": "加载中...",
    "predictions.empty": "暂无热门币种。",
    "predictions.cardUnavailable": "暂时无法获取热门币种。",
    "predictions.volSuffix": "24 小时成交量",
    "exchanges.title": "热门交易所",
    "exchanges.description": "按 CoinGecko 信任评分排名的中心化加密货币交易所，自动刷新 -- 仅供参考。Token Exchange 是自托管钱包，绝不会通过其中任何一家路由交易；查询这些信息时不会发送你的钱包的任何信息。",
    "exchanges.loading": "加载中...",
    "exchanges.empty": "暂无交易所数据。",
    "exchanges.cardUnavailable": "暂时无法获取交易所数据。",
    "exchanges.foundedYear": "成立于 {year} 年",
    "buy.description2": "通过 Transak 购买的流程直接在应用内打开，你的收款地址已自动填入并锁定 -- 无需粘贴，购买的加密货币只能进入你自己的钱包。",
    "buy.presetNote": "已预设购买 {symbol} -- Transak 打开后你仍可选择其他资产。",
    "buy.closeWidgetBtn": "← 关闭",
    "sell.title": "出售换现金",
    "sell.description1": "出售由 Transak 提供支持，与购买使用的是同一个第三方服务 -- Token Exchange 绝不会接触你的收款信息。",
    "sell.description2": "通过 Transak 出售的流程直接在应用内打开，并为你报出现金支付金额。它会显示一个充值地址，供你发送加密货币 -- Transak 收到后会兑换并支付到你绑定的银行账户或银行卡。",
    "sell.continueBtn": "前往 Transak",
    "sell.closeWidgetBtn": "← 关闭",
    "send.contactsBtn": "联系人",
    "contacts.title": "地址簿",
    "contacts.pickerHint": "点按联系人即可将其填为收款人。",
    "contacts.namePlaceholder": "名称",
    "contacts.addBtn": "保存联系人",
    "contacts.empty": "还没有保存的联系人。",
    "contacts.removeBtn": "移除",
    "contacts.nameRequired": "请为此联系人设置名称。",
    "contacts.invalidAddress": "请输入有效的 0x 地址。",
    "send.confirmIntro": "{seconds} 秒后发送 -- 你仍可取消。",
    "send.confirmSummary": "{amount} {asset} 发送至 {to}",
    "send.newAddressWarning": "你尚未在此设备上向该地址转过账 -- 请仔细核对地址是否正确。",
    "send.cancelBtn": "取消发送",
    "send.cancelledStatus": "已取消发送 -- 未发送任何内容。",
    "send.feeEstimateLoading": "正在估算网络手续费...",
    "send.feeEstimate": "预估网络手续费：约 {fee} {symbol}（约 {usd}）",
    "send.feeEstimateNoUsd": "预估网络手续费：约 {fee} {symbol}",
    "fee.burned": "其中约 {burn} {symbol} 会被销毁（永久退出流通）",
    "send.scanBtn": "扫描二维码",
    "send.scanTitle": "扫描钱包二维码",
    "send.scanClose": "关闭",
    "send.scanHint": "请将摄像头对准钱包地址二维码。",
    "send.scanUnsupported": "此浏览器不支持扫描二维码。请改为粘贴地址。",
    "send.scanDenied": "摄像头访问被阻止。请为此网站允许使用摄像头，或粘贴地址。",
    "send.scanNoAddress": "该二维码不包含有效的钱包地址。",
    "send.scanFilled": "地址已填入。发送前请再次核对。",
    "activity.exportCsv": "导出为 CSV",
    "activity.exportEmpty": "暂无可导出的内容。",
    "settings.themeLabel": "外观",
    "settings.themeDark": "深色（默认）",
    "settings.themeLight": "浅色",
    "settings.notifyLabel": "通知",
    "settings.notifyOff": "关闭",
    "settings.notifyOn": "开启",
    "settings.notifyHint": "在交易确认、资金到账或价格提醒触发时通知你。仅在此页面于浏览器中保持打开时有效。",
    "settings.notifyUnsupported": "此浏览器不支持系统通知。你仍会在页面内看到消息。",
    "settings.notifyDenied": "浏览器设置中已阻止此网站发送通知。",
    "settings.alertLabel": "价格提醒（原生币）",
    "settings.alertAbove": "涨到高于",
    "settings.alertBelow": "跌到低于",
    "settings.alertPlaceholder": "价格",
    "settings.alertAdd": "添加",
    "settings.alertHint": "使用你的显示货币。每个提醒只触发一次，且仅在此页面保持打开时有效。",
    "settings.alertRemove": "移除提醒",
    "settings.alertBadPrice": "请输入大于零的价格。",
    "settings.alertNoFeed": "此网络目前没有可用的价格数据源。",
    "notify.txConfirmed": "交易已确认",
    "notify.txFailed": "交易失败",
    "notify.received": "已收到资金",
    "notify.priceAlert": "价格提醒",
    "swap.bridgeLink": "要换到另一条链？通过跨链桥转移资金 ↗",
    "send.feeEstimateUnavailable": "无法估算网络手续费 -- 在任何内容广播之前，你仍会看到实际手续费。",
    "send.confirmFeeLine": "网络手续费：约 {fee} {symbol}",
    "send.toPlaceholder": "0x... 或 name.eth",
    "send.resolvingName": "正在查询 {name}...",
    "send.resolvedName": "解析为 {address}",
    "send.nameNotFound": "找不到 {name} 对应的地址 -- 请核对名称，或直接粘贴地址。",
    "send.nameResolutionUnsupported": "此网络不支持名称查询 -- 请直接粘贴地址。",
    "swap.selectBtn": "选择",
    "swap.balanceLabel": "余额：{amount} {symbol}",
    "swap.maxBtn": "最大",
    "swap.quotingHint": "正在获取报价…",
    "swap.rateLabel": "汇率",
    "swap.appFeeShortLabel": "应用手续费",
    "swap.minReceivedLabel": "最少收到",
    "swap.networkFeeLabel": "网络手续费",
    "swap.gasStep_approve": "授权",
    "swap.gasStep_fee": "应用手续费转账",
    "swap.gasStep_swap": "兑换",
    "swap.gasPriceLabel": "Gas 价格",
    "swap.gasUnavailable": "不可用",
    "swap.gasLowEth": "注意：此次兑换的网络手续费约为 {need} {symbol}，但此账户只有 {have}。请先充入一点 {symbol}，否则交易将失败。",
    "swap.selectAssetTitle": "选择资产",
    "swap.selectTokenTitle": "选择代币",
    "swap.pickerSearchPlaceholder": "输入代币名称或粘贴地址",
    "swap.pickerNoFavs": "此网络上还没有加星标的代币。点按代币上的星标即可添加。",
    "swap.pickerInfoTitle": "在区块浏览器中查看",
    "swap.pickerStarTitle": "为代币加星标",
    "swap.pickerNoMatch": "此网络上没有匹配的代币。",
    "swap.pickerUseAddress": "使用此代币地址",
    "swap.pickerLoadingTokens": "正在搜索代币...",
    "swap.pickerTopTokens": "此网络上的热门代币",
    "swap.pickerSearchResults": "搜索结果",
    "swap.pickerSuggested": "推荐稳定币（发行方已验证）",
    "swap.pickerNoSwapHere": "此网络尚未启用兑换。请在上方选择其他网络。",
    "swap.noAssetsHint": "这里暂时没有可用内容。",
    "settings.walletConnectBtn": "WalletConnect",
    "settings.contactsBtn": "地址簿",
    "settings.currencyLabel": "显示货币",
    "settings.navStyleLabel": "导航样式",
    "settings.navCube": "立方体",
    "settings.navGlobe": "地球仪",
    "settings.feedbackBtn": "提交功能建议",
    "settings.sendDelayLabel": "发送延迟（取消窗口）",
    "settings.sendDelayHint": "每笔转出交易会先保留这么长时间，让你有机会在广播前取消。这只适用于在 Token Exchange 中发起的转账 -- 无法保护私钥或恢复短语已在应用之外泄露的钱包。",
    "settings.autoLockLabel": "闲置后自动锁定",
    "settings.autoLockOff": "关闭（从不自动锁定）",
    "settings.autoLock1": "1 分钟",
    "settings.autoLock5": "5 分钟",
    "settings.autoLock15": "15 分钟",
    "settings.autoLock21": "21 分钟（默认）",
    "settings.autoLock30": "30 分钟",
    "settings.autoLockHint": "在此处没有点击、点按或键盘输入达到这段时间后，自动锁定钱包 -- 否则一直开着的浏览器标签页会无限期保持解锁状态。",
    "settings.sendDelayOff": "关闭（立即发送）",
    "settings.sendDelay15": "15 秒",
    "settings.sendDelay30": "30 秒（推荐）",
    "settings.sendDelay60": "60 秒",
    "feedback.title": "功能建议",
    "feedback.subtitle": "看看其他用户在期待什么，为你也想要的功能投票，或发布你自己的建议。此列表是公开的 -- 我们据此决定接下来开发什么。",
    "feedback.titlePlaceholder": "简短标题（例如“深色模式”）",
    "feedback.descPlaceholder": "再补充一些细节（可选）",
    "feedback.submitBtn": "发布建议",
    "feedback.submittingStatus": "发布中...",
    "feedback.submittedStatus": "谢谢！你的建议已发布在下方。",
    "feedback.listTitle": "建议列表",
    "feedback.empty": "还没有建议 -- 来做第一个吧！",
    "feedback.loadError": "无法加载建议。请稍后再试。",
    "feedback.titleRequired": "请先填写一个简短标题。",
    "feedback.upvoteBtn": "点赞",
    "feedback.upvotedBtn": "已点赞",
    "feedback.contactLine": "更喜欢电子邮件？请联系 msandersod@gmail.com",
    "wc.title": "WalletConnect",
    "wc.subtitle": "连接任何提供“WalletConnect”选项的 dapp -- 在下方粘贴其连接钱包二维码中的 wc:... URI。",
    "wc.uriPlaceholder": "wc:...",
    "wc.connectBtn": "连接",
    "wc.notConfigured": "WalletConnect 需要一个免费的项目 ID 才能连接任何内容 -- 请参阅 lib/walletconnect-config.js。",
    "wc.sessionsTitle": "已连接的 dapp",
    "wc.sessionsEmpty": "尚未连接任何 dapp。",
    "wc.disconnectBtn": "断开连接",
    "wc.invalidUri": "这看起来不像 WalletConnect URI -- 它应以“wc:”开头。",
    "wc.pairingStatus": "配对中... 连接请求稍后应会出现。",
    "wc.pairedStatus": "已配对 -- 请留意是否弹出新窗口，请求你批准连接。",
    "swap.appFeeValue": "{percent} ({amount} {symbol})",
    "main.findNftsBtn": "🔍 查找 NFT",
    "findNfts.title": "查找 NFT",
    "findNfts.description": "通过 Alchemy 的 NFT API 扫描此账户在当前网络上的地址，并列出其持有的内容。此操作只读取公开的链上所有权数据 -- 除了你已在使用的地址外，不会向任何地方发送你的钱包的任何信息。",
    "findNfts.loadMore": "加载更多",
    "swap.flipBtnTitle": "切换兑换方向",
    "findNfts.loading": "正在查找 NFT...",
    "findNfts.notConfigured": "此服务器尚未设置 NFT 查询。",
    "findNfts.notSupported": "此网络不支持 NFT 查询。",
    "findNfts.empty": "在此网络上未找到此账户的 NFT。",
    "findNfts.loadError": "无法加载 NFT。请稍后再试。",
    "findNfts.addedBtn": "已添加",
    "findNfts.addBtn": "添加到我的 NFT",
  };

  const faq = [
    {
      id: "create-wallet",
      chip: "如何创建钱包？",
      keywords: ["创建钱包", "新建钱包", "怎么创建钱包", "如何创建钱包", "设置钱包", "新手", "第一次使用"],
      answer: "在欢迎页面点击「创建新钱包」，设置一个密码（该密码仅用于解锁本设备上的钱包，无法用来找回资金），随后系统会显示一组 12 个单词的助记词。请先将它抄写并妥善保存后再继续——如果这台设备日后丢失或损坏，这组助记词是找回资金的唯一方式。",
    },
    {
      id: "import-wallet",
      chip: "如何导入已有钱包？",
      keywords: ["导入钱包", "导入已有钱包", "恢复钱包", "导入助记词", "导入种子短语", "已有钱包怎么导入"],
      answer: "在欢迎页面点击「导入已有钱包」，按原样输入您的 12 个或 24 个单词的助记词（全部小写，以空格分隔），然后为本设备设置一个新密码。助记词本身不会离开您的设备——它仅在本地用于生成您的账户。",
    },
    {
      id: "forgot-password",
      chip: "我忘记密码了",
      keywords: ["忘记密码", "密码忘了", "密码错误", "无法解锁", "打不开钱包", "密码不对", "登录不了"],
      answer: "您的密码仅用于解锁本设备上的钱包——Token Exchange 从不存储该密码，也无法为您重置。如果您想不起密码，请在解锁页面点击「改为重置钱包」，然后使用您的 12 个单词助记词重新导入钱包。如果您没有保存助记词，那么很遗憾，此钱包中的资金将无法找回——这正是非托管钱包的代价：除了您本人，没有任何人能解锁它，这也意味着除了您本人，没有任何人能挽救它。",
    },
    {
      id: "lost-seed-phrase",
      chip: "我的助记词丢失了",
      keywords: ["助记词丢了", "丢失助记词", "没有备份助记词", "忘记保存助记词", "种子短语丢了", "没抄助记词"],
      answer: "如果您目前仍处于登录状态，请前往「设置 → 查看助记词」，重新输入密码，并立即将其抄写并妥善保存。如果您已被锁定在钱包之外，且此前从未保存过助记词，那么该钱包及其中的资金将无法找回。Token Exchange 从不会将您的助记词存储在任何地方——无论是服务器、云端还是其他任何位置——因此包括开发者在内，没有任何人能替您找回它。",
    },
    {
      id: "balance-not-showing",
      chip: "我的余额没有显示",
      keywords: ["余额不显示", "余额为零", "余额不对", "余额一直加载", "余额显示0", "查不到余额"],
      answer: "如果余额一直显示为「...」，通常是该网络的 RPC 节点响应缓慢或暂时不可用——本钱包会在几秒后自动重试备用节点，一般会自行恢复正常。如果余额最终显示为 0 但您认为不对，请仔细检查是否选择了正确的网络和账户（这两个下拉菜单都在主界面上）——余额是按网络和账户分别统计的，例如当前选择 Ethereum Mainnet 时，Base 上的资产是不会显示出来的。",
    },
    {
      id: "swap-failed",
      chip: "我的兑换失败了",
      keywords: ["兑换失败", "闪兑失败", "兑换出错", "兑换卡住", "报价失败", "兑换不成功"],
      answer: "兑换是通过公开的去中心化交易所路由合约在链上完成的，因此失败通常是以下三种情况之一：余额不足以支付兑换金额加燃料费（gas 费）、在价格波动较快时滑点容差设置过紧（可尝试将 0.5% 调整为 1% 或 3%），或者该交易对在该网络路由上的流动性尚不充足。点击「获取报价」后兑换页面显示的错误信息通常会说明具体原因——如果不确定，可以先尝试用较小的金额重试。",
    },
    {
      id: "swap-fee",
      chip: "兑换需要支付什么费用？",
      keywords: ["兑换手续费", "兑换费用", "闪兑手续费", "手续费多少", "0.5%手续费", "收费多少"],
      answer: "每笔兑换会收取固定 0.5% 的手续费，在您确认之前会在报价中清楚显示——这笔费用是兑换交易本身的一部分，绝不会被隐藏在汇率里。这与燃料费（gas 费）是分开的，燃料费支付给区块链网络，而不是 Token Exchange。",
    },
    {
      id: "gas-fees",
      chip: "什么是燃料费（gas 费）？",
      keywords: ["燃料费", "gas费", "网络手续费", "交易费", "什么是gas"],
      answer: "燃料费（gas 费）是区块链网络本身为处理交易而收取的费用——它与 Token Exchange 的 0.5% 兑换手续费无关，全部支付给网络，而非我们。费用高低会随当时的网络拥堵程度变化。请确保您持有足够数量的该网络原生币（如 ETH、BNB、POL 等）以支付燃料费，即使您发送的是代币而非原生币，也同样需要用原生币支付燃料费。",
    },
    {
      id: "add-network",
      chip: "如何添加网络？",
      keywords: ["添加网络", "新增网络", "自定义网络", "添加链", "切换到其他链"],
      answer: "前往「设置 → 添加网络」，填写网络名称、链 ID、RPC URL 以及原生代币符号。如果您同时填写了经过验证的兑换路由合约地址，该网络也将支持兑换功能——否则该网络将仅支持收发功能。请务必只填写您已亲自对照该网络官方文档或区块浏览器核实过的信息。",
    },
    {
      id: "add-token",
      chip: "如何添加代币追踪？",
      keywords: ["添加代币", "追踪代币", "自定义代币", "添加ERC20", "erc-20代币"],
      answer: "在主界面点击「+ 添加代币」，粘贴该代币在当前网络上的合约地址，然后点击「查询」——系统会直接从合约中读取代币的名称、符号和小数位数，供您确认后再添加。请仅添加来自可信来源的合约地址；钱包无法分辨真代币与使用相同名称和符号的仿冒代币。",
    },
    {
      id: "send-crypto",
      chip: "如何发送加密货币？",
      keywords: ["怎么发送", "发送加密货币", "转账", "发送代币", "转账eth", "如何转账"],
      answer: "在主界面点击「发送」，选择原生币或代币（通过合约地址选择），输入收款地址和金额，然后确认。请在确认前仔细核对地址——这些网络上的转账一经完成即不可撤销。",
    },
    {
      id: "connect-dapp",
      chip: "如何连接到网站？",
      keywords: ["连接dapp", "连接网站", "连接钱包按钮", "无法连接", "连不上钱包"],
      answer: "任何带有「连接钱包」按钮且支持浏览器钱包扩展的网站，都应当像识别 MetaMask 或 Coinbase Wallet 一样识别 Token Exchange。如果某个网站没有将其列为可选项，请在钱包安装并解锁后刷新页面重试——部分网站只会在页面加载时检测钱包扩展。",
    },
    {
      id: "buy-not-working",
      chip: "购买功能无法使用",
      keywords: ["购买按钮", "购买不能用", "购买没反应", "moonpay", "无法购买", "买不了"],
      answer: "「购买」按钮会在新标签页中打开第三方法币入金服务 MoonPay。如果提示「购买功能尚未配置」，说明本钱包的开发者尚未添加 MoonPay API 密钥——这不是您在钱包内部可以解决的问题。配置完成后，您需要自行将收款地址粘贴到 MoonPay 页面中；Token Exchange 不会代您发送该地址。",
    },
    {
      id: "reset-wallet",
      chip: "如何重置我的钱包？",
      keywords: ["重置钱包", "删除钱包", "清空钱包", "重新开始", "移除钱包"],
      answer: "「设置 → 重置钱包」会永久删除该浏览器中已加密的钱包数据。请务必先确认您已备份好助记词——此操作无法撤销，一旦执行，若没有助记词将无法再找回该钱包。",
    },
    {
      id: "is-it-safe",
      chip: "这个钱包安全吗？",
      keywords: ["安全吗", "靠谱吗", "是骗局吗", "非托管", "会不会是诈骗", "值得信任吗"],
      answer: "Token Exchange 是一款非托管钱包：您的助记词和私钥经过加密后仅存储在您的浏览器中——绝不会发送到任何服务器，因为本产品根本没有服务器。这也意味着，如果您同时丢失密码和助记词，包括开发者在内的任何人都无法帮您找回资金。发送和兑换在发出前都会在本地对照内置的制裁名单进行检查，且兑换手续费始终会在您确认前提前展示。",
    },
    {
      id: "pending-transaction",
      chip: "我的交易卡住了",
      keywords: ["交易卡住", "交易一直待确认", "交易不确认", "交易pending", "一直显示待处理"],
      answer: "如果网络拥堵，或交易使用的燃料费价格相对当前情况偏低，交易可能会长时间处于「待处理」状态，通常最终仍会自行确认。如果长时间未能确认，您可以使用账户地址在该网络的区块浏览器上查询该交易的实时状态。",
    },
    {
      id: "wrong-network",
      chip: "支持哪些网络？",
      keywords: ["支持哪些网络", "切换网络", "支持的链", "有哪些网络", "网络选错了"],
      answer: "内置支持：Ethereum、Base、Polygon、BNB Chain、Arbitrum One 和 OP Mainnet，可通过主界面底部附近的下拉菜单切换——您的余额、代币和兑换选项都对应于当前选中的网络。您也可以通过「设置 → 添加网络」自行添加任何其他兼容 EVM 的网络。",
    },
    {
      id: "contact-human",
      chip: "我需要更多帮助",
      keywords: ["联系人工", "真人客服", "联系支持", "联系客服", "还需要帮助", "转人工"],
      answer: "__CONTACT_FALLBACK__",
    },
  ];

  const greeting = "您好！我是内置的简易帮助机器人——我只能回答预先编写好的固定问题列表中的内容，仅此而已。请点击下方主题，或输入您自己的问题。";
  const fallbackWithEmail = "我目前还没有针对这个问题的现成答案。您可以通过 {email} 联系人工客服——建议说明您当时所在的界面以及您期望发生的情况，这样会更有帮助。";
  const fallbackNoEmail = "我目前还没有针对这个问题的现成答案，而且本钱包尚未设置人工客服渠道。您可以尝试换一种方式描述问题，或查阅该扩展的 README 文件，了解各项功能的详细说明。";

  self.TM_I18N_DATA = self.TM_I18N_DATA || {};
  self.TM_I18N_DATA.zh = {
    name: "中文（简体）",
    dir: "ltr",
    strings,
    faq,
    greeting,
    fallbackWithEmail,
    fallbackNoEmail,
  };
})();
